// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_events.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivityEvents = `-- name: CountActivityEvents :one
SELECT COUNT(*)::bigint FROM activity_events
WHERE ($1::bigint IS NULL OR actor_user_id = $1)
  AND ($2::text IS NULL OR resource = $2)
  AND ($3::text IS NULL OR action = $3)
  AND (
    $4::text IS NULL
    OR action ILIKE '%' || $4 || '%'
    OR resource ILIKE '%' || $4 || '%'
  )
`

type CountActivityEventsParams struct {
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	Resource    pgtype.Text `json:"resource"`
	Action      pgtype.Text `json:"action"`
	Q           pgtype.Text `json:"q"`
}

func (q *Queries) CountActivityEvents(ctx context.Context, arg CountActivityEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityEvents,
		arg.ActorUserID,
		arg.Resource,
		arg.Action,
		arg.Q,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertActivityEvent = `-- name: InsertActivityEvent :one
INSERT INTO activity_events (actor_user_id, action, resource, resource_uuid, payload, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, uuid, actor_user_id, action, resource, resource_uuid, payload, ip_address, user_agent, created_at
`

type InsertActivityEventParams struct {
	ActorUserID  pgtype.Int8 `json:"actor_user_id"`
	Action       string      `json:"action"`
	Resource     string      `json:"resource"`
	ResourceUuid pgtype.UUID `json:"resource_uuid"`
	Payload      []byte      `json:"payload"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertActivityEvent(ctx context.Context, arg InsertActivityEventParams) (ActivityEvent, error) {
	row := q.db.QueryRow(ctx, insertActivityEvent,
		arg.ActorUserID,
		arg.Action,
		arg.Resource,
		arg.ResourceUuid,
		arg.Payload,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i ActivityEvent
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ActorUserID,
		&i.Action,
		&i.Resource,
		&i.ResourceUuid,
		&i.Payload,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listActivityEvents = `-- name: ListActivityEvents :many
SELECT id, uuid, actor_user_id, action, resource, resource_uuid, payload, ip_address, user_agent, created_at FROM activity_events
WHERE ($1::bigint IS NULL OR actor_user_id = $1)
  AND ($2::text IS NULL OR resource = $2)
  AND ($3::text IS NULL OR action = $3)
  AND (
    $4::text IS NULL
    OR action ILIKE '%' || $4 || '%'
    OR resource ILIKE '%' || $4 || '%'
  )
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListActivityEventsParams struct {
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	Resource    pgtype.Text `json:"resource"`
	Action      pgtype.Text `json:"action"`
	Q           pgtype.Text `json:"q"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListActivityEvents(ctx context.Context, arg ListActivityEventsParams) ([]ActivityEvent, error) {
	rows, err := q.db.Query(ctx, listActivityEvents,
		arg.ActorUserID,
		arg.Resource,
		arg.Action,
		arg.Q,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityEvent{}
	for rows.Next() {
		var i ActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ActorUserID,
			&i.Action,
			&i.Resource,
			&i.ResourceUuid,
			&i.Payload,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
