// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_tokens.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at, user_agent, ip_address, impersonator_user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uuid, user_id, token_hash, expires_at, revoked_at, user_agent, ip_address, impersonator_user_id, created_at
`

type CreateRefreshTokenParams struct {
	UserID             int64              `json:"user_id"`
	TokenHash          string             `json:"token_hash"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	UserAgent          pgtype.Text        `json:"user_agent"`
	IpAddress          *netip.Addr        `json:"ip_address"`
	ImpersonatorUserID pgtype.Int8        `json:"impersonator_user_id"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
		arg.ImpersonatorUserID,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.ImpersonatorUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getValidRefreshTokenByHash = `-- name: GetValidRefreshTokenByHash :one
SELECT id, uuid, user_id, token_hash, expires_at, revoked_at, user_agent, ip_address, impersonator_user_id, created_at
FROM refresh_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetValidRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getValidRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.ImpersonatorUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveRefreshTokensByUserID = `-- name: ListActiveRefreshTokensByUserID :many
SELECT id, uuid, user_id, token_hash, expires_at, revoked_at, user_agent, ip_address, impersonator_user_id, created_at
FROM refresh_tokens
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListActiveRefreshTokensByUserID(ctx context.Context, userID int64) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, listActiveRefreshTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefreshToken{}
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.UserAgent,
			&i.IpAddress,
			&i.ImpersonatorUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForUser, userID)
	return err
}

const revokeOtherRefreshTokensForUser = `-- name: RevokeOtherRefreshTokensForUser :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1
  AND uuid <> $2
  AND revoked_at IS NULL
`

type RevokeOtherRefreshTokensForUserParams struct {
	UserID int64     `json:"user_id"`
	Uuid   uuid.UUID `json:"uuid"`
}

func (q *Queries) RevokeOtherRefreshTokensForUser(ctx context.Context, arg RevokeOtherRefreshTokensForUserParams) error {
	_, err := q.db.Exec(ctx, revokeOtherRefreshTokensForUser, arg.UserID, arg.Uuid)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByHash, tokenHash)
	return err
}

const revokeRefreshTokenByUUIDForUser = `-- name: RevokeRefreshTokenByUUIDForUser :execrows
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE uuid = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type RevokeRefreshTokenByUUIDForUserParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	UserID int64     `json:"user_id"`
}

func (q *Queries) RevokeRefreshTokenByUUIDForUser(ctx context.Context, arg RevokeRefreshTokenByUUIDForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenByUUIDForUser, arg.Uuid, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
