// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuthSettings = `-- name: GetAuthSettings :one
SELECT
    s.id, s.registration_enabled, s.default_role_id, s.password_login_enabled, s.password_register_enabled, s.passkey_login_enabled, s.created_at, s.updated_at,
    r.uuid AS default_role_uuid,
    r.name AS default_role_name,
    r.slug AS default_role_slug
FROM auth_settings s
LEFT JOIN roles r ON r.id = s.default_role_id
WHERE s.id = 1
`

type GetAuthSettingsRow struct {
	ID                      int16              `json:"id"`
	RegistrationEnabled     bool               `json:"registration_enabled"`
	DefaultRoleID           pgtype.Int8        `json:"default_role_id"`
	PasswordLoginEnabled    bool               `json:"password_login_enabled"`
	PasswordRegisterEnabled bool               `json:"password_register_enabled"`
	PasskeyLoginEnabled     bool               `json:"passkey_login_enabled"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	DefaultRoleUuid         pgtype.UUID        `json:"default_role_uuid"`
	DefaultRoleName         pgtype.Text        `json:"default_role_name"`
	DefaultRoleSlug         pgtype.Text        `json:"default_role_slug"`
}

func (q *Queries) GetAuthSettings(ctx context.Context) (GetAuthSettingsRow, error) {
	row := q.db.QueryRow(ctx, getAuthSettings)
	var i GetAuthSettingsRow
	err := row.Scan(
		&i.ID,
		&i.RegistrationEnabled,
		&i.DefaultRoleID,
		&i.PasswordLoginEnabled,
		&i.PasswordRegisterEnabled,
		&i.PasskeyLoginEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultRoleUuid,
		&i.DefaultRoleName,
		&i.DefaultRoleSlug,
	)
	return i, err
}

const updateAuthSettings = `-- name: UpdateAuthSettings :one
UPDATE auth_settings
SET registration_enabled = $1,
    default_role_id = $2,
    password_login_enabled = $3,
    password_register_enabled = $4,
    passkey_login_enabled = $5
WHERE id = 1
RETURNING id, registration_enabled, default_role_id, password_login_enabled, password_register_enabled, passkey_login_enabled, created_at, updated_at
`

type UpdateAuthSettingsParams struct {
	RegistrationEnabled     bool        `json:"registration_enabled"`
	DefaultRoleID           pgtype.Int8 `json:"default_role_id"`
	PasswordLoginEnabled    bool        `json:"password_login_enabled"`
	PasswordRegisterEnabled bool        `json:"password_register_enabled"`
	PasskeyLoginEnabled     bool        `json:"passkey_login_enabled"`
}

func (q *Queries) UpdateAuthSettings(ctx context.Context, arg UpdateAuthSettingsParams) (AuthSetting, error) {
	row := q.db.QueryRow(ctx, updateAuthSettings,
		arg.RegistrationEnabled,
		arg.DefaultRoleID,
		arg.PasswordLoginEnabled,
		arg.PasswordRegisterEnabled,
		arg.PasskeyLoginEnabled,
	)
	var i AuthSetting
	err := row.Scan(
		&i.ID,
		&i.RegistrationEnabled,
		&i.DefaultRoleID,
		&i.PasswordLoginEnabled,
		&i.PasswordRegisterEnabled,
		&i.PasskeyLoginEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
