// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cari.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adjustCariAccountBalance = `-- name: AdjustCariAccountBalance :one
UPDATE cari_accounts
SET balance = balance + $3
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
RETURNING id, uuid, organization_id, customer_id, currency, balance, is_active, created_at, updated_at, deleted_at
`

type AdjustCariAccountBalanceParams struct {
	ID             int64          `json:"id"`
	OrganizationID int64          `json:"organization_id"`
	Balance        pgtype.Numeric `json:"balance"`
}

func (q *Queries) AdjustCariAccountBalance(ctx context.Context, arg AdjustCariAccountBalanceParams) (CariAccount, error) {
	row := q.db.QueryRow(ctx, adjustCariAccountBalance, arg.ID, arg.OrganizationID, arg.Balance)
	var i CariAccount
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.Currency,
		&i.Balance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countCariAccounts = `-- name: CountCariAccounts :one
SELECT COUNT(*)::bigint
FROM cari_accounts a
JOIN customers c ON c.id = a.customer_id AND c.deleted_at IS NULL
WHERE a.organization_id = $1 AND a.deleted_at IS NULL
  AND ($2::boolean IS NULL OR a.is_active = $2)
  AND (
    $3::boolean IS NULL
    OR ($3 = true AND a.balance <> 0)
    OR ($3 = false AND a.balance = 0)
  )
  AND (
    $4::text IS NULL
    OR c.name ILIKE '%' || $4 || '%'
    OR c.phone ILIKE '%' || $4 || '%'
    OR c.email ILIKE '%' || $4 || '%'
  )
`

type CountCariAccountsParams struct {
	OrganizationID int64       `json:"organization_id"`
	IsActive       pgtype.Bool `json:"is_active"`
	HasBalance     pgtype.Bool `json:"has_balance"`
	Q              pgtype.Text `json:"q"`
}

func (q *Queries) CountCariAccounts(ctx context.Context, arg CountCariAccountsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCariAccounts,
		arg.OrganizationID,
		arg.IsActive,
		arg.HasBalance,
		arg.Q,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countCariEntries = `-- name: CountCariEntries :one
SELECT COUNT(*)::bigint
FROM cari_entries e
WHERE e.organization_id = $1
  AND e.account_id = $2
  AND ($3::text IS NULL OR e.type = $3)
  AND ($4::text IS NULL OR e.status = $4)
  AND ($5::date IS NULL OR e.entry_date >= $5)
  AND ($6::date IS NULL OR e.entry_date <= $6)
  AND (
    $7::text IS NULL
    OR e.description ILIKE '%' || $7 || '%'
    OR e.reference_no ILIKE '%' || $7 || '%'
  )
`

type CountCariEntriesParams struct {
	OrganizationID int64       `json:"organization_id"`
	AccountID      int64       `json:"account_id"`
	Type           pgtype.Text `json:"type"`
	Status         pgtype.Text `json:"status"`
	DateFrom       pgtype.Date `json:"date_from"`
	DateTo         pgtype.Date `json:"date_to"`
	Q              pgtype.Text `json:"q"`
}

func (q *Queries) CountCariEntries(ctx context.Context, arg CountCariEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCariEntries,
		arg.OrganizationID,
		arg.AccountID,
		arg.Type,
		arg.Status,
		arg.DateFrom,
		arg.DateTo,
		arg.Q,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCariAccount = `-- name: CreateCariAccount :one

INSERT INTO cari_accounts (
    organization_id, customer_id, currency, balance, is_active
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, uuid, organization_id, customer_id, currency, balance, is_active, created_at, updated_at, deleted_at
`

type CreateCariAccountParams struct {
	OrganizationID int64          `json:"organization_id"`
	CustomerID     int64          `json:"customer_id"`
	Currency       string         `json:"currency"`
	Balance        pgtype.Numeric `json:"balance"`
	IsActive       bool           `json:"is_active"`
}

// Tenant cari (accounts receivable) accounts and ledger entries.
func (q *Queries) CreateCariAccount(ctx context.Context, arg CreateCariAccountParams) (CariAccount, error) {
	row := q.db.QueryRow(ctx, createCariAccount,
		arg.OrganizationID,
		arg.CustomerID,
		arg.Currency,
		arg.Balance,
		arg.IsActive,
	)
	var i CariAccount
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.Currency,
		&i.Balance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createCariEntry = `-- name: CreateCariEntry :one
INSERT INTO cari_entries (
    organization_id, account_id, type, amount, balance_after, entry_date,
    description, reference_no, payment_method, finance_account_id, finance_transaction_id,
    created_by, source_type, source_uuid, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, uuid, organization_id, account_id, type, status, amount, balance_after, entry_date, description, reference_no, payment_method, finance_account_id, finance_transaction_id, created_by, voided_at, voided_by, source_type, source_uuid, metadata, created_at, updated_at
`

type CreateCariEntryParams struct {
	OrganizationID       int64          `json:"organization_id"`
	AccountID            int64          `json:"account_id"`
	Type                 string         `json:"type"`
	Amount               pgtype.Numeric `json:"amount"`
	BalanceAfter         pgtype.Numeric `json:"balance_after"`
	EntryDate            pgtype.Date    `json:"entry_date"`
	Description          string         `json:"description"`
	ReferenceNo          pgtype.Text    `json:"reference_no"`
	PaymentMethod        pgtype.Text    `json:"payment_method"`
	FinanceAccountID     pgtype.Int8    `json:"finance_account_id"`
	FinanceTransactionID pgtype.Int8    `json:"finance_transaction_id"`
	CreatedBy            int64          `json:"created_by"`
	SourceType           pgtype.Text    `json:"source_type"`
	SourceUuid           pgtype.UUID    `json:"source_uuid"`
	Metadata             []byte         `json:"metadata"`
}

func (q *Queries) CreateCariEntry(ctx context.Context, arg CreateCariEntryParams) (CariEntry, error) {
	row := q.db.QueryRow(ctx, createCariEntry,
		arg.OrganizationID,
		arg.AccountID,
		arg.Type,
		arg.Amount,
		arg.BalanceAfter,
		arg.EntryDate,
		arg.Description,
		arg.ReferenceNo,
		arg.PaymentMethod,
		arg.FinanceAccountID,
		arg.FinanceTransactionID,
		arg.CreatedBy,
		arg.SourceType,
		arg.SourceUuid,
		arg.Metadata,
	)
	var i CariEntry
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.AccountID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.BalanceAfter,
		&i.EntryDate,
		&i.Description,
		&i.ReferenceNo,
		&i.PaymentMethod,
		&i.FinanceAccountID,
		&i.FinanceTransactionID,
		&i.CreatedBy,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.SourceType,
		&i.SourceUuid,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCariAccountByCustomerID = `-- name: GetCariAccountByCustomerID :one
SELECT id, uuid, organization_id, customer_id, currency, balance, is_active, created_at, updated_at, deleted_at FROM cari_accounts
WHERE customer_id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type GetCariAccountByCustomerIDParams struct {
	CustomerID     int64 `json:"customer_id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) GetCariAccountByCustomerID(ctx context.Context, arg GetCariAccountByCustomerIDParams) (CariAccount, error) {
	row := q.db.QueryRow(ctx, getCariAccountByCustomerID, arg.CustomerID, arg.OrganizationID)
	var i CariAccount
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.Currency,
		&i.Balance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCariAccountByID = `-- name: GetCariAccountByID :one
SELECT id, uuid, organization_id, customer_id, currency, balance, is_active, created_at, updated_at, deleted_at FROM cari_accounts
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type GetCariAccountByIDParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) GetCariAccountByID(ctx context.Context, arg GetCariAccountByIDParams) (CariAccount, error) {
	row := q.db.QueryRow(ctx, getCariAccountByID, arg.ID, arg.OrganizationID)
	var i CariAccount
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.Currency,
		&i.Balance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCariAccountByUUID = `-- name: GetCariAccountByUUID :one
SELECT a.id, a.uuid, a.organization_id, a.customer_id, a.currency, a.balance, a.is_active, a.created_at, a.updated_at, a.deleted_at,
       c.uuid AS customer_uuid,
       c.name AS customer_name,
       c.phone AS customer_phone,
       c.email AS customer_email,
       c.kind AS customer_kind,
       c.tax_id AS customer_tax_id,
       c.tax_office AS customer_tax_office,
       c.is_active AS customer_is_active
FROM cari_accounts a
JOIN customers c ON c.id = a.customer_id
WHERE a.uuid = $1 AND a.organization_id = $2 AND a.deleted_at IS NULL
`

type GetCariAccountByUUIDParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

type GetCariAccountByUUIDRow struct {
	ID                int64              `json:"id"`
	Uuid              uuid.UUID          `json:"uuid"`
	OrganizationID    int64              `json:"organization_id"`
	CustomerID        int64              `json:"customer_id"`
	Currency          string             `json:"currency"`
	Balance           pgtype.Numeric     `json:"balance"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CustomerUuid      uuid.UUID          `json:"customer_uuid"`
	CustomerName      string             `json:"customer_name"`
	CustomerPhone     string             `json:"customer_phone"`
	CustomerEmail     string             `json:"customer_email"`
	CustomerKind      string             `json:"customer_kind"`
	CustomerTaxID     string             `json:"customer_tax_id"`
	CustomerTaxOffice string             `json:"customer_tax_office"`
	CustomerIsActive  bool               `json:"customer_is_active"`
}

func (q *Queries) GetCariAccountByUUID(ctx context.Context, arg GetCariAccountByUUIDParams) (GetCariAccountByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getCariAccountByUUID, arg.Uuid, arg.OrganizationID)
	var i GetCariAccountByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.Currency,
		&i.Balance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CustomerUuid,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerEmail,
		&i.CustomerKind,
		&i.CustomerTaxID,
		&i.CustomerTaxOffice,
		&i.CustomerIsActive,
	)
	return i, err
}

const getCariAccountForSearch = `-- name: GetCariAccountForSearch :one
SELECT a.uuid, a.balance, a.currency, a.is_active, a.organization_id,
       c.name AS customer_name, c.phone AS customer_phone,
       o.uuid AS organization_uuid, o.slug AS organization_slug
FROM cari_accounts a
JOIN customers c ON c.id = a.customer_id AND c.deleted_at IS NULL
JOIN organizations o ON o.id = a.organization_id
WHERE a.uuid = $1 AND o.uuid = $2 AND a.deleted_at IS NULL
`

type GetCariAccountForSearchParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	Uuid_2 uuid.UUID `json:"uuid_2"`
}

type GetCariAccountForSearchRow struct {
	Uuid             uuid.UUID      `json:"uuid"`
	Balance          pgtype.Numeric `json:"balance"`
	Currency         string         `json:"currency"`
	IsActive         bool           `json:"is_active"`
	OrganizationID   int64          `json:"organization_id"`
	CustomerName     string         `json:"customer_name"`
	CustomerPhone    string         `json:"customer_phone"`
	OrganizationUuid uuid.UUID      `json:"organization_uuid"`
	OrganizationSlug string         `json:"organization_slug"`
}

func (q *Queries) GetCariAccountForSearch(ctx context.Context, arg GetCariAccountForSearchParams) (GetCariAccountForSearchRow, error) {
	row := q.db.QueryRow(ctx, getCariAccountForSearch, arg.Uuid, arg.Uuid_2)
	var i GetCariAccountForSearchRow
	err := row.Scan(
		&i.Uuid,
		&i.Balance,
		&i.Currency,
		&i.IsActive,
		&i.OrganizationID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.OrganizationUuid,
		&i.OrganizationSlug,
	)
	return i, err
}

const getCariEntryBySource = `-- name: GetCariEntryBySource :one
SELECT id, uuid, organization_id, account_id, type, status, amount, balance_after, entry_date, description, reference_no, payment_method, finance_account_id, finance_transaction_id, created_by, voided_at, voided_by, source_type, source_uuid, metadata, created_at, updated_at FROM cari_entries
WHERE organization_id = $1
  AND source_type = $2
  AND source_uuid = $3
  AND status = 'posted'
LIMIT 1
`

type GetCariEntryBySourceParams struct {
	OrganizationID int64       `json:"organization_id"`
	SourceType     pgtype.Text `json:"source_type"`
	SourceUuid     pgtype.UUID `json:"source_uuid"`
}

func (q *Queries) GetCariEntryBySource(ctx context.Context, arg GetCariEntryBySourceParams) (CariEntry, error) {
	row := q.db.QueryRow(ctx, getCariEntryBySource, arg.OrganizationID, arg.SourceType, arg.SourceUuid)
	var i CariEntry
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.AccountID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.BalanceAfter,
		&i.EntryDate,
		&i.Description,
		&i.ReferenceNo,
		&i.PaymentMethod,
		&i.FinanceAccountID,
		&i.FinanceTransactionID,
		&i.CreatedBy,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.SourceType,
		&i.SourceUuid,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCariEntryByUUID = `-- name: GetCariEntryByUUID :one
SELECT e.id, e.uuid, e.organization_id, e.account_id, e.type, e.status, e.amount, e.balance_after, e.entry_date, e.description, e.reference_no, e.payment_method, e.finance_account_id, e.finance_transaction_id, e.created_by, e.voided_at, e.voided_by, e.source_type, e.source_uuid, e.metadata, e.created_at, e.updated_at,
       a.uuid AS account_uuid,
       c.uuid AS customer_uuid,
       c.name AS customer_name,
       fa.uuid AS finance_account_uuid,
       fa.name AS finance_account_name,
       ft.uuid AS finance_transaction_uuid
FROM cari_entries e
JOIN cari_accounts a ON a.id = e.account_id
JOIN customers c ON c.id = a.customer_id
LEFT JOIN finance_accounts fa ON fa.id = e.finance_account_id
LEFT JOIN finance_transactions ft ON ft.id = e.finance_transaction_id
WHERE e.uuid = $1 AND e.organization_id = $2
`

type GetCariEntryByUUIDParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

type GetCariEntryByUUIDRow struct {
	ID                     int64              `json:"id"`
	Uuid                   uuid.UUID          `json:"uuid"`
	OrganizationID         int64              `json:"organization_id"`
	AccountID              int64              `json:"account_id"`
	Type                   string             `json:"type"`
	Status                 string             `json:"status"`
	Amount                 pgtype.Numeric     `json:"amount"`
	BalanceAfter           pgtype.Numeric     `json:"balance_after"`
	EntryDate              pgtype.Date        `json:"entry_date"`
	Description            string             `json:"description"`
	ReferenceNo            pgtype.Text        `json:"reference_no"`
	PaymentMethod          pgtype.Text        `json:"payment_method"`
	FinanceAccountID       pgtype.Int8        `json:"finance_account_id"`
	FinanceTransactionID   pgtype.Int8        `json:"finance_transaction_id"`
	CreatedBy              int64              `json:"created_by"`
	VoidedAt               pgtype.Timestamptz `json:"voided_at"`
	VoidedBy               pgtype.Int8        `json:"voided_by"`
	SourceType             pgtype.Text        `json:"source_type"`
	SourceUuid             pgtype.UUID        `json:"source_uuid"`
	Metadata               []byte             `json:"metadata"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	AccountUuid            uuid.UUID          `json:"account_uuid"`
	CustomerUuid           uuid.UUID          `json:"customer_uuid"`
	CustomerName           string             `json:"customer_name"`
	FinanceAccountUuid     pgtype.UUID        `json:"finance_account_uuid"`
	FinanceAccountName     pgtype.Text        `json:"finance_account_name"`
	FinanceTransactionUuid pgtype.UUID        `json:"finance_transaction_uuid"`
}

func (q *Queries) GetCariEntryByUUID(ctx context.Context, arg GetCariEntryByUUIDParams) (GetCariEntryByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getCariEntryByUUID, arg.Uuid, arg.OrganizationID)
	var i GetCariEntryByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.AccountID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.BalanceAfter,
		&i.EntryDate,
		&i.Description,
		&i.ReferenceNo,
		&i.PaymentMethod,
		&i.FinanceAccountID,
		&i.FinanceTransactionID,
		&i.CreatedBy,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.SourceType,
		&i.SourceUuid,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountUuid,
		&i.CustomerUuid,
		&i.CustomerName,
		&i.FinanceAccountUuid,
		&i.FinanceAccountName,
		&i.FinanceTransactionUuid,
	)
	return i, err
}

const linkCariEntryFinanceTransaction = `-- name: LinkCariEntryFinanceTransaction :one
UPDATE cari_entries
SET finance_transaction_id = $3, finance_account_id = $4
WHERE id = $1 AND organization_id = $2
RETURNING id, uuid, organization_id, account_id, type, status, amount, balance_after, entry_date, description, reference_no, payment_method, finance_account_id, finance_transaction_id, created_by, voided_at, voided_by, source_type, source_uuid, metadata, created_at, updated_at
`

type LinkCariEntryFinanceTransactionParams struct {
	ID                   int64       `json:"id"`
	OrganizationID       int64       `json:"organization_id"`
	FinanceTransactionID pgtype.Int8 `json:"finance_transaction_id"`
	FinanceAccountID     pgtype.Int8 `json:"finance_account_id"`
}

func (q *Queries) LinkCariEntryFinanceTransaction(ctx context.Context, arg LinkCariEntryFinanceTransactionParams) (CariEntry, error) {
	row := q.db.QueryRow(ctx, linkCariEntryFinanceTransaction,
		arg.ID,
		arg.OrganizationID,
		arg.FinanceTransactionID,
		arg.FinanceAccountID,
	)
	var i CariEntry
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.AccountID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.BalanceAfter,
		&i.EntryDate,
		&i.Description,
		&i.ReferenceNo,
		&i.PaymentMethod,
		&i.FinanceAccountID,
		&i.FinanceTransactionID,
		&i.CreatedBy,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.SourceType,
		&i.SourceUuid,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCariAccounts = `-- name: ListCariAccounts :many
SELECT a.id, a.uuid, a.organization_id, a.customer_id, a.currency, a.balance, a.is_active, a.created_at, a.updated_at, a.deleted_at,
       c.uuid AS customer_uuid,
       c.name AS customer_name,
       c.phone AS customer_phone,
       c.kind AS customer_kind
FROM cari_accounts a
JOIN customers c ON c.id = a.customer_id AND c.deleted_at IS NULL
WHERE a.organization_id = $1 AND a.deleted_at IS NULL
  AND ($2::boolean IS NULL OR a.is_active = $2)
  AND (
    $3::boolean IS NULL
    OR ($3 = true AND a.balance <> 0)
    OR ($3 = false AND a.balance = 0)
  )
  AND (
    $4::text IS NULL
    OR c.name ILIKE '%' || $4 || '%'
    OR c.phone ILIKE '%' || $4 || '%'
    OR c.email ILIKE '%' || $4 || '%'
  )
ORDER BY
    CASE WHEN $5::text = 'balance' THEN a.balance END ASC,
    CASE WHEN $5::text = '-balance' THEN a.balance END DESC,
    CASE WHEN $5::text = 'customer_name' THEN c.name END ASC,
    CASE WHEN $5::text = '-customer_name' THEN c.name END DESC,
    CASE WHEN $5::text = 'created_at' THEN a.created_at END ASC,
    CASE WHEN $5::text = '-created_at' THEN a.created_at END DESC,
    c.name ASC
LIMIT $7 OFFSET $6
`

type ListCariAccountsParams struct {
	OrganizationID int64       `json:"organization_id"`
	IsActive       pgtype.Bool `json:"is_active"`
	HasBalance     pgtype.Bool `json:"has_balance"`
	Q              pgtype.Text `json:"q"`
	Sort           string      `json:"sort"`
	OffsetCount    int32       `json:"offset_count"`
	LimitCount     int32       `json:"limit_count"`
}

type ListCariAccountsRow struct {
	ID             int64              `json:"id"`
	Uuid           uuid.UUID          `json:"uuid"`
	OrganizationID int64              `json:"organization_id"`
	CustomerID     int64              `json:"customer_id"`
	Currency       string             `json:"currency"`
	Balance        pgtype.Numeric     `json:"balance"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CustomerUuid   uuid.UUID          `json:"customer_uuid"`
	CustomerName   string             `json:"customer_name"`
	CustomerPhone  string             `json:"customer_phone"`
	CustomerKind   string             `json:"customer_kind"`
}

func (q *Queries) ListCariAccounts(ctx context.Context, arg ListCariAccountsParams) ([]ListCariAccountsRow, error) {
	rows, err := q.db.Query(ctx, listCariAccounts,
		arg.OrganizationID,
		arg.IsActive,
		arg.HasBalance,
		arg.Q,
		arg.Sort,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCariAccountsRow{}
	for rows.Next() {
		var i ListCariAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.CustomerID,
			&i.Currency,
			&i.Balance,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CustomerUuid,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CustomerKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCariAccountsForExport = `-- name: ListCariAccountsForExport :many
SELECT a.uuid, a.currency, a.balance, a.is_active, a.created_at,
       c.name AS customer_name, c.phone AS customer_phone, c.kind AS customer_kind
FROM cari_accounts a
JOIN customers c ON c.id = a.customer_id AND c.deleted_at IS NULL
WHERE a.organization_id = $1 AND a.deleted_at IS NULL
  AND ($2::boolean IS NULL OR a.is_active = $2)
  AND (
    $3::boolean IS NULL
    OR ($3 = true AND a.balance <> 0)
    OR ($3 = false AND a.balance = 0)
  )
  AND (
    $4::text IS NULL
    OR c.name ILIKE '%' || $4 || '%'
    OR c.phone ILIKE '%' || $4 || '%'
  )
ORDER BY c.name ASC
`

type ListCariAccountsForExportParams struct {
	OrganizationID int64       `json:"organization_id"`
	IsActive       pgtype.Bool `json:"is_active"`
	HasBalance     pgtype.Bool `json:"has_balance"`
	Q              pgtype.Text `json:"q"`
}

type ListCariAccountsForExportRow struct {
	Uuid          uuid.UUID          `json:"uuid"`
	Currency      string             `json:"currency"`
	Balance       pgtype.Numeric     `json:"balance"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CustomerName  string             `json:"customer_name"`
	CustomerPhone string             `json:"customer_phone"`
	CustomerKind  string             `json:"customer_kind"`
}

func (q *Queries) ListCariAccountsForExport(ctx context.Context, arg ListCariAccountsForExportParams) ([]ListCariAccountsForExportRow, error) {
	rows, err := q.db.Query(ctx, listCariAccountsForExport,
		arg.OrganizationID,
		arg.IsActive,
		arg.HasBalance,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCariAccountsForExportRow{}
	for rows.Next() {
		var i ListCariAccountsForExportRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Currency,
			&i.Balance,
			&i.IsActive,
			&i.CreatedAt,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CustomerKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCariAccountsForSearch = `-- name: ListCariAccountsForSearch :many
SELECT a.uuid, a.balance, a.currency, a.is_active, a.organization_id,
       c.name AS customer_name, c.phone AS customer_phone,
       o.uuid AS organization_uuid, o.slug AS organization_slug
FROM cari_accounts a
JOIN customers c ON c.id = a.customer_id AND c.deleted_at IS NULL
JOIN organizations o ON o.id = a.organization_id
WHERE a.deleted_at IS NULL
`

type ListCariAccountsForSearchRow struct {
	Uuid             uuid.UUID      `json:"uuid"`
	Balance          pgtype.Numeric `json:"balance"`
	Currency         string         `json:"currency"`
	IsActive         bool           `json:"is_active"`
	OrganizationID   int64          `json:"organization_id"`
	CustomerName     string         `json:"customer_name"`
	CustomerPhone    string         `json:"customer_phone"`
	OrganizationUuid uuid.UUID      `json:"organization_uuid"`
	OrganizationSlug string         `json:"organization_slug"`
}

func (q *Queries) ListCariAccountsForSearch(ctx context.Context) ([]ListCariAccountsForSearchRow, error) {
	rows, err := q.db.Query(ctx, listCariAccountsForSearch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCariAccountsForSearchRow{}
	for rows.Next() {
		var i ListCariAccountsForSearchRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Balance,
			&i.Currency,
			&i.IsActive,
			&i.OrganizationID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.OrganizationUuid,
			&i.OrganizationSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCariEntries = `-- name: ListCariEntries :many
SELECT e.id, e.uuid, e.organization_id, e.account_id, e.type, e.status, e.amount, e.balance_after, e.entry_date, e.description, e.reference_no, e.payment_method, e.finance_account_id, e.finance_transaction_id, e.created_by, e.voided_at, e.voided_by, e.source_type, e.source_uuid, e.metadata, e.created_at, e.updated_at,
       a.uuid AS account_uuid,
       fa.uuid AS finance_account_uuid,
       fa.name AS finance_account_name,
       ft.uuid AS finance_transaction_uuid
FROM cari_entries e
JOIN cari_accounts a ON a.id = e.account_id
LEFT JOIN finance_accounts fa ON fa.id = e.finance_account_id
LEFT JOIN finance_transactions ft ON ft.id = e.finance_transaction_id
WHERE e.organization_id = $1
  AND e.account_id = $2
  AND ($3::text IS NULL OR e.type = $3)
  AND ($4::text IS NULL OR e.status = $4)
  AND ($5::date IS NULL OR e.entry_date >= $5)
  AND ($6::date IS NULL OR e.entry_date <= $6)
  AND (
    $7::text IS NULL
    OR e.description ILIKE '%' || $7 || '%'
    OR e.reference_no ILIKE '%' || $7 || '%'
  )
ORDER BY e.entry_date DESC, e.created_at DESC
LIMIT $9 OFFSET $8
`

type ListCariEntriesParams struct {
	OrganizationID int64       `json:"organization_id"`
	AccountID      int64       `json:"account_id"`
	Type           pgtype.Text `json:"type"`
	Status         pgtype.Text `json:"status"`
	DateFrom       pgtype.Date `json:"date_from"`
	DateTo         pgtype.Date `json:"date_to"`
	Q              pgtype.Text `json:"q"`
	OffsetCount    int32       `json:"offset_count"`
	LimitCount     int32       `json:"limit_count"`
}

type ListCariEntriesRow struct {
	ID                     int64              `json:"id"`
	Uuid                   uuid.UUID          `json:"uuid"`
	OrganizationID         int64              `json:"organization_id"`
	AccountID              int64              `json:"account_id"`
	Type                   string             `json:"type"`
	Status                 string             `json:"status"`
	Amount                 pgtype.Numeric     `json:"amount"`
	BalanceAfter           pgtype.Numeric     `json:"balance_after"`
	EntryDate              pgtype.Date        `json:"entry_date"`
	Description            string             `json:"description"`
	ReferenceNo            pgtype.Text        `json:"reference_no"`
	PaymentMethod          pgtype.Text        `json:"payment_method"`
	FinanceAccountID       pgtype.Int8        `json:"finance_account_id"`
	FinanceTransactionID   pgtype.Int8        `json:"finance_transaction_id"`
	CreatedBy              int64              `json:"created_by"`
	VoidedAt               pgtype.Timestamptz `json:"voided_at"`
	VoidedBy               pgtype.Int8        `json:"voided_by"`
	SourceType             pgtype.Text        `json:"source_type"`
	SourceUuid             pgtype.UUID        `json:"source_uuid"`
	Metadata               []byte             `json:"metadata"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	AccountUuid            uuid.UUID          `json:"account_uuid"`
	FinanceAccountUuid     pgtype.UUID        `json:"finance_account_uuid"`
	FinanceAccountName     pgtype.Text        `json:"finance_account_name"`
	FinanceTransactionUuid pgtype.UUID        `json:"finance_transaction_uuid"`
}

func (q *Queries) ListCariEntries(ctx context.Context, arg ListCariEntriesParams) ([]ListCariEntriesRow, error) {
	rows, err := q.db.Query(ctx, listCariEntries,
		arg.OrganizationID,
		arg.AccountID,
		arg.Type,
		arg.Status,
		arg.DateFrom,
		arg.DateTo,
		arg.Q,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCariEntriesRow{}
	for rows.Next() {
		var i ListCariEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.AccountID,
			&i.Type,
			&i.Status,
			&i.Amount,
			&i.BalanceAfter,
			&i.EntryDate,
			&i.Description,
			&i.ReferenceNo,
			&i.PaymentMethod,
			&i.FinanceAccountID,
			&i.FinanceTransactionID,
			&i.CreatedBy,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.SourceType,
			&i.SourceUuid,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountUuid,
			&i.FinanceAccountUuid,
			&i.FinanceAccountName,
			&i.FinanceTransactionUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCariEntriesForExport = `-- name: ListCariEntriesForExport :many
SELECT e.uuid, e.type, e.status, e.amount, e.balance_after, e.entry_date,
       e.description, e.reference_no, e.payment_method, e.created_at,
       c.name AS customer_name
FROM cari_entries e
JOIN cari_accounts a ON a.id = e.account_id
JOIN customers c ON c.id = a.customer_id
WHERE e.organization_id = $1
  AND e.account_id = $2
  AND ($3::text IS NULL OR e.type = $3)
  AND ($4::text IS NULL OR e.status = $4)
ORDER BY e.entry_date DESC, e.created_at DESC
`

type ListCariEntriesForExportParams struct {
	OrganizationID int64       `json:"organization_id"`
	AccountID      int64       `json:"account_id"`
	Type           pgtype.Text `json:"type"`
	Status         pgtype.Text `json:"status"`
}

type ListCariEntriesForExportRow struct {
	Uuid          uuid.UUID          `json:"uuid"`
	Type          string             `json:"type"`
	Status        string             `json:"status"`
	Amount        pgtype.Numeric     `json:"amount"`
	BalanceAfter  pgtype.Numeric     `json:"balance_after"`
	EntryDate     pgtype.Date        `json:"entry_date"`
	Description   string             `json:"description"`
	ReferenceNo   pgtype.Text        `json:"reference_no"`
	PaymentMethod pgtype.Text        `json:"payment_method"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CustomerName  string             `json:"customer_name"`
}

func (q *Queries) ListCariEntriesForExport(ctx context.Context, arg ListCariEntriesForExportParams) ([]ListCariEntriesForExportRow, error) {
	rows, err := q.db.Query(ctx, listCariEntriesForExport,
		arg.OrganizationID,
		arg.AccountID,
		arg.Type,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCariEntriesForExportRow{}
	for rows.Next() {
		var i ListCariEntriesForExportRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Type,
			&i.Status,
			&i.Amount,
			&i.BalanceAfter,
			&i.EntryDate,
			&i.Description,
			&i.ReferenceNo,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCariAccountByCustomer = `-- name: SoftDeleteCariAccountByCustomer :one
UPDATE cari_accounts
SET deleted_at = NOW(), is_active = false
WHERE customer_id = $1 AND organization_id = $2 AND deleted_at IS NULL
RETURNING id, uuid, organization_id, customer_id, currency, balance, is_active, created_at, updated_at, deleted_at
`

type SoftDeleteCariAccountByCustomerParams struct {
	CustomerID     int64 `json:"customer_id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) SoftDeleteCariAccountByCustomer(ctx context.Context, arg SoftDeleteCariAccountByCustomerParams) (CariAccount, error) {
	row := q.db.QueryRow(ctx, softDeleteCariAccountByCustomer, arg.CustomerID, arg.OrganizationID)
	var i CariAccount
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.Currency,
		&i.Balance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const sumCariBalances = `-- name: SumCariBalances :one
SELECT
    COALESCE(SUM(a.balance), 0)::numeric AS total_receivable,
    COUNT(*)::bigint AS account_count,
    COUNT(*) FILTER (WHERE a.balance <> 0)::bigint AS with_balance_count
FROM cari_accounts a
WHERE a.organization_id = $1 AND a.deleted_at IS NULL AND a.is_active = true
`

type SumCariBalancesRow struct {
	TotalReceivable  pgtype.Numeric `json:"total_receivable"`
	AccountCount     int64          `json:"account_count"`
	WithBalanceCount int64          `json:"with_balance_count"`
}

func (q *Queries) SumCariBalances(ctx context.Context, organizationID int64) (SumCariBalancesRow, error) {
	row := q.db.QueryRow(ctx, sumCariBalances, organizationID)
	var i SumCariBalancesRow
	err := row.Scan(&i.TotalReceivable, &i.AccountCount, &i.WithBalanceCount)
	return i, err
}

const voidCariEntry = `-- name: VoidCariEntry :one
UPDATE cari_entries
SET status = 'void', voided_at = NOW(), voided_by = $3
WHERE uuid = $1 AND organization_id = $2 AND status = 'posted'
RETURNING id, uuid, organization_id, account_id, type, status, amount, balance_after, entry_date, description, reference_no, payment_method, finance_account_id, finance_transaction_id, created_by, voided_at, voided_by, source_type, source_uuid, metadata, created_at, updated_at
`

type VoidCariEntryParams struct {
	Uuid           uuid.UUID   `json:"uuid"`
	OrganizationID int64       `json:"organization_id"`
	VoidedBy       pgtype.Int8 `json:"voided_by"`
}

func (q *Queries) VoidCariEntry(ctx context.Context, arg VoidCariEntryParams) (CariEntry, error) {
	row := q.db.QueryRow(ctx, voidCariEntry, arg.Uuid, arg.OrganizationID, arg.VoidedBy)
	var i CariEntry
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.AccountID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.BalanceAfter,
		&i.EntryDate,
		&i.Description,
		&i.ReferenceNo,
		&i.PaymentMethod,
		&i.FinanceAccountID,
		&i.FinanceTransactionID,
		&i.CreatedBy,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.SourceType,
		&i.SourceUuid,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const voidCariEntryBySource = `-- name: VoidCariEntryBySource :one
UPDATE cari_entries
SET status = 'void', voided_at = NOW(), voided_by = $4
WHERE organization_id = $1
  AND source_type = $2
  AND source_uuid = $3
  AND status = 'posted'
RETURNING id, uuid, organization_id, account_id, type, status, amount, balance_after, entry_date, description, reference_no, payment_method, finance_account_id, finance_transaction_id, created_by, voided_at, voided_by, source_type, source_uuid, metadata, created_at, updated_at
`

type VoidCariEntryBySourceParams struct {
	OrganizationID int64       `json:"organization_id"`
	SourceType     pgtype.Text `json:"source_type"`
	SourceUuid     pgtype.UUID `json:"source_uuid"`
	VoidedBy       pgtype.Int8 `json:"voided_by"`
}

func (q *Queries) VoidCariEntryBySource(ctx context.Context, arg VoidCariEntryBySourceParams) (CariEntry, error) {
	row := q.db.QueryRow(ctx, voidCariEntryBySource,
		arg.OrganizationID,
		arg.SourceType,
		arg.SourceUuid,
		arg.VoidedBy,
	)
	var i CariEntry
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.AccountID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.BalanceAfter,
		&i.EntryDate,
		&i.Description,
		&i.ReferenceNo,
		&i.PaymentMethod,
		&i.FinanceAccountID,
		&i.FinanceTransactionID,
		&i.CreatedBy,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.SourceType,
		&i.SourceUuid,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
