// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adjustProductStock = `-- name: AdjustProductStock :one
UPDATE products
SET stock_quantity = stock_quantity + $1
WHERE uuid = $2 AND organization_id = $3 AND deleted_at IS NULL
RETURNING id, uuid, organization_id, category_id, name, sku, barcode, unit, cost_price, sale_price, vat_rate, currency, stock_quantity, min_stock_alert, track_stock, is_active, description, created_at, updated_at, deleted_at
`

type AdjustProductStockParams struct {
	Delta          pgtype.Numeric `json:"delta"`
	Uuid           uuid.UUID      `json:"uuid"`
	OrganizationID int64          `json:"organization_id"`
}

func (q *Queries) AdjustProductStock(ctx context.Context, arg AdjustProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, adjustProductStock, arg.Delta, arg.Uuid, arg.OrganizationID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.Unit,
		&i.CostPrice,
		&i.SalePrice,
		&i.VatRate,
		&i.Currency,
		&i.StockQuantity,
		&i.MinStockAlert,
		&i.TrackStock,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countCatalogCategories = `-- name: CountCatalogCategories :one
SELECT COUNT(*)::bigint FROM catalog_categories
WHERE organization_id = $1 AND deleted_at IS NULL
  AND ($2::text IS NULL OR kind = $2)
  AND ($3::boolean IS NULL OR is_active = $3)
  AND (
    $4::text IS NULL
    OR name ILIKE '%' || $4 || '%'
  )
`

type CountCatalogCategoriesParams struct {
	OrganizationID int64       `json:"organization_id"`
	Kind           pgtype.Text `json:"kind"`
	IsActive       pgtype.Bool `json:"is_active"`
	Q              pgtype.Text `json:"q"`
}

func (q *Queries) CountCatalogCategories(ctx context.Context, arg CountCatalogCategoriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCatalogCategories,
		arg.OrganizationID,
		arg.Kind,
		arg.IsActive,
		arg.Q,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*)::bigint
FROM products p
LEFT JOIN catalog_categories c ON c.id = p.category_id AND c.deleted_at IS NULL
WHERE p.organization_id = $1 AND p.deleted_at IS NULL
  AND ($2::uuid IS NULL OR c.uuid = $2)
  AND ($3::boolean IS NULL OR p.is_active = $3)
  AND ($4::boolean IS NULL OR p.track_stock = $4)
  AND ($5::text IS NULL OR p.unit = $5)
  AND (
    $6::text IS NULL
    OR ($6 = 'in_stock' AND p.track_stock = true AND p.stock_quantity > p.min_stock_alert)
    OR ($6 = 'low_stock' AND p.track_stock = true AND p.stock_quantity <= p.min_stock_alert AND p.stock_quantity > 0)
    OR ($6 = 'out_of_stock' AND p.track_stock = true AND p.stock_quantity <= 0)
  )
  AND (
    $7::text IS NULL
    OR p.name ILIKE '%' || $7 || '%'
    OR p.sku ILIKE '%' || $7 || '%'
    OR p.barcode ILIKE '%' || $7 || '%'
  )
`

type CountProductsParams struct {
	OrganizationID int64       `json:"organization_id"`
	CategoryUuid   pgtype.UUID `json:"category_uuid"`
	IsActive       pgtype.Bool `json:"is_active"`
	TrackStock     pgtype.Bool `json:"track_stock"`
	Unit           pgtype.Text `json:"unit"`
	StockStatus    pgtype.Text `json:"stock_status"`
	Q              pgtype.Text `json:"q"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts,
		arg.OrganizationID,
		arg.CategoryUuid,
		arg.IsActive,
		arg.TrackStock,
		arg.Unit,
		arg.StockStatus,
		arg.Q,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countServices = `-- name: CountServices :one
SELECT COUNT(*)::bigint
FROM services s
LEFT JOIN catalog_categories c ON c.id = s.category_id AND c.deleted_at IS NULL
WHERE s.organization_id = $1 AND s.deleted_at IS NULL
  AND ($2::uuid IS NULL OR c.uuid = $2)
  AND ($3::boolean IS NULL OR s.is_active = $3)
  AND (
    $4::text IS NULL
    OR s.name ILIKE '%' || $4 || '%'
    OR s.code ILIKE '%' || $4 || '%'
  )
`

type CountServicesParams struct {
	OrganizationID int64       `json:"organization_id"`
	CategoryUuid   pgtype.UUID `json:"category_uuid"`
	IsActive       pgtype.Bool `json:"is_active"`
	Q              pgtype.Text `json:"q"`
}

func (q *Queries) CountServices(ctx context.Context, arg CountServicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countServices,
		arg.OrganizationID,
		arg.CategoryUuid,
		arg.IsActive,
		arg.Q,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCatalogCategory = `-- name: CreateCatalogCategory :one


INSERT INTO catalog_categories (
    organization_id, parent_id, name, kind, sort_order, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, uuid, organization_id, parent_id, name, kind, sort_order, is_active, created_at, updated_at, deleted_at
`

type CreateCatalogCategoryParams struct {
	OrganizationID int64       `json:"organization_id"`
	ParentID       pgtype.Int8 `json:"parent_id"`
	Name           string      `json:"name"`
	Kind           string      `json:"kind"`
	SortOrder      int32       `json:"sort_order"`
	IsActive       bool        `json:"is_active"`
}

// Catalog module queries (tenant-scoped via organization_id).
// ============================================================================
// Categories
// ============================================================================
func (q *Queries) CreateCatalogCategory(ctx context.Context, arg CreateCatalogCategoryParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, createCatalogCategory,
		arg.OrganizationID,
		arg.ParentID,
		arg.Name,
		arg.Kind,
		arg.SortOrder,
		arg.IsActive,
	)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one

INSERT INTO products (
    organization_id, category_id, name, sku, barcode, unit,
    cost_price, sale_price, vat_rate, currency,
    stock_quantity, min_stock_alert, track_stock, is_active, description
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14, $15
)
RETURNING id, uuid, organization_id, category_id, name, sku, barcode, unit, cost_price, sale_price, vat_rate, currency, stock_quantity, min_stock_alert, track_stock, is_active, description, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	OrganizationID int64          `json:"organization_id"`
	CategoryID     pgtype.Int8    `json:"category_id"`
	Name           string         `json:"name"`
	Sku            pgtype.Text    `json:"sku"`
	Barcode        pgtype.Text    `json:"barcode"`
	Unit           string         `json:"unit"`
	CostPrice      pgtype.Numeric `json:"cost_price"`
	SalePrice      pgtype.Numeric `json:"sale_price"`
	VatRate        pgtype.Numeric `json:"vat_rate"`
	Currency       string         `json:"currency"`
	StockQuantity  pgtype.Numeric `json:"stock_quantity"`
	MinStockAlert  pgtype.Numeric `json:"min_stock_alert"`
	TrackStock     bool           `json:"track_stock"`
	IsActive       bool           `json:"is_active"`
	Description    string         `json:"description"`
}

// ============================================================================
// Products
// ============================================================================
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.OrganizationID,
		arg.CategoryID,
		arg.Name,
		arg.Sku,
		arg.Barcode,
		arg.Unit,
		arg.CostPrice,
		arg.SalePrice,
		arg.VatRate,
		arg.Currency,
		arg.StockQuantity,
		arg.MinStockAlert,
		arg.TrackStock,
		arg.IsActive,
		arg.Description,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.Unit,
		&i.CostPrice,
		&i.SalePrice,
		&i.VatRate,
		&i.Currency,
		&i.StockQuantity,
		&i.MinStockAlert,
		&i.TrackStock,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createService = `-- name: CreateService :one

INSERT INTO services (
    organization_id, category_id, name, code, duration_minutes,
    price, vat_rate, currency, is_active, description, color
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11
)
RETURNING id, uuid, organization_id, category_id, name, code, duration_minutes, price, vat_rate, currency, is_active, description, created_at, updated_at, deleted_at, color
`

type CreateServiceParams struct {
	OrganizationID  int64          `json:"organization_id"`
	CategoryID      pgtype.Int8    `json:"category_id"`
	Name            string         `json:"name"`
	Code            pgtype.Text    `json:"code"`
	DurationMinutes int32          `json:"duration_minutes"`
	Price           pgtype.Numeric `json:"price"`
	VatRate         pgtype.Numeric `json:"vat_rate"`
	Currency        string         `json:"currency"`
	IsActive        bool           `json:"is_active"`
	Description     string         `json:"description"`
	Color           string         `json:"color"`
}

// ============================================================================
// Services
// ============================================================================
func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.OrganizationID,
		arg.CategoryID,
		arg.Name,
		arg.Code,
		arg.DurationMinutes,
		arg.Price,
		arg.VatRate,
		arg.Currency,
		arg.IsActive,
		arg.Description,
		arg.Color,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Code,
		&i.DurationMinutes,
		&i.Price,
		&i.VatRate,
		&i.Currency,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Color,
	)
	return i, err
}

const getCatalogCategoryByID = `-- name: GetCatalogCategoryByID :one
SELECT id, uuid, organization_id, parent_id, name, kind, sort_order, is_active, created_at, updated_at, deleted_at FROM catalog_categories
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type GetCatalogCategoryByIDParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) GetCatalogCategoryByID(ctx context.Context, arg GetCatalogCategoryByIDParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, getCatalogCategoryByID, arg.ID, arg.OrganizationID)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCatalogCategoryByName = `-- name: GetCatalogCategoryByName :one
SELECT id, uuid, organization_id, parent_id, name, kind, sort_order, is_active, created_at, updated_at, deleted_at FROM catalog_categories
WHERE organization_id = $1 AND kind = $2 AND lower(name) = lower($3) AND deleted_at IS NULL
`

type GetCatalogCategoryByNameParams struct {
	OrganizationID int64  `json:"organization_id"`
	Kind           string `json:"kind"`
	Lower          string `json:"lower"`
}

func (q *Queries) GetCatalogCategoryByName(ctx context.Context, arg GetCatalogCategoryByNameParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, getCatalogCategoryByName, arg.OrganizationID, arg.Kind, arg.Lower)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCatalogCategoryByUUID = `-- name: GetCatalogCategoryByUUID :one
SELECT id, uuid, organization_id, parent_id, name, kind, sort_order, is_active, created_at, updated_at, deleted_at FROM catalog_categories
WHERE uuid = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type GetCatalogCategoryByUUIDParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) GetCatalogCategoryByUUID(ctx context.Context, arg GetCatalogCategoryByUUIDParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, getCatalogCategoryByUUID, arg.Uuid, arg.OrganizationID)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCatalogStats = `-- name: GetCatalogStats :one
SELECT
    ps.total_products,
    ps.active_products,
    ps.low_stock_products,
    ps.out_of_stock_products,
    ps.total_stock_cost_value,
    ps.total_stock_sale_value,
    ss.total_services,
    ss.active_services,
    cs.total_categories
FROM (
    SELECT
        COUNT(*)::bigint AS total_products,
        COUNT(*) FILTER (WHERE p.is_active = true)::bigint AS active_products,
        COUNT(*) FILTER (WHERE p.is_active = true AND p.track_stock = true AND p.stock_quantity <= p.min_stock_alert AND p.stock_quantity > 0)::bigint AS low_stock_products,
        COUNT(*) FILTER (WHERE p.is_active = true AND p.track_stock = true AND p.stock_quantity <= 0)::bigint AS out_of_stock_products,
        COALESCE(SUM(p.stock_quantity * p.cost_price) FILTER (WHERE p.is_active = true AND p.track_stock = true), 0)::numeric(18,2) AS total_stock_cost_value,
        COALESCE(SUM(p.stock_quantity * p.sale_price) FILTER (WHERE p.is_active = true AND p.track_stock = true), 0)::numeric(18,2) AS total_stock_sale_value
    FROM products p
    WHERE p.organization_id = $1 AND p.deleted_at IS NULL
) ps,
(
    SELECT
        COUNT(*)::bigint AS total_services,
        COUNT(*) FILTER (WHERE s.is_active = true)::bigint AS active_services
    FROM services s
    WHERE s.organization_id = $1 AND s.deleted_at IS NULL
) ss,
(
    SELECT COUNT(*)::bigint AS total_categories
    FROM catalog_categories c
    WHERE c.organization_id = $1 AND c.deleted_at IS NULL
) cs
`

type GetCatalogStatsRow struct {
	TotalProducts       int64          `json:"total_products"`
	ActiveProducts      int64          `json:"active_products"`
	LowStockProducts    int64          `json:"low_stock_products"`
	OutOfStockProducts  int64          `json:"out_of_stock_products"`
	TotalStockCostValue pgtype.Numeric `json:"total_stock_cost_value"`
	TotalStockSaleValue pgtype.Numeric `json:"total_stock_sale_value"`
	TotalServices       int64          `json:"total_services"`
	ActiveServices      int64          `json:"active_services"`
	TotalCategories     int64          `json:"total_categories"`
}

// Each aggregate reads its own table: joining products, services and
// categories together multiplies the product sums by the other row counts.
func (q *Queries) GetCatalogStats(ctx context.Context, organizationID int64) (GetCatalogStatsRow, error) {
	row := q.db.QueryRow(ctx, getCatalogStats, organizationID)
	var i GetCatalogStatsRow
	err := row.Scan(
		&i.TotalProducts,
		&i.ActiveProducts,
		&i.LowStockProducts,
		&i.OutOfStockProducts,
		&i.TotalStockCostValue,
		&i.TotalStockSaleValue,
		&i.TotalServices,
		&i.ActiveServices,
		&i.TotalCategories,
	)
	return i, err
}

const getProductByBarcode = `-- name: GetProductByBarcode :one
SELECT id, uuid, organization_id, category_id, name, sku, barcode, unit, cost_price, sale_price, vat_rate, currency, stock_quantity, min_stock_alert, track_stock, is_active, description, created_at, updated_at, deleted_at FROM products
WHERE organization_id = $1 AND lower(barcode) = lower($2) AND deleted_at IS NULL
`

type GetProductByBarcodeParams struct {
	OrganizationID int64  `json:"organization_id"`
	Lower          string `json:"lower"`
}

func (q *Queries) GetProductByBarcode(ctx context.Context, arg GetProductByBarcodeParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByBarcode, arg.OrganizationID, arg.Lower)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.Unit,
		&i.CostPrice,
		&i.SalePrice,
		&i.VatRate,
		&i.Currency,
		&i.StockQuantity,
		&i.MinStockAlert,
		&i.TrackStock,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, uuid, organization_id, category_id, name, sku, barcode, unit, cost_price, sale_price, vat_rate, currency, stock_quantity, min_stock_alert, track_stock, is_active, description, created_at, updated_at, deleted_at FROM products
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type GetProductByIDParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, arg.ID, arg.OrganizationID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.Unit,
		&i.CostPrice,
		&i.SalePrice,
		&i.VatRate,
		&i.Currency,
		&i.StockQuantity,
		&i.MinStockAlert,
		&i.TrackStock,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductByName = `-- name: GetProductByName :one
SELECT id, uuid, organization_id, category_id, name, sku, barcode, unit, cost_price, sale_price, vat_rate, currency, stock_quantity, min_stock_alert, track_stock, is_active, description, created_at, updated_at, deleted_at FROM products
WHERE organization_id = $1 AND lower(name) = lower($2) AND deleted_at IS NULL
`

type GetProductByNameParams struct {
	OrganizationID int64  `json:"organization_id"`
	Lower          string `json:"lower"`
}

func (q *Queries) GetProductByName(ctx context.Context, arg GetProductByNameParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByName, arg.OrganizationID, arg.Lower)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.Unit,
		&i.CostPrice,
		&i.SalePrice,
		&i.VatRate,
		&i.Currency,
		&i.StockQuantity,
		&i.MinStockAlert,
		&i.TrackStock,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT id, uuid, organization_id, category_id, name, sku, barcode, unit, cost_price, sale_price, vat_rate, currency, stock_quantity, min_stock_alert, track_stock, is_active, description, created_at, updated_at, deleted_at FROM products
WHERE organization_id = $1 AND lower(sku) = lower($2) AND deleted_at IS NULL
`

type GetProductBySKUParams struct {
	OrganizationID int64  `json:"organization_id"`
	Lower          string `json:"lower"`
}

func (q *Queries) GetProductBySKU(ctx context.Context, arg GetProductBySKUParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySKU, arg.OrganizationID, arg.Lower)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.Unit,
		&i.CostPrice,
		&i.SalePrice,
		&i.VatRate,
		&i.Currency,
		&i.StockQuantity,
		&i.MinStockAlert,
		&i.TrackStock,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductByUUID = `-- name: GetProductByUUID :one
SELECT p.id, p.uuid, p.organization_id, p.category_id, p.name, p.sku, p.barcode, p.unit, p.cost_price, p.sale_price, p.vat_rate, p.currency, p.stock_quantity, p.min_stock_alert, p.track_stock, p.is_active, p.description, p.created_at, p.updated_at, p.deleted_at, c.uuid AS category_uuid, c.name AS category_name
FROM products p
LEFT JOIN catalog_categories c ON c.id = p.category_id AND c.deleted_at IS NULL
WHERE p.uuid = $1 AND p.organization_id = $2 AND p.deleted_at IS NULL
`

type GetProductByUUIDParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

type GetProductByUUIDRow struct {
	ID             int64              `json:"id"`
	Uuid           uuid.UUID          `json:"uuid"`
	OrganizationID int64              `json:"organization_id"`
	CategoryID     pgtype.Int8        `json:"category_id"`
	Name           string             `json:"name"`
	Sku            pgtype.Text        `json:"sku"`
	Barcode        pgtype.Text        `json:"barcode"`
	Unit           string             `json:"unit"`
	CostPrice      pgtype.Numeric     `json:"cost_price"`
	SalePrice      pgtype.Numeric     `json:"sale_price"`
	VatRate        pgtype.Numeric     `json:"vat_rate"`
	Currency       string             `json:"currency"`
	StockQuantity  pgtype.Numeric     `json:"stock_quantity"`
	MinStockAlert  pgtype.Numeric     `json:"min_stock_alert"`
	TrackStock     bool               `json:"track_stock"`
	IsActive       bool               `json:"is_active"`
	Description    string             `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CategoryUuid   pgtype.UUID        `json:"category_uuid"`
	CategoryName   pgtype.Text        `json:"category_name"`
}

func (q *Queries) GetProductByUUID(ctx context.Context, arg GetProductByUUIDParams) (GetProductByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByUUID, arg.Uuid, arg.OrganizationID)
	var i GetProductByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.Unit,
		&i.CostPrice,
		&i.SalePrice,
		&i.VatRate,
		&i.Currency,
		&i.StockQuantity,
		&i.MinStockAlert,
		&i.TrackStock,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CategoryUuid,
		&i.CategoryName,
	)
	return i, err
}

const getProductForSearch = `-- name: GetProductForSearch :one
SELECT
    p.uuid,
    p.name,
    p.sku,
    p.barcode,
    p.sale_price,
    p.currency,
    p.stock_quantity,
    p.unit,
    p.is_active,
    c.name AS category_name,
    o.uuid AS organization_uuid,
    o.slug AS organization_slug
FROM products p
JOIN organizations o ON o.id = p.organization_id AND o.deleted_at IS NULL
LEFT JOIN catalog_categories c ON c.id = p.category_id AND c.deleted_at IS NULL
WHERE p.uuid = $1 AND o.uuid = $2 AND p.deleted_at IS NULL
`

type GetProductForSearchParams struct {
	Uuid    uuid.UUID `json:"uuid"`
	OrgUuid uuid.UUID `json:"org_uuid"`
}

type GetProductForSearchRow struct {
	Uuid             uuid.UUID      `json:"uuid"`
	Name             string         `json:"name"`
	Sku              pgtype.Text    `json:"sku"`
	Barcode          pgtype.Text    `json:"barcode"`
	SalePrice        pgtype.Numeric `json:"sale_price"`
	Currency         string         `json:"currency"`
	StockQuantity    pgtype.Numeric `json:"stock_quantity"`
	Unit             string         `json:"unit"`
	IsActive         bool           `json:"is_active"`
	CategoryName     pgtype.Text    `json:"category_name"`
	OrganizationUuid uuid.UUID      `json:"organization_uuid"`
	OrganizationSlug string         `json:"organization_slug"`
}

func (q *Queries) GetProductForSearch(ctx context.Context, arg GetProductForSearchParams) (GetProductForSearchRow, error) {
	row := q.db.QueryRow(ctx, getProductForSearch, arg.Uuid, arg.OrgUuid)
	var i GetProductForSearchRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.SalePrice,
		&i.Currency,
		&i.StockQuantity,
		&i.Unit,
		&i.IsActive,
		&i.CategoryName,
		&i.OrganizationUuid,
		&i.OrganizationSlug,
	)
	return i, err
}

const getServiceByCode = `-- name: GetServiceByCode :one
SELECT id, uuid, organization_id, category_id, name, code, duration_minutes, price, vat_rate, currency, is_active, description, created_at, updated_at, deleted_at, color FROM services
WHERE organization_id = $1 AND lower(code) = lower($2) AND deleted_at IS NULL
`

type GetServiceByCodeParams struct {
	OrganizationID int64  `json:"organization_id"`
	Lower          string `json:"lower"`
}

func (q *Queries) GetServiceByCode(ctx context.Context, arg GetServiceByCodeParams) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByCode, arg.OrganizationID, arg.Lower)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Code,
		&i.DurationMinutes,
		&i.Price,
		&i.VatRate,
		&i.Currency,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Color,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, uuid, organization_id, category_id, name, code, duration_minutes, price, vat_rate, currency, is_active, description, created_at, updated_at, deleted_at, color FROM services
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type GetServiceByIDParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) GetServiceByID(ctx context.Context, arg GetServiceByIDParams) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, arg.ID, arg.OrganizationID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Code,
		&i.DurationMinutes,
		&i.Price,
		&i.VatRate,
		&i.Currency,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Color,
	)
	return i, err
}

const getServiceByName = `-- name: GetServiceByName :one
SELECT id, uuid, organization_id, category_id, name, code, duration_minutes, price, vat_rate, currency, is_active, description, created_at, updated_at, deleted_at, color FROM services
WHERE organization_id = $1 AND lower(name) = lower($2) AND deleted_at IS NULL
`

type GetServiceByNameParams struct {
	OrganizationID int64  `json:"organization_id"`
	Lower          string `json:"lower"`
}

func (q *Queries) GetServiceByName(ctx context.Context, arg GetServiceByNameParams) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByName, arg.OrganizationID, arg.Lower)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Code,
		&i.DurationMinutes,
		&i.Price,
		&i.VatRate,
		&i.Currency,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Color,
	)
	return i, err
}

const getServiceByUUID = `-- name: GetServiceByUUID :one
SELECT s.id, s.uuid, s.organization_id, s.category_id, s.name, s.code, s.duration_minutes, s.price, s.vat_rate, s.currency, s.is_active, s.description, s.created_at, s.updated_at, s.deleted_at, s.color, c.uuid AS category_uuid, c.name AS category_name
FROM services s
LEFT JOIN catalog_categories c ON c.id = s.category_id AND c.deleted_at IS NULL
WHERE s.uuid = $1 AND s.organization_id = $2 AND s.deleted_at IS NULL
`

type GetServiceByUUIDParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

type GetServiceByUUIDRow struct {
	ID              int64              `json:"id"`
	Uuid            uuid.UUID          `json:"uuid"`
	OrganizationID  int64              `json:"organization_id"`
	CategoryID      pgtype.Int8        `json:"category_id"`
	Name            string             `json:"name"`
	Code            pgtype.Text        `json:"code"`
	DurationMinutes int32              `json:"duration_minutes"`
	Price           pgtype.Numeric     `json:"price"`
	VatRate         pgtype.Numeric     `json:"vat_rate"`
	Currency        string             `json:"currency"`
	IsActive        bool               `json:"is_active"`
	Description     string             `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	Color           string             `json:"color"`
	CategoryUuid    pgtype.UUID        `json:"category_uuid"`
	CategoryName    pgtype.Text        `json:"category_name"`
}

func (q *Queries) GetServiceByUUID(ctx context.Context, arg GetServiceByUUIDParams) (GetServiceByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getServiceByUUID, arg.Uuid, arg.OrganizationID)
	var i GetServiceByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Code,
		&i.DurationMinutes,
		&i.Price,
		&i.VatRate,
		&i.Currency,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Color,
		&i.CategoryUuid,
		&i.CategoryName,
	)
	return i, err
}

const getServiceForSearch = `-- name: GetServiceForSearch :one
SELECT
    s.uuid,
    s.name,
    s.code,
    s.price,
    s.currency,
    s.duration_minutes,
    s.is_active,
    c.name AS category_name,
    o.uuid AS organization_uuid,
    o.slug AS organization_slug
FROM services s
JOIN organizations o ON o.id = s.organization_id AND o.deleted_at IS NULL
LEFT JOIN catalog_categories c ON c.id = s.category_id AND c.deleted_at IS NULL
WHERE s.uuid = $1 AND o.uuid = $2 AND s.deleted_at IS NULL
`

type GetServiceForSearchParams struct {
	Uuid    uuid.UUID `json:"uuid"`
	OrgUuid uuid.UUID `json:"org_uuid"`
}

type GetServiceForSearchRow struct {
	Uuid             uuid.UUID      `json:"uuid"`
	Name             string         `json:"name"`
	Code             pgtype.Text    `json:"code"`
	Price            pgtype.Numeric `json:"price"`
	Currency         string         `json:"currency"`
	DurationMinutes  int32          `json:"duration_minutes"`
	IsActive         bool           `json:"is_active"`
	CategoryName     pgtype.Text    `json:"category_name"`
	OrganizationUuid uuid.UUID      `json:"organization_uuid"`
	OrganizationSlug string         `json:"organization_slug"`
}

func (q *Queries) GetServiceForSearch(ctx context.Context, arg GetServiceForSearchParams) (GetServiceForSearchRow, error) {
	row := q.db.QueryRow(ctx, getServiceForSearch, arg.Uuid, arg.OrgUuid)
	var i GetServiceForSearchRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Code,
		&i.Price,
		&i.Currency,
		&i.DurationMinutes,
		&i.IsActive,
		&i.CategoryName,
		&i.OrganizationUuid,
		&i.OrganizationSlug,
	)
	return i, err
}

const listCatalogCategories = `-- name: ListCatalogCategories :many
SELECT c.id, c.uuid, c.organization_id, c.parent_id, c.name, c.kind, c.sort_order, c.is_active, c.created_at, c.updated_at, c.deleted_at, p.name AS parent_name
FROM catalog_categories c
LEFT JOIN catalog_categories p ON p.id = c.parent_id AND p.deleted_at IS NULL
WHERE c.organization_id = $1 AND c.deleted_at IS NULL
  AND ($2::text IS NULL OR c.kind = $2)
  AND ($3::boolean IS NULL OR c.is_active = $3)
  AND (
    $4::text IS NULL
    OR c.name ILIKE '%' || $4 || '%'
  )
ORDER BY c.kind ASC, c.sort_order ASC, c.name ASC
`

type ListCatalogCategoriesParams struct {
	OrganizationID int64       `json:"organization_id"`
	Kind           pgtype.Text `json:"kind"`
	IsActive       pgtype.Bool `json:"is_active"`
	Q              pgtype.Text `json:"q"`
}

type ListCatalogCategoriesRow struct {
	ID             int64              `json:"id"`
	Uuid           uuid.UUID          `json:"uuid"`
	OrganizationID int64              `json:"organization_id"`
	ParentID       pgtype.Int8        `json:"parent_id"`
	Name           string             `json:"name"`
	Kind           string             `json:"kind"`
	SortOrder      int32              `json:"sort_order"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	ParentName     pgtype.Text        `json:"parent_name"`
}

func (q *Queries) ListCatalogCategories(ctx context.Context, arg ListCatalogCategoriesParams) ([]ListCatalogCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCatalogCategories,
		arg.OrganizationID,
		arg.Kind,
		arg.IsActive,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogCategoriesRow{}
	for rows.Next() {
		var i ListCatalogCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ParentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductUUIDsForBulk = `-- name: ListProductUUIDsForBulk :many
SELECT p.uuid
FROM products p
LEFT JOIN catalog_categories c ON c.id = p.category_id AND c.deleted_at IS NULL
WHERE p.organization_id = $1 AND p.deleted_at IS NULL
  AND ($2::uuid IS NULL OR c.uuid = $2)
  AND ($3::boolean IS NULL OR p.is_active = $3)
  AND ($4::boolean IS NULL OR p.track_stock = $4)
  AND ($5::text IS NULL OR p.unit = $5)
  AND (
    $6::text IS NULL
    OR ($6 = 'in_stock' AND p.track_stock = true AND p.stock_quantity > p.min_stock_alert)
    OR ($6 = 'low_stock' AND p.track_stock = true AND p.stock_quantity <= p.min_stock_alert AND p.stock_quantity > 0)
    OR ($6 = 'out_of_stock' AND p.track_stock = true AND p.stock_quantity <= 0)
  )
  AND (
    $7::text IS NULL
    OR p.name ILIKE '%' || $7 || '%'
    OR p.sku ILIKE '%' || $7 || '%'
    OR p.barcode ILIKE '%' || $7 || '%'
  )
ORDER BY p.name ASC
`

type ListProductUUIDsForBulkParams struct {
	OrganizationID int64       `json:"organization_id"`
	CategoryUuid   pgtype.UUID `json:"category_uuid"`
	IsActive       pgtype.Bool `json:"is_active"`
	TrackStock     pgtype.Bool `json:"track_stock"`
	Unit           pgtype.Text `json:"unit"`
	StockStatus    pgtype.Text `json:"stock_status"`
	Q              pgtype.Text `json:"q"`
}

func (q *Queries) ListProductUUIDsForBulk(ctx context.Context, arg ListProductUUIDsForBulkParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listProductUUIDsForBulk,
		arg.OrganizationID,
		arg.CategoryUuid,
		arg.IsActive,
		arg.TrackStock,
		arg.Unit,
		arg.StockStatus,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var uuid uuid.UUID
		if err := rows.Scan(&uuid); err != nil {
			return nil, err
		}
		items = append(items, uuid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.uuid, p.organization_id, p.category_id, p.name, p.sku, p.barcode, p.unit, p.cost_price, p.sale_price, p.vat_rate, p.currency, p.stock_quantity, p.min_stock_alert, p.track_stock, p.is_active, p.description, p.created_at, p.updated_at, p.deleted_at, c.uuid AS category_uuid, c.name AS category_name
FROM products p
LEFT JOIN catalog_categories c ON c.id = p.category_id AND c.deleted_at IS NULL
WHERE p.organization_id = $1 AND p.deleted_at IS NULL
  AND ($2::uuid IS NULL OR c.uuid = $2)
  AND ($3::boolean IS NULL OR p.is_active = $3)
  AND ($4::boolean IS NULL OR p.track_stock = $4)
  AND ($5::text IS NULL OR p.unit = $5)
  AND (
    $6::text IS NULL
    OR ($6 = 'in_stock' AND p.track_stock = true AND p.stock_quantity > p.min_stock_alert)
    OR ($6 = 'low_stock' AND p.track_stock = true AND p.stock_quantity <= p.min_stock_alert AND p.stock_quantity > 0)
    OR ($6 = 'out_of_stock' AND p.track_stock = true AND p.stock_quantity <= 0)
  )
  AND (
    $7::text IS NULL
    OR p.name ILIKE '%' || $7 || '%'
    OR p.sku ILIKE '%' || $7 || '%'
    OR p.barcode ILIKE '%' || $7 || '%'
  )
ORDER BY
  CASE WHEN $8::text = 'name_asc' THEN p.name END ASC,
  CASE WHEN $8::text = 'name_desc' THEN p.name END DESC,
  CASE WHEN $8::text = 'stock_asc' THEN p.stock_quantity END ASC,
  CASE WHEN $8::text = 'stock_desc' THEN p.stock_quantity END DESC,
  CASE WHEN $8::text = 'price_asc' THEN p.sale_price END ASC,
  CASE WHEN $8::text = 'price_desc' THEN p.sale_price END DESC,
  p.name ASC
LIMIT $10 OFFSET $9
`

type ListProductsParams struct {
	OrganizationID int64       `json:"organization_id"`
	CategoryUuid   pgtype.UUID `json:"category_uuid"`
	IsActive       pgtype.Bool `json:"is_active"`
	TrackStock     pgtype.Bool `json:"track_stock"`
	Unit           pgtype.Text `json:"unit"`
	StockStatus    pgtype.Text `json:"stock_status"`
	Q              pgtype.Text `json:"q"`
	SortBy         pgtype.Text `json:"sort_by"`
	OffsetCount    int32       `json:"offset_count"`
	LimitCount     int32       `json:"limit_count"`
}

type ListProductsRow struct {
	ID             int64              `json:"id"`
	Uuid           uuid.UUID          `json:"uuid"`
	OrganizationID int64              `json:"organization_id"`
	CategoryID     pgtype.Int8        `json:"category_id"`
	Name           string             `json:"name"`
	Sku            pgtype.Text        `json:"sku"`
	Barcode        pgtype.Text        `json:"barcode"`
	Unit           string             `json:"unit"`
	CostPrice      pgtype.Numeric     `json:"cost_price"`
	SalePrice      pgtype.Numeric     `json:"sale_price"`
	VatRate        pgtype.Numeric     `json:"vat_rate"`
	Currency       string             `json:"currency"`
	StockQuantity  pgtype.Numeric     `json:"stock_quantity"`
	MinStockAlert  pgtype.Numeric     `json:"min_stock_alert"`
	TrackStock     bool               `json:"track_stock"`
	IsActive       bool               `json:"is_active"`
	Description    string             `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CategoryUuid   pgtype.UUID        `json:"category_uuid"`
	CategoryName   pgtype.Text        `json:"category_name"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.OrganizationID,
		arg.CategoryUuid,
		arg.IsActive,
		arg.TrackStock,
		arg.Unit,
		arg.StockStatus,
		arg.Q,
		arg.SortBy,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.CategoryID,
			&i.Name,
			&i.Sku,
			&i.Barcode,
			&i.Unit,
			&i.CostPrice,
			&i.SalePrice,
			&i.VatRate,
			&i.Currency,
			&i.StockQuantity,
			&i.MinStockAlert,
			&i.TrackStock,
			&i.IsActive,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryUuid,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsForExport = `-- name: ListProductsForExport :many
SELECT p.id, p.uuid, p.organization_id, p.category_id, p.name, p.sku, p.barcode, p.unit, p.cost_price, p.sale_price, p.vat_rate, p.currency, p.stock_quantity, p.min_stock_alert, p.track_stock, p.is_active, p.description, p.created_at, p.updated_at, p.deleted_at, c.name AS category_name
FROM products p
LEFT JOIN catalog_categories c ON c.id = p.category_id AND c.deleted_at IS NULL
WHERE p.organization_id = $1 AND p.deleted_at IS NULL
  AND ($2::uuid IS NULL OR c.uuid = $2)
  AND ($3::boolean IS NULL OR p.is_active = $3)
  AND (
    $4::text IS NULL
    OR p.name ILIKE '%' || $4 || '%'
    OR p.sku ILIKE '%' || $4 || '%'
    OR p.barcode ILIKE '%' || $4 || '%'
  )
ORDER BY p.name ASC
`

type ListProductsForExportParams struct {
	OrganizationID int64       `json:"organization_id"`
	CategoryUuid   pgtype.UUID `json:"category_uuid"`
	IsActive       pgtype.Bool `json:"is_active"`
	Q              pgtype.Text `json:"q"`
}

type ListProductsForExportRow struct {
	ID             int64              `json:"id"`
	Uuid           uuid.UUID          `json:"uuid"`
	OrganizationID int64              `json:"organization_id"`
	CategoryID     pgtype.Int8        `json:"category_id"`
	Name           string             `json:"name"`
	Sku            pgtype.Text        `json:"sku"`
	Barcode        pgtype.Text        `json:"barcode"`
	Unit           string             `json:"unit"`
	CostPrice      pgtype.Numeric     `json:"cost_price"`
	SalePrice      pgtype.Numeric     `json:"sale_price"`
	VatRate        pgtype.Numeric     `json:"vat_rate"`
	Currency       string             `json:"currency"`
	StockQuantity  pgtype.Numeric     `json:"stock_quantity"`
	MinStockAlert  pgtype.Numeric     `json:"min_stock_alert"`
	TrackStock     bool               `json:"track_stock"`
	IsActive       bool               `json:"is_active"`
	Description    string             `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CategoryName   pgtype.Text        `json:"category_name"`
}

func (q *Queries) ListProductsForExport(ctx context.Context, arg ListProductsForExportParams) ([]ListProductsForExportRow, error) {
	rows, err := q.db.Query(ctx, listProductsForExport,
		arg.OrganizationID,
		arg.CategoryUuid,
		arg.IsActive,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsForExportRow{}
	for rows.Next() {
		var i ListProductsForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.CategoryID,
			&i.Name,
			&i.Sku,
			&i.Barcode,
			&i.Unit,
			&i.CostPrice,
			&i.SalePrice,
			&i.VatRate,
			&i.Currency,
			&i.StockQuantity,
			&i.MinStockAlert,
			&i.TrackStock,
			&i.IsActive,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsForSearch = `-- name: ListProductsForSearch :many

SELECT
    p.uuid,
    p.name,
    p.sku,
    p.barcode,
    p.sale_price,
    p.currency,
    p.stock_quantity,
    p.unit,
    p.is_active,
    c.name AS category_name,
    o.uuid AS organization_uuid,
    o.slug AS organization_slug
FROM products p
JOIN organizations o ON o.id = p.organization_id AND o.deleted_at IS NULL
LEFT JOIN catalog_categories c ON c.id = p.category_id AND c.deleted_at IS NULL
WHERE p.deleted_at IS NULL
`

type ListProductsForSearchRow struct {
	Uuid             uuid.UUID      `json:"uuid"`
	Name             string         `json:"name"`
	Sku              pgtype.Text    `json:"sku"`
	Barcode          pgtype.Text    `json:"barcode"`
	SalePrice        pgtype.Numeric `json:"sale_price"`
	Currency         string         `json:"currency"`
	StockQuantity    pgtype.Numeric `json:"stock_quantity"`
	Unit             string         `json:"unit"`
	IsActive         bool           `json:"is_active"`
	CategoryName     pgtype.Text    `json:"category_name"`
	OrganizationUuid uuid.UUID      `json:"organization_uuid"`
	OrganizationSlug string         `json:"organization_slug"`
}

// ============================================================================
// Catalog Search Queries
// ============================================================================
func (q *Queries) ListProductsForSearch(ctx context.Context) ([]ListProductsForSearchRow, error) {
	rows, err := q.db.Query(ctx, listProductsForSearch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsForSearchRow{}
	for rows.Next() {
		var i ListProductsForSearchRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Sku,
			&i.Barcode,
			&i.SalePrice,
			&i.Currency,
			&i.StockQuantity,
			&i.Unit,
			&i.IsActive,
			&i.CategoryName,
			&i.OrganizationUuid,
			&i.OrganizationSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceUUIDsForBulk = `-- name: ListServiceUUIDsForBulk :many
SELECT s.uuid
FROM services s
LEFT JOIN catalog_categories c ON c.id = s.category_id AND c.deleted_at IS NULL
WHERE s.organization_id = $1 AND s.deleted_at IS NULL
  AND ($2::uuid IS NULL OR c.uuid = $2)
  AND ($3::boolean IS NULL OR s.is_active = $3)
  AND (
    $4::text IS NULL
    OR s.name ILIKE '%' || $4 || '%'
    OR s.code ILIKE '%' || $4 || '%'
  )
ORDER BY s.name ASC
`

type ListServiceUUIDsForBulkParams struct {
	OrganizationID int64       `json:"organization_id"`
	CategoryUuid   pgtype.UUID `json:"category_uuid"`
	IsActive       pgtype.Bool `json:"is_active"`
	Q              pgtype.Text `json:"q"`
}

func (q *Queries) ListServiceUUIDsForBulk(ctx context.Context, arg ListServiceUUIDsForBulkParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listServiceUUIDsForBulk,
		arg.OrganizationID,
		arg.CategoryUuid,
		arg.IsActive,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var uuid uuid.UUID
		if err := rows.Scan(&uuid); err != nil {
			return nil, err
		}
		items = append(items, uuid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT s.id, s.uuid, s.organization_id, s.category_id, s.name, s.code, s.duration_minutes, s.price, s.vat_rate, s.currency, s.is_active, s.description, s.created_at, s.updated_at, s.deleted_at, s.color, c.uuid AS category_uuid, c.name AS category_name
FROM services s
LEFT JOIN catalog_categories c ON c.id = s.category_id AND c.deleted_at IS NULL
WHERE s.organization_id = $1 AND s.deleted_at IS NULL
  AND ($2::uuid IS NULL OR c.uuid = $2)
  AND ($3::boolean IS NULL OR s.is_active = $3)
  AND (
    $4::text IS NULL
    OR s.name ILIKE '%' || $4 || '%'
    OR s.code ILIKE '%' || $4 || '%'
  )
ORDER BY
  CASE WHEN $5::text = 'name_asc' THEN s.name END ASC,
  CASE WHEN $5::text = 'name_desc' THEN s.name END DESC,
  CASE WHEN $5::text = 'price_asc' THEN s.price END ASC,
  CASE WHEN $5::text = 'price_desc' THEN s.price END DESC,
  CASE WHEN $5::text = 'duration_asc' THEN s.duration_minutes END ASC,
  CASE WHEN $5::text = 'duration_desc' THEN s.duration_minutes END DESC,
  s.name ASC
LIMIT $7 OFFSET $6
`

type ListServicesParams struct {
	OrganizationID int64       `json:"organization_id"`
	CategoryUuid   pgtype.UUID `json:"category_uuid"`
	IsActive       pgtype.Bool `json:"is_active"`
	Q              pgtype.Text `json:"q"`
	SortBy         pgtype.Text `json:"sort_by"`
	OffsetCount    int32       `json:"offset_count"`
	LimitCount     int32       `json:"limit_count"`
}

type ListServicesRow struct {
	ID              int64              `json:"id"`
	Uuid            uuid.UUID          `json:"uuid"`
	OrganizationID  int64              `json:"organization_id"`
	CategoryID      pgtype.Int8        `json:"category_id"`
	Name            string             `json:"name"`
	Code            pgtype.Text        `json:"code"`
	DurationMinutes int32              `json:"duration_minutes"`
	Price           pgtype.Numeric     `json:"price"`
	VatRate         pgtype.Numeric     `json:"vat_rate"`
	Currency        string             `json:"currency"`
	IsActive        bool               `json:"is_active"`
	Description     string             `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	Color           string             `json:"color"`
	CategoryUuid    pgtype.UUID        `json:"category_uuid"`
	CategoryName    pgtype.Text        `json:"category_name"`
}

func (q *Queries) ListServices(ctx context.Context, arg ListServicesParams) ([]ListServicesRow, error) {
	rows, err := q.db.Query(ctx, listServices,
		arg.OrganizationID,
		arg.CategoryUuid,
		arg.IsActive,
		arg.Q,
		arg.SortBy,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesRow{}
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.CategoryID,
			&i.Name,
			&i.Code,
			&i.DurationMinutes,
			&i.Price,
			&i.VatRate,
			&i.Currency,
			&i.IsActive,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Color,
			&i.CategoryUuid,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesForExport = `-- name: ListServicesForExport :many
SELECT s.id, s.uuid, s.organization_id, s.category_id, s.name, s.code, s.duration_minutes, s.price, s.vat_rate, s.currency, s.is_active, s.description, s.created_at, s.updated_at, s.deleted_at, s.color, c.name AS category_name
FROM services s
LEFT JOIN catalog_categories c ON c.id = s.category_id AND c.deleted_at IS NULL
WHERE s.organization_id = $1 AND s.deleted_at IS NULL
  AND ($2::uuid IS NULL OR c.uuid = $2)
  AND ($3::boolean IS NULL OR s.is_active = $3)
  AND (
    $4::text IS NULL
    OR s.name ILIKE '%' || $4 || '%'
    OR s.code ILIKE '%' || $4 || '%'
  )
ORDER BY s.name ASC
`

type ListServicesForExportParams struct {
	OrganizationID int64       `json:"organization_id"`
	CategoryUuid   pgtype.UUID `json:"category_uuid"`
	IsActive       pgtype.Bool `json:"is_active"`
	Q              pgtype.Text `json:"q"`
}

type ListServicesForExportRow struct {
	ID              int64              `json:"id"`
	Uuid            uuid.UUID          `json:"uuid"`
	OrganizationID  int64              `json:"organization_id"`
	CategoryID      pgtype.Int8        `json:"category_id"`
	Name            string             `json:"name"`
	Code            pgtype.Text        `json:"code"`
	DurationMinutes int32              `json:"duration_minutes"`
	Price           pgtype.Numeric     `json:"price"`
	VatRate         pgtype.Numeric     `json:"vat_rate"`
	Currency        string             `json:"currency"`
	IsActive        bool               `json:"is_active"`
	Description     string             `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	Color           string             `json:"color"`
	CategoryName    pgtype.Text        `json:"category_name"`
}

func (q *Queries) ListServicesForExport(ctx context.Context, arg ListServicesForExportParams) ([]ListServicesForExportRow, error) {
	rows, err := q.db.Query(ctx, listServicesForExport,
		arg.OrganizationID,
		arg.CategoryUuid,
		arg.IsActive,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesForExportRow{}
	for rows.Next() {
		var i ListServicesForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.CategoryID,
			&i.Name,
			&i.Code,
			&i.DurationMinutes,
			&i.Price,
			&i.VatRate,
			&i.Currency,
			&i.IsActive,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Color,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesForSearch = `-- name: ListServicesForSearch :many
SELECT
    s.uuid,
    s.name,
    s.code,
    s.price,
    s.currency,
    s.duration_minutes,
    s.is_active,
    c.name AS category_name,
    o.uuid AS organization_uuid,
    o.slug AS organization_slug
FROM services s
JOIN organizations o ON o.id = s.organization_id AND o.deleted_at IS NULL
LEFT JOIN catalog_categories c ON c.id = s.category_id AND c.deleted_at IS NULL
WHERE s.deleted_at IS NULL
`

type ListServicesForSearchRow struct {
	Uuid             uuid.UUID      `json:"uuid"`
	Name             string         `json:"name"`
	Code             pgtype.Text    `json:"code"`
	Price            pgtype.Numeric `json:"price"`
	Currency         string         `json:"currency"`
	DurationMinutes  int32          `json:"duration_minutes"`
	IsActive         bool           `json:"is_active"`
	CategoryName     pgtype.Text    `json:"category_name"`
	OrganizationUuid uuid.UUID      `json:"organization_uuid"`
	OrganizationSlug string         `json:"organization_slug"`
}

func (q *Queries) ListServicesForSearch(ctx context.Context) ([]ListServicesForSearchRow, error) {
	rows, err := q.db.Query(ctx, listServicesForSearch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesForSearchRow{}
	for rows.Next() {
		var i ListServicesForSearchRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Code,
			&i.Price,
			&i.Currency,
			&i.DurationMinutes,
			&i.IsActive,
			&i.CategoryName,
			&i.OrganizationUuid,
			&i.OrganizationSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreProduct = `-- name: RestoreProduct :exec
UPDATE products
SET deleted_at = NULL,
    is_active = $3,
    updated_at = NOW()
WHERE uuid = $1 AND organization_id = $2
`

type RestoreProductParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
	IsActive       bool      `json:"is_active"`
}

func (q *Queries) RestoreProduct(ctx context.Context, arg RestoreProductParams) error {
	_, err := q.db.Exec(ctx, restoreProduct, arg.Uuid, arg.OrganizationID, arg.IsActive)
	return err
}

const restoreService = `-- name: RestoreService :exec
UPDATE services
SET deleted_at = NULL,
    is_active = $3,
    updated_at = NOW()
WHERE uuid = $1 AND organization_id = $2
`

type RestoreServiceParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
	IsActive       bool      `json:"is_active"`
}

func (q *Queries) RestoreService(ctx context.Context, arg RestoreServiceParams) error {
	_, err := q.db.Exec(ctx, restoreService, arg.Uuid, arg.OrganizationID, arg.IsActive)
	return err
}

const softDeleteCatalogCategory = `-- name: SoftDeleteCatalogCategory :one
UPDATE catalog_categories
SET deleted_at = NOW(), is_active = false
WHERE uuid = $1 AND organization_id = $2 AND deleted_at IS NULL
RETURNING id, uuid, organization_id, parent_id, name, kind, sort_order, is_active, created_at, updated_at, deleted_at
`

type SoftDeleteCatalogCategoryParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) SoftDeleteCatalogCategory(ctx context.Context, arg SoftDeleteCatalogCategoryParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, softDeleteCatalogCategory, arg.Uuid, arg.OrganizationID)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :one
UPDATE products
SET deleted_at = NOW(), is_active = false
WHERE uuid = $1 AND organization_id = $2 AND deleted_at IS NULL
RETURNING id, uuid, organization_id, category_id, name, sku, barcode, unit, cost_price, sale_price, vat_rate, currency, stock_quantity, min_stock_alert, track_stock, is_active, description, created_at, updated_at, deleted_at
`

type SoftDeleteProductParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, softDeleteProduct, arg.Uuid, arg.OrganizationID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.Unit,
		&i.CostPrice,
		&i.SalePrice,
		&i.VatRate,
		&i.Currency,
		&i.StockQuantity,
		&i.MinStockAlert,
		&i.TrackStock,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteService = `-- name: SoftDeleteService :one
UPDATE services
SET deleted_at = NOW(), is_active = false
WHERE uuid = $1 AND organization_id = $2 AND deleted_at IS NULL
RETURNING id, uuid, organization_id, category_id, name, code, duration_minutes, price, vat_rate, currency, is_active, description, created_at, updated_at, deleted_at, color
`

type SoftDeleteServiceParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) SoftDeleteService(ctx context.Context, arg SoftDeleteServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, softDeleteService, arg.Uuid, arg.OrganizationID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Code,
		&i.DurationMinutes,
		&i.Price,
		&i.VatRate,
		&i.Currency,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Color,
	)
	return i, err
}

const updateCatalogCategory = `-- name: UpdateCatalogCategory :one
UPDATE catalog_categories
SET name = COALESCE($1, name),
    parent_id = CASE WHEN $2::boolean = true THEN $3 ELSE parent_id END,
    kind = COALESCE($4, kind),
    sort_order = COALESCE($5, sort_order),
    is_active = COALESCE($6, is_active)
WHERE uuid = $7 AND organization_id = $8 AND deleted_at IS NULL
RETURNING id, uuid, organization_id, parent_id, name, kind, sort_order, is_active, created_at, updated_at, deleted_at
`

type UpdateCatalogCategoryParams struct {
	Name           pgtype.Text `json:"name"`
	SetParent      pgtype.Bool `json:"set_parent"`
	ParentID       pgtype.Int8 `json:"parent_id"`
	Kind           pgtype.Text `json:"kind"`
	SortOrder      pgtype.Int4 `json:"sort_order"`
	IsActive       pgtype.Bool `json:"is_active"`
	Uuid           uuid.UUID   `json:"uuid"`
	OrganizationID int64       `json:"organization_id"`
}

func (q *Queries) UpdateCatalogCategory(ctx context.Context, arg UpdateCatalogCategoryParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, updateCatalogCategory,
		arg.Name,
		arg.SetParent,
		arg.ParentID,
		arg.Kind,
		arg.SortOrder,
		arg.IsActive,
		arg.Uuid,
		arg.OrganizationID,
	)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = COALESCE($1, name),
    category_id = CASE WHEN $2::boolean = true THEN $3 ELSE category_id END,
    sku = CASE WHEN $4::boolean = true THEN $5 ELSE sku END,
    barcode = CASE WHEN $6::boolean = true THEN $7 ELSE barcode END,
    unit = COALESCE($8, unit),
    cost_price = COALESCE($9, cost_price),
    sale_price = COALESCE($10, sale_price),
    vat_rate = COALESCE($11, vat_rate),
    currency = COALESCE($12, currency),
    stock_quantity = COALESCE($13, stock_quantity),
    min_stock_alert = COALESCE($14, min_stock_alert),
    track_stock = COALESCE($15, track_stock),
    is_active = COALESCE($16, is_active),
    description = COALESCE($17, description)
WHERE uuid = $18 AND organization_id = $19 AND deleted_at IS NULL
RETURNING id, uuid, organization_id, category_id, name, sku, barcode, unit, cost_price, sale_price, vat_rate, currency, stock_quantity, min_stock_alert, track_stock, is_active, description, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	Name           pgtype.Text    `json:"name"`
	SetCategory    pgtype.Bool    `json:"set_category"`
	CategoryID     pgtype.Int8    `json:"category_id"`
	SetSku         pgtype.Bool    `json:"set_sku"`
	Sku            pgtype.Text    `json:"sku"`
	SetBarcode     pgtype.Bool    `json:"set_barcode"`
	Barcode        pgtype.Text    `json:"barcode"`
	Unit           pgtype.Text    `json:"unit"`
	CostPrice      pgtype.Numeric `json:"cost_price"`
	SalePrice      pgtype.Numeric `json:"sale_price"`
	VatRate        pgtype.Numeric `json:"vat_rate"`
	Currency       pgtype.Text    `json:"currency"`
	StockQuantity  pgtype.Numeric `json:"stock_quantity"`
	MinStockAlert  pgtype.Numeric `json:"min_stock_alert"`
	TrackStock     pgtype.Bool    `json:"track_stock"`
	IsActive       pgtype.Bool    `json:"is_active"`
	Description    pgtype.Text    `json:"description"`
	Uuid           uuid.UUID      `json:"uuid"`
	OrganizationID int64          `json:"organization_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.SetCategory,
		arg.CategoryID,
		arg.SetSku,
		arg.Sku,
		arg.SetBarcode,
		arg.Barcode,
		arg.Unit,
		arg.CostPrice,
		arg.SalePrice,
		arg.VatRate,
		arg.Currency,
		arg.StockQuantity,
		arg.MinStockAlert,
		arg.TrackStock,
		arg.IsActive,
		arg.Description,
		arg.Uuid,
		arg.OrganizationID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.Unit,
		&i.CostPrice,
		&i.SalePrice,
		&i.VatRate,
		&i.Currency,
		&i.StockQuantity,
		&i.MinStockAlert,
		&i.TrackStock,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name = COALESCE($1, name),
    category_id = CASE WHEN $2::boolean = true THEN $3 ELSE category_id END,
    code = CASE WHEN $4::boolean = true THEN $5 ELSE code END,
    duration_minutes = COALESCE($6, duration_minutes),
    price = COALESCE($7, price),
    vat_rate = COALESCE($8, vat_rate),
    currency = COALESCE($9, currency),
    is_active = COALESCE($10, is_active),
    description = COALESCE($11, description),
    color = COALESCE($12, color)
WHERE uuid = $13 AND organization_id = $14 AND deleted_at IS NULL
RETURNING id, uuid, organization_id, category_id, name, code, duration_minutes, price, vat_rate, currency, is_active, description, created_at, updated_at, deleted_at, color
`

type UpdateServiceParams struct {
	Name            pgtype.Text    `json:"name"`
	SetCategory     pgtype.Bool    `json:"set_category"`
	CategoryID      pgtype.Int8    `json:"category_id"`
	SetCode         pgtype.Bool    `json:"set_code"`
	Code            pgtype.Text    `json:"code"`
	DurationMinutes pgtype.Int4    `json:"duration_minutes"`
	Price           pgtype.Numeric `json:"price"`
	VatRate         pgtype.Numeric `json:"vat_rate"`
	Currency        pgtype.Text    `json:"currency"`
	IsActive        pgtype.Bool    `json:"is_active"`
	Description     pgtype.Text    `json:"description"`
	Color           pgtype.Text    `json:"color"`
	Uuid            uuid.UUID      `json:"uuid"`
	OrganizationID  int64          `json:"organization_id"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.Name,
		arg.SetCategory,
		arg.CategoryID,
		arg.SetCode,
		arg.Code,
		arg.DurationMinutes,
		arg.Price,
		arg.VatRate,
		arg.Currency,
		arg.IsActive,
		arg.Description,
		arg.Color,
		arg.Uuid,
		arg.OrganizationID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CategoryID,
		&i.Name,
		&i.Code,
		&i.DurationMinutes,
		&i.Price,
		&i.VatRate,
		&i.Currency,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Color,
	)
	return i, err
}
