// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contracts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countContractInstances = `-- name: CountContractInstances :one
SELECT count(*)::bigint
FROM contract_instances
WHERE organization_id = $1
  AND (
    $2::text IS NULL
    OR status = $2::text
  )
  AND (
    $3::text IS NULL
    OR subject_type = $3::text
  )
  AND (
    $4::uuid IS NULL
    OR subject_uuid = $4::uuid
  )
  AND (
    $5::text IS NULL
    OR title ILIKE '%' || $5::text || '%'
  )
`

type CountContractInstancesParams struct {
	OrganizationID int64       `json:"organization_id"`
	Status         pgtype.Text `json:"status"`
	SubjectType    pgtype.Text `json:"subject_type"`
	SubjectUuid    pgtype.UUID `json:"subject_uuid"`
	Q              pgtype.Text `json:"q"`
}

func (q *Queries) CountContractInstances(ctx context.Context, arg CountContractInstancesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContractInstances,
		arg.OrganizationID,
		arg.Status,
		arg.SubjectType,
		arg.SubjectUuid,
		arg.Q,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countContractPresets = `-- name: CountContractPresets :one
SELECT count(*)::bigint
FROM contract_presets
WHERE deleted_at IS NULL
  AND (
    $1::text IS NULL
    OR title ILIKE '%' || $1::text || '%'
    OR description ILIKE '%' || $1::text || '%'
  )
  AND (
    $2::boolean IS NULL
    OR is_active = $2::boolean
  )
`

type CountContractPresetsParams struct {
	Q        pgtype.Text `json:"q"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) CountContractPresets(ctx context.Context, arg CountContractPresetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContractPresets, arg.Q, arg.IsActive)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countContractSignerOTPsSince = `-- name: CountContractSignerOTPsSince :one
SELECT count(*)::bigint
FROM contract_signer_otps
WHERE signer_id = $1
  AND created_at >= $2
`

type CountContractSignerOTPsSinceParams struct {
	SignerID  int64              `json:"signer_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountContractSignerOTPsSince(ctx context.Context, arg CountContractSignerOTPsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContractSignerOTPsSince, arg.SignerID, arg.CreatedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countContractTemplates = `-- name: CountContractTemplates :one
SELECT count(*)::bigint
FROM contract_templates
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND (
    $2::text IS NULL
    OR title ILIKE '%' || $2::text || '%'
  )
  AND (
    $3::boolean IS NULL
    OR is_active = $3::boolean
  )
`

type CountContractTemplatesParams struct {
	OrganizationID int64       `json:"organization_id"`
	Q              pgtype.Text `json:"q"`
	IsActive       pgtype.Bool `json:"is_active"`
}

func (q *Queries) CountContractTemplates(ctx context.Context, arg CountContractTemplatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContractTemplates, arg.OrganizationID, arg.Q, arg.IsActive)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPendingRequiredSigners = `-- name: CountPendingRequiredSigners :one
SELECT count(*)::bigint
FROM contract_signers
WHERE instance_id = $1
  AND required = true
  AND status = 'pending'
`

func (q *Queries) CountPendingRequiredSigners(ctx context.Context, instanceID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingRequiredSigners, instanceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createContractInstance = `-- name: CreateContractInstance :one
INSERT INTO contract_instances (
    organization_id, template_id, title, subject_type, subject_uuid,
    content_json, content_html, variables_resolved, signature_required,
    status, created_by, number, locale, otp_required
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, uuid, organization_id, template_id, title, subject_type, subject_uuid, content_json, content_html, variables_resolved, signature_required, status, content_sha256, pdf_object_key, pdf_error, created_by, executed_at, voided_at, voided_by, created_at, updated_at, number, locale, otp_required
`

type CreateContractInstanceParams struct {
	OrganizationID    int64       `json:"organization_id"`
	TemplateID        pgtype.Int8 `json:"template_id"`
	Title             string      `json:"title"`
	SubjectType       string      `json:"subject_type"`
	SubjectUuid       uuid.UUID   `json:"subject_uuid"`
	ContentJson       []byte      `json:"content_json"`
	ContentHtml       string      `json:"content_html"`
	VariablesResolved []byte      `json:"variables_resolved"`
	SignatureRequired bool        `json:"signature_required"`
	Status            string      `json:"status"`
	CreatedBy         int64       `json:"created_by"`
	Number            int32       `json:"number"`
	Locale            string      `json:"locale"`
	OtpRequired       bool        `json:"otp_required"`
}

func (q *Queries) CreateContractInstance(ctx context.Context, arg CreateContractInstanceParams) (ContractInstance, error) {
	row := q.db.QueryRow(ctx, createContractInstance,
		arg.OrganizationID,
		arg.TemplateID,
		arg.Title,
		arg.SubjectType,
		arg.SubjectUuid,
		arg.ContentJson,
		arg.ContentHtml,
		arg.VariablesResolved,
		arg.SignatureRequired,
		arg.Status,
		arg.CreatedBy,
		arg.Number,
		arg.Locale,
		arg.OtpRequired,
	)
	var i ContractInstance
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.TemplateID,
		&i.Title,
		&i.SubjectType,
		&i.SubjectUuid,
		&i.ContentJson,
		&i.ContentHtml,
		&i.VariablesResolved,
		&i.SignatureRequired,
		&i.Status,
		&i.ContentSha256,
		&i.PdfObjectKey,
		&i.PdfError,
		&i.CreatedBy,
		&i.ExecutedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Number,
		&i.Locale,
		&i.OtpRequired,
	)
	return i, err
}

const createContractMedia = `-- name: CreateContractMedia :one
INSERT INTO contract_media (
    organization_id, instance_id, object_key, content_type, file_name,
    byte_size, caption, sort_order, uploaded_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, uuid, organization_id, instance_id, object_key, content_type, file_name, byte_size, caption, sort_order, uploaded_by, created_at
`

type CreateContractMediaParams struct {
	OrganizationID int64  `json:"organization_id"`
	InstanceID     int64  `json:"instance_id"`
	ObjectKey      string `json:"object_key"`
	ContentType    string `json:"content_type"`
	FileName       string `json:"file_name"`
	ByteSize       int64  `json:"byte_size"`
	Caption        string `json:"caption"`
	SortOrder      int32  `json:"sort_order"`
	UploadedBy     int64  `json:"uploaded_by"`
}

func (q *Queries) CreateContractMedia(ctx context.Context, arg CreateContractMediaParams) (ContractMedium, error) {
	row := q.db.QueryRow(ctx, createContractMedia,
		arg.OrganizationID,
		arg.InstanceID,
		arg.ObjectKey,
		arg.ContentType,
		arg.FileName,
		arg.ByteSize,
		arg.Caption,
		arg.SortOrder,
		arg.UploadedBy,
	)
	var i ContractMedium
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.InstanceID,
		&i.ObjectKey,
		&i.ContentType,
		&i.FileName,
		&i.ByteSize,
		&i.Caption,
		&i.SortOrder,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createContractPreset = `-- name: CreateContractPreset :one
INSERT INTO contract_presets (
    title, description, category, content_json, content_html,
    variables, signer_slots, signature_required, is_active, created_by,
    otp_required
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, uuid, title, description, category, content_json, content_html, variables, signer_slots, signature_required, is_active, created_by, created_at, updated_at, deleted_at, otp_required
`

type CreateContractPresetParams struct {
	Title             string      `json:"title"`
	Description       string      `json:"description"`
	Category          string      `json:"category"`
	ContentJson       []byte      `json:"content_json"`
	ContentHtml       string      `json:"content_html"`
	Variables         []byte      `json:"variables"`
	SignerSlots       []byte      `json:"signer_slots"`
	SignatureRequired bool        `json:"signature_required"`
	IsActive          bool        `json:"is_active"`
	CreatedBy         pgtype.Int8 `json:"created_by"`
	OtpRequired       bool        `json:"otp_required"`
}

func (q *Queries) CreateContractPreset(ctx context.Context, arg CreateContractPresetParams) (ContractPreset, error) {
	row := q.db.QueryRow(ctx, createContractPreset,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.ContentJson,
		arg.ContentHtml,
		arg.Variables,
		arg.SignerSlots,
		arg.SignatureRequired,
		arg.IsActive,
		arg.CreatedBy,
		arg.OtpRequired,
	)
	var i ContractPreset
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ContentJson,
		&i.ContentHtml,
		&i.Variables,
		&i.SignerSlots,
		&i.SignatureRequired,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OtpRequired,
	)
	return i, err
}

const createContractSignature = `-- name: CreateContractSignature :one
INSERT INTO contract_signatures (
    organization_id, instance_id, signer_id, display_name, object_key,
    content_sha256, signed_by_user_id, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, uuid, organization_id, instance_id, signer_id, display_name, object_key, content_sha256, signed_by_user_id, ip_address, user_agent, signed_at, created_at
`

type CreateContractSignatureParams struct {
	OrganizationID int64  `json:"organization_id"`
	InstanceID     int64  `json:"instance_id"`
	SignerID       int64  `json:"signer_id"`
	DisplayName    string `json:"display_name"`
	ObjectKey      string `json:"object_key"`
	ContentSha256  string `json:"content_sha256"`
	SignedByUserID int64  `json:"signed_by_user_id"`
	IpAddress      string `json:"ip_address"`
	UserAgent      string `json:"user_agent"`
}

func (q *Queries) CreateContractSignature(ctx context.Context, arg CreateContractSignatureParams) (ContractSignature, error) {
	row := q.db.QueryRow(ctx, createContractSignature,
		arg.OrganizationID,
		arg.InstanceID,
		arg.SignerID,
		arg.DisplayName,
		arg.ObjectKey,
		arg.ContentSha256,
		arg.SignedByUserID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i ContractSignature
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.InstanceID,
		&i.SignerID,
		&i.DisplayName,
		&i.ObjectKey,
		&i.ContentSha256,
		&i.SignedByUserID,
		&i.IpAddress,
		&i.UserAgent,
		&i.SignedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createContractSigner = `-- name: CreateContractSigner :one
INSERT INTO contract_signers (
    organization_id, instance_id, role, label, required, sort_order, status,
    suggested_name, phone
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, uuid, organization_id, instance_id, role, label, required, sort_order, status, created_at, updated_at, suggested_name, phone, otp_verified_at, otp_channel, otp_phone
`

type CreateContractSignerParams struct {
	OrganizationID int64  `json:"organization_id"`
	InstanceID     int64  `json:"instance_id"`
	Role           string `json:"role"`
	Label          string `json:"label"`
	Required       bool   `json:"required"`
	SortOrder      int32  `json:"sort_order"`
	Status         string `json:"status"`
	SuggestedName  string `json:"suggested_name"`
	Phone          string `json:"phone"`
}

func (q *Queries) CreateContractSigner(ctx context.Context, arg CreateContractSignerParams) (ContractSigner, error) {
	row := q.db.QueryRow(ctx, createContractSigner,
		arg.OrganizationID,
		arg.InstanceID,
		arg.Role,
		arg.Label,
		arg.Required,
		arg.SortOrder,
		arg.Status,
		arg.SuggestedName,
		arg.Phone,
	)
	var i ContractSigner
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.InstanceID,
		&i.Role,
		&i.Label,
		&i.Required,
		&i.SortOrder,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuggestedName,
		&i.Phone,
		&i.OtpVerifiedAt,
		&i.OtpChannel,
		&i.OtpPhone,
	)
	return i, err
}

const createContractSignerOTP = `-- name: CreateContractSignerOTP :one
INSERT INTO contract_signer_otps (
    organization_id, instance_id, signer_id, channel, phone, code_hash,
    message_sha256, provider_reference, max_attempts, expires_at,
    sent_by_user_id, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, uuid, organization_id, instance_id, signer_id, channel, phone, code_hash, message_sha256, provider_reference, attempts, max_attempts, expires_at, verified_at, sent_by_user_id, ip_address, user_agent, created_at
`

type CreateContractSignerOTPParams struct {
	OrganizationID    int64              `json:"organization_id"`
	InstanceID        int64              `json:"instance_id"`
	SignerID          int64              `json:"signer_id"`
	Channel           string             `json:"channel"`
	Phone             string             `json:"phone"`
	CodeHash          string             `json:"code_hash"`
	MessageSha256     string             `json:"message_sha256"`
	ProviderReference string             `json:"provider_reference"`
	MaxAttempts       int32              `json:"max_attempts"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	SentByUserID      int64              `json:"sent_by_user_id"`
	IpAddress         string             `json:"ip_address"`
	UserAgent         string             `json:"user_agent"`
}

func (q *Queries) CreateContractSignerOTP(ctx context.Context, arg CreateContractSignerOTPParams) (ContractSignerOtp, error) {
	row := q.db.QueryRow(ctx, createContractSignerOTP,
		arg.OrganizationID,
		arg.InstanceID,
		arg.SignerID,
		arg.Channel,
		arg.Phone,
		arg.CodeHash,
		arg.MessageSha256,
		arg.ProviderReference,
		arg.MaxAttempts,
		arg.ExpiresAt,
		arg.SentByUserID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i ContractSignerOtp
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.InstanceID,
		&i.SignerID,
		&i.Channel,
		&i.Phone,
		&i.CodeHash,
		&i.MessageSha256,
		&i.ProviderReference,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.SentByUserID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const createContractTemplate = `-- name: CreateContractTemplate :one
INSERT INTO contract_templates (
    organization_id, preset_id, title, description, category,
    content_json, content_html, variables, signer_slots,
    signature_required, is_active, created_by, otp_required
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, uuid, organization_id, preset_id, title, description, category, content_json, content_html, variables, signer_slots, signature_required, is_active, created_by, created_at, updated_at, deleted_at, otp_required
`

type CreateContractTemplateParams struct {
	OrganizationID    int64       `json:"organization_id"`
	PresetID          pgtype.Int8 `json:"preset_id"`
	Title             string      `json:"title"`
	Description       string      `json:"description"`
	Category          string      `json:"category"`
	ContentJson       []byte      `json:"content_json"`
	ContentHtml       string      `json:"content_html"`
	Variables         []byte      `json:"variables"`
	SignerSlots       []byte      `json:"signer_slots"`
	SignatureRequired bool        `json:"signature_required"`
	IsActive          bool        `json:"is_active"`
	CreatedBy         int64       `json:"created_by"`
	OtpRequired       bool        `json:"otp_required"`
}

func (q *Queries) CreateContractTemplate(ctx context.Context, arg CreateContractTemplateParams) (ContractTemplate, error) {
	row := q.db.QueryRow(ctx, createContractTemplate,
		arg.OrganizationID,
		arg.PresetID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.ContentJson,
		arg.ContentHtml,
		arg.Variables,
		arg.SignerSlots,
		arg.SignatureRequired,
		arg.IsActive,
		arg.CreatedBy,
		arg.OtpRequired,
	)
	var i ContractTemplate
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.PresetID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ContentJson,
		&i.ContentHtml,
		&i.Variables,
		&i.SignerSlots,
		&i.SignatureRequired,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OtpRequired,
	)
	return i, err
}

const deleteContractMedia = `-- name: DeleteContractMedia :exec
DELETE FROM contract_media
WHERE uuid = $1 AND organization_id = $2 AND instance_id = $3
`

type DeleteContractMediaParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
	InstanceID     int64     `json:"instance_id"`
}

func (q *Queries) DeleteContractMedia(ctx context.Context, arg DeleteContractMediaParams) error {
	_, err := q.db.Exec(ctx, deleteContractMedia, arg.Uuid, arg.OrganizationID, arg.InstanceID)
	return err
}

const getContractInstanceByID = `-- name: GetContractInstanceByID :one
SELECT id, uuid, organization_id, template_id, title, subject_type, subject_uuid, content_json, content_html, variables_resolved, signature_required, status, content_sha256, pdf_object_key, pdf_error, created_by, executed_at, voided_at, voided_by, created_at, updated_at, number, locale, otp_required
FROM contract_instances
WHERE id = $1
`

func (q *Queries) GetContractInstanceByID(ctx context.Context, id int64) (ContractInstance, error) {
	row := q.db.QueryRow(ctx, getContractInstanceByID, id)
	var i ContractInstance
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.TemplateID,
		&i.Title,
		&i.SubjectType,
		&i.SubjectUuid,
		&i.ContentJson,
		&i.ContentHtml,
		&i.VariablesResolved,
		&i.SignatureRequired,
		&i.Status,
		&i.ContentSha256,
		&i.PdfObjectKey,
		&i.PdfError,
		&i.CreatedBy,
		&i.ExecutedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Number,
		&i.Locale,
		&i.OtpRequired,
	)
	return i, err
}

const getContractInstanceByUUID = `-- name: GetContractInstanceByUUID :one
SELECT id, uuid, organization_id, template_id, title, subject_type, subject_uuid, content_json, content_html, variables_resolved, signature_required, status, content_sha256, pdf_object_key, pdf_error, created_by, executed_at, voided_at, voided_by, created_at, updated_at, number, locale, otp_required
FROM contract_instances
WHERE uuid = $1 AND organization_id = $2
`

type GetContractInstanceByUUIDParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) GetContractInstanceByUUID(ctx context.Context, arg GetContractInstanceByUUIDParams) (ContractInstance, error) {
	row := q.db.QueryRow(ctx, getContractInstanceByUUID, arg.Uuid, arg.OrganizationID)
	var i ContractInstance
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.TemplateID,
		&i.Title,
		&i.SubjectType,
		&i.SubjectUuid,
		&i.ContentJson,
		&i.ContentHtml,
		&i.VariablesResolved,
		&i.SignatureRequired,
		&i.Status,
		&i.ContentSha256,
		&i.PdfObjectKey,
		&i.PdfError,
		&i.CreatedBy,
		&i.ExecutedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Number,
		&i.Locale,
		&i.OtpRequired,
	)
	return i, err
}

const getContractMediaByUUID = `-- name: GetContractMediaByUUID :one
SELECT id, uuid, organization_id, instance_id, object_key, content_type, file_name, byte_size, caption, sort_order, uploaded_by, created_at
FROM contract_media
WHERE uuid = $1 AND organization_id = $2 AND instance_id = $3
`

type GetContractMediaByUUIDParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
	InstanceID     int64     `json:"instance_id"`
}

func (q *Queries) GetContractMediaByUUID(ctx context.Context, arg GetContractMediaByUUIDParams) (ContractMedium, error) {
	row := q.db.QueryRow(ctx, getContractMediaByUUID, arg.Uuid, arg.OrganizationID, arg.InstanceID)
	var i ContractMedium
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.InstanceID,
		&i.ObjectKey,
		&i.ContentType,
		&i.FileName,
		&i.ByteSize,
		&i.Caption,
		&i.SortOrder,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getContractPresetByUUID = `-- name: GetContractPresetByUUID :one
SELECT id, uuid, title, description, category, content_json, content_html, variables, signer_slots, signature_required, is_active, created_by, created_at, updated_at, deleted_at, otp_required
FROM contract_presets
WHERE uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetContractPresetByUUID(ctx context.Context, argUuid uuid.UUID) (ContractPreset, error) {
	row := q.db.QueryRow(ctx, getContractPresetByUUID, argUuid)
	var i ContractPreset
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ContentJson,
		&i.ContentHtml,
		&i.Variables,
		&i.SignerSlots,
		&i.SignatureRequired,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OtpRequired,
	)
	return i, err
}

const getContractSignerByUUID = `-- name: GetContractSignerByUUID :one
SELECT id, uuid, organization_id, instance_id, role, label, required, sort_order, status, created_at, updated_at, suggested_name, phone, otp_verified_at, otp_channel, otp_phone
FROM contract_signers
WHERE uuid = $1
  AND organization_id = $2
  AND instance_id = $3
`

type GetContractSignerByUUIDParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
	InstanceID     int64     `json:"instance_id"`
}

func (q *Queries) GetContractSignerByUUID(ctx context.Context, arg GetContractSignerByUUIDParams) (ContractSigner, error) {
	row := q.db.QueryRow(ctx, getContractSignerByUUID, arg.Uuid, arg.OrganizationID, arg.InstanceID)
	var i ContractSigner
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.InstanceID,
		&i.Role,
		&i.Label,
		&i.Required,
		&i.SortOrder,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuggestedName,
		&i.Phone,
		&i.OtpVerifiedAt,
		&i.OtpChannel,
		&i.OtpPhone,
	)
	return i, err
}

const getContractTemplateByUUID = `-- name: GetContractTemplateByUUID :one
SELECT id, uuid, organization_id, preset_id, title, description, category, content_json, content_html, variables, signer_slots, signature_required, is_active, created_by, created_at, updated_at, deleted_at, otp_required
FROM contract_templates
WHERE uuid = $1
  AND organization_id = $2
  AND deleted_at IS NULL
`

type GetContractTemplateByUUIDParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) GetContractTemplateByUUID(ctx context.Context, arg GetContractTemplateByUUIDParams) (ContractTemplate, error) {
	row := q.db.QueryRow(ctx, getContractTemplateByUUID, arg.Uuid, arg.OrganizationID)
	var i ContractTemplate
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.PresetID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ContentJson,
		&i.ContentHtml,
		&i.Variables,
		&i.SignerSlots,
		&i.SignatureRequired,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OtpRequired,
	)
	return i, err
}

const getLatestContractSignerOTP = `-- name: GetLatestContractSignerOTP :one
SELECT id, uuid, organization_id, instance_id, signer_id, channel, phone, code_hash, message_sha256, provider_reference, attempts, max_attempts, expires_at, verified_at, sent_by_user_id, ip_address, user_agent, created_at
FROM contract_signer_otps
WHERE signer_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestContractSignerOTP(ctx context.Context, signerID int64) (ContractSignerOtp, error) {
	row := q.db.QueryRow(ctx, getLatestContractSignerOTP, signerID)
	var i ContractSignerOtp
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.InstanceID,
		&i.SignerID,
		&i.Channel,
		&i.Phone,
		&i.CodeHash,
		&i.MessageSha256,
		&i.ProviderReference,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.SentByUserID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const incrementContractSignerOTPAttempts = `-- name: IncrementContractSignerOTPAttempts :one
UPDATE contract_signer_otps
SET attempts = attempts + 1
WHERE id = $1
RETURNING id, uuid, organization_id, instance_id, signer_id, channel, phone, code_hash, message_sha256, provider_reference, attempts, max_attempts, expires_at, verified_at, sent_by_user_id, ip_address, user_agent, created_at
`

func (q *Queries) IncrementContractSignerOTPAttempts(ctx context.Context, id int64) (ContractSignerOtp, error) {
	row := q.db.QueryRow(ctx, incrementContractSignerOTPAttempts, id)
	var i ContractSignerOtp
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.InstanceID,
		&i.SignerID,
		&i.Channel,
		&i.Phone,
		&i.CodeHash,
		&i.MessageSha256,
		&i.ProviderReference,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.SentByUserID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listContractInstances = `-- name: ListContractInstances :many
SELECT id, uuid, organization_id, template_id, title, subject_type, subject_uuid, content_json, content_html, variables_resolved, signature_required, status, content_sha256, pdf_object_key, pdf_error, created_by, executed_at, voided_at, voided_by, created_at, updated_at, number, locale, otp_required
FROM contract_instances
WHERE organization_id = $1
  AND (
    $2::text IS NULL
    OR status = $2::text
  )
  AND (
    $3::text IS NULL
    OR subject_type = $3::text
  )
  AND (
    $4::uuid IS NULL
    OR subject_uuid = $4::uuid
  )
  AND (
    $5::text IS NULL
    OR title ILIKE '%' || $5::text || '%'
  )
ORDER BY created_at DESC
LIMIT $7 OFFSET $6
`

type ListContractInstancesParams struct {
	OrganizationID int64       `json:"organization_id"`
	Status         pgtype.Text `json:"status"`
	SubjectType    pgtype.Text `json:"subject_type"`
	SubjectUuid    pgtype.UUID `json:"subject_uuid"`
	Q              pgtype.Text `json:"q"`
	OffsetCount    int32       `json:"offset_count"`
	LimitCount     int32       `json:"limit_count"`
}

func (q *Queries) ListContractInstances(ctx context.Context, arg ListContractInstancesParams) ([]ContractInstance, error) {
	rows, err := q.db.Query(ctx, listContractInstances,
		arg.OrganizationID,
		arg.Status,
		arg.SubjectType,
		arg.SubjectUuid,
		arg.Q,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContractInstance{}
	for rows.Next() {
		var i ContractInstance
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.TemplateID,
			&i.Title,
			&i.SubjectType,
			&i.SubjectUuid,
			&i.ContentJson,
			&i.ContentHtml,
			&i.VariablesResolved,
			&i.SignatureRequired,
			&i.Status,
			&i.ContentSha256,
			&i.PdfObjectKey,
			&i.PdfError,
			&i.CreatedBy,
			&i.ExecutedAt,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Number,
			&i.Locale,
			&i.OtpRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractMediaByInstance = `-- name: ListContractMediaByInstance :many
SELECT id, uuid, organization_id, instance_id, object_key, content_type, file_name, byte_size, caption, sort_order, uploaded_by, created_at
FROM contract_media
WHERE instance_id = $1
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListContractMediaByInstance(ctx context.Context, instanceID int64) ([]ContractMedium, error) {
	rows, err := q.db.Query(ctx, listContractMediaByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContractMedium{}
	for rows.Next() {
		var i ContractMedium
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.InstanceID,
			&i.ObjectKey,
			&i.ContentType,
			&i.FileName,
			&i.ByteSize,
			&i.Caption,
			&i.SortOrder,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractPresets = `-- name: ListContractPresets :many
SELECT id, uuid, title, description, category, content_json, content_html, variables, signer_slots, signature_required, is_active, created_by, created_at, updated_at, deleted_at, otp_required
FROM contract_presets
WHERE deleted_at IS NULL
  AND (
    $1::text IS NULL
    OR title ILIKE '%' || $1::text || '%'
    OR description ILIKE '%' || $1::text || '%'
  )
  AND (
    $2::boolean IS NULL
    OR is_active = $2::boolean
  )
ORDER BY
  CASE WHEN $3 = 'title' THEN title END ASC,
  CASE WHEN $3 = '-title' THEN title END DESC,
  CASE WHEN $3 = 'created_at' THEN created_at END ASC,
  CASE WHEN $3 = '-created_at' THEN created_at END DESC,
  created_at DESC
LIMIT $5 OFFSET $4
`

type ListContractPresetsParams struct {
	Q           pgtype.Text `json:"q"`
	IsActive    pgtype.Bool `json:"is_active"`
	Sort        interface{} `json:"sort"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListContractPresets(ctx context.Context, arg ListContractPresetsParams) ([]ContractPreset, error) {
	rows, err := q.db.Query(ctx, listContractPresets,
		arg.Q,
		arg.IsActive,
		arg.Sort,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContractPreset{}
	for rows.Next() {
		var i ContractPreset
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.ContentJson,
			&i.ContentHtml,
			&i.Variables,
			&i.SignerSlots,
			&i.SignatureRequired,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OtpRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractSignaturesByInstance = `-- name: ListContractSignaturesByInstance :many
SELECT id, uuid, organization_id, instance_id, signer_id, display_name, object_key, content_sha256, signed_by_user_id, ip_address, user_agent, signed_at, created_at
FROM contract_signatures
WHERE instance_id = $1
ORDER BY signed_at ASC
`

func (q *Queries) ListContractSignaturesByInstance(ctx context.Context, instanceID int64) ([]ContractSignature, error) {
	rows, err := q.db.Query(ctx, listContractSignaturesByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContractSignature{}
	for rows.Next() {
		var i ContractSignature
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.InstanceID,
			&i.SignerID,
			&i.DisplayName,
			&i.ObjectKey,
			&i.ContentSha256,
			&i.SignedByUserID,
			&i.IpAddress,
			&i.UserAgent,
			&i.SignedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractSignersByInstance = `-- name: ListContractSignersByInstance :many
SELECT id, uuid, organization_id, instance_id, role, label, required, sort_order, status, created_at, updated_at, suggested_name, phone, otp_verified_at, otp_channel, otp_phone
FROM contract_signers
WHERE instance_id = $1
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListContractSignersByInstance(ctx context.Context, instanceID int64) ([]ContractSigner, error) {
	rows, err := q.db.Query(ctx, listContractSignersByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContractSigner{}
	for rows.Next() {
		var i ContractSigner
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.InstanceID,
			&i.Role,
			&i.Label,
			&i.Required,
			&i.SortOrder,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuggestedName,
			&i.Phone,
			&i.OtpVerifiedAt,
			&i.OtpChannel,
			&i.OtpPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractTemplates = `-- name: ListContractTemplates :many
SELECT id, uuid, organization_id, preset_id, title, description, category, content_json, content_html, variables, signer_slots, signature_required, is_active, created_by, created_at, updated_at, deleted_at, otp_required
FROM contract_templates
WHERE organization_id = $1
  AND deleted_at IS NULL
  AND (
    $2::text IS NULL
    OR title ILIKE '%' || $2::text || '%'
  )
  AND (
    $3::boolean IS NULL
    OR is_active = $3::boolean
  )
ORDER BY
  CASE WHEN $4 = 'title' THEN title END ASC,
  CASE WHEN $4 = '-title' THEN title END DESC,
  CASE WHEN $4 = 'created_at' THEN created_at END ASC,
  CASE WHEN $4 = '-created_at' THEN created_at END DESC,
  created_at DESC
LIMIT $6 OFFSET $5
`

type ListContractTemplatesParams struct {
	OrganizationID int64       `json:"organization_id"`
	Q              pgtype.Text `json:"q"`
	IsActive       pgtype.Bool `json:"is_active"`
	Sort           interface{} `json:"sort"`
	OffsetCount    int32       `json:"offset_count"`
	LimitCount     int32       `json:"limit_count"`
}

func (q *Queries) ListContractTemplates(ctx context.Context, arg ListContractTemplatesParams) ([]ContractTemplate, error) {
	rows, err := q.db.Query(ctx, listContractTemplates,
		arg.OrganizationID,
		arg.Q,
		arg.IsActive,
		arg.Sort,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContractTemplate{}
	for rows.Next() {
		var i ContractTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.PresetID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.ContentJson,
			&i.ContentHtml,
			&i.Variables,
			&i.SignerSlots,
			&i.SignatureRequired,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OtpRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markContractSignerOTPVerified = `-- name: MarkContractSignerOTPVerified :one
UPDATE contract_signers
SET otp_verified_at = $2,
    otp_channel = $3,
    otp_phone = $4
WHERE id = $1
RETURNING id, uuid, organization_id, instance_id, role, label, required, sort_order, status, created_at, updated_at, suggested_name, phone, otp_verified_at, otp_channel, otp_phone
`

type MarkContractSignerOTPVerifiedParams struct {
	ID            int64              `json:"id"`
	OtpVerifiedAt pgtype.Timestamptz `json:"otp_verified_at"`
	OtpChannel    string             `json:"otp_channel"`
	OtpPhone      string             `json:"otp_phone"`
}

func (q *Queries) MarkContractSignerOTPVerified(ctx context.Context, arg MarkContractSignerOTPVerifiedParams) (ContractSigner, error) {
	row := q.db.QueryRow(ctx, markContractSignerOTPVerified,
		arg.ID,
		arg.OtpVerifiedAt,
		arg.OtpChannel,
		arg.OtpPhone,
	)
	var i ContractSigner
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.InstanceID,
		&i.Role,
		&i.Label,
		&i.Required,
		&i.SortOrder,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuggestedName,
		&i.Phone,
		&i.OtpVerifiedAt,
		&i.OtpChannel,
		&i.OtpPhone,
	)
	return i, err
}

const markContractSignerOTPVerifiedAt = `-- name: MarkContractSignerOTPVerifiedAt :exec
UPDATE contract_signer_otps
SET verified_at = $2
WHERE id = $1
`

type MarkContractSignerOTPVerifiedAtParams struct {
	ID         int64              `json:"id"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) MarkContractSignerOTPVerifiedAt(ctx context.Context, arg MarkContractSignerOTPVerifiedAtParams) error {
	_, err := q.db.Exec(ctx, markContractSignerOTPVerifiedAt, arg.ID, arg.VerifiedAt)
	return err
}

const markContractSignerSigned = `-- name: MarkContractSignerSigned :one
UPDATE contract_signers
SET status = 'signed'
WHERE id = $1
RETURNING id, uuid, organization_id, instance_id, role, label, required, sort_order, status, created_at, updated_at, suggested_name, phone, otp_verified_at, otp_channel, otp_phone
`

func (q *Queries) MarkContractSignerSigned(ctx context.Context, id int64) (ContractSigner, error) {
	row := q.db.QueryRow(ctx, markContractSignerSigned, id)
	var i ContractSigner
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.InstanceID,
		&i.Role,
		&i.Label,
		&i.Required,
		&i.SortOrder,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuggestedName,
		&i.Phone,
		&i.OtpVerifiedAt,
		&i.OtpChannel,
		&i.OtpPhone,
	)
	return i, err
}

const nextContractInstanceNumber = `-- name: NextContractInstanceNumber :one
SELECT COALESCE(MAX(number), 0)::int + 1
FROM contract_instances
WHERE organization_id = $1
`

func (q *Queries) NextContractInstanceNumber(ctx context.Context, organizationID int64) (int32, error) {
	row := q.db.QueryRow(ctx, nextContractInstanceNumber, organizationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setContractInstancePDFError = `-- name: SetContractInstancePDFError :exec
UPDATE contract_instances
SET pdf_error = $2
WHERE id = $1
`

type SetContractInstancePDFErrorParams struct {
	ID       int64  `json:"id"`
	PdfError string `json:"pdf_error"`
}

func (q *Queries) SetContractInstancePDFError(ctx context.Context, arg SetContractInstancePDFErrorParams) error {
	_, err := q.db.Exec(ctx, setContractInstancePDFError, arg.ID, arg.PdfError)
	return err
}

const softDeleteContractPreset = `-- name: SoftDeleteContractPreset :exec
UPDATE contract_presets
SET deleted_at = NOW(), is_active = false
WHERE uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteContractPreset(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteContractPreset, argUuid)
	return err
}

const softDeleteContractTemplate = `-- name: SoftDeleteContractTemplate :exec
UPDATE contract_templates
SET deleted_at = NOW(), is_active = false
WHERE uuid = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type SoftDeleteContractTemplateParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) SoftDeleteContractTemplate(ctx context.Context, arg SoftDeleteContractTemplateParams) error {
	_, err := q.db.Exec(ctx, softDeleteContractTemplate, arg.Uuid, arg.OrganizationID)
	return err
}

const updateContractInstanceStatus = `-- name: UpdateContractInstanceStatus :one
UPDATE contract_instances
SET
    status = $3,
    content_sha256 = COALESCE($4, content_sha256),
    pdf_object_key = COALESCE($5, pdf_object_key),
    pdf_error = COALESCE($6, pdf_error),
    executed_at = COALESCE($7, executed_at),
    voided_at = COALESCE($8, voided_at),
    voided_by = COALESCE($9, voided_by)
WHERE id = $1 AND organization_id = $2
RETURNING id, uuid, organization_id, template_id, title, subject_type, subject_uuid, content_json, content_html, variables_resolved, signature_required, status, content_sha256, pdf_object_key, pdf_error, created_by, executed_at, voided_at, voided_by, created_at, updated_at, number, locale, otp_required
`

type UpdateContractInstanceStatusParams struct {
	ID             int64              `json:"id"`
	OrganizationID int64              `json:"organization_id"`
	Status         string             `json:"status"`
	ContentSha256  pgtype.Text        `json:"content_sha256"`
	PdfObjectKey   pgtype.Text        `json:"pdf_object_key"`
	PdfError       pgtype.Text        `json:"pdf_error"`
	ExecutedAt     pgtype.Timestamptz `json:"executed_at"`
	VoidedAt       pgtype.Timestamptz `json:"voided_at"`
	VoidedBy       pgtype.Int8        `json:"voided_by"`
}

func (q *Queries) UpdateContractInstanceStatus(ctx context.Context, arg UpdateContractInstanceStatusParams) (ContractInstance, error) {
	row := q.db.QueryRow(ctx, updateContractInstanceStatus,
		arg.ID,
		arg.OrganizationID,
		arg.Status,
		arg.ContentSha256,
		arg.PdfObjectKey,
		arg.PdfError,
		arg.ExecutedAt,
		arg.VoidedAt,
		arg.VoidedBy,
	)
	var i ContractInstance
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.TemplateID,
		&i.Title,
		&i.SubjectType,
		&i.SubjectUuid,
		&i.ContentJson,
		&i.ContentHtml,
		&i.VariablesResolved,
		&i.SignatureRequired,
		&i.Status,
		&i.ContentSha256,
		&i.PdfObjectKey,
		&i.PdfError,
		&i.CreatedBy,
		&i.ExecutedAt,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Number,
		&i.Locale,
		&i.OtpRequired,
	)
	return i, err
}

const updateContractPreset = `-- name: UpdateContractPreset :one
UPDATE contract_presets
SET
    title = COALESCE($1, title),
    description = COALESCE($2, description),
    category = COALESCE($3, category),
    content_json = COALESCE($4, content_json),
    content_html = COALESCE($5, content_html),
    variables = COALESCE($6, variables),
    signer_slots = COALESCE($7, signer_slots),
    signature_required = COALESCE($8, signature_required),
    otp_required = COALESCE($9, otp_required),
    is_active = COALESCE($10, is_active)
WHERE uuid = $11 AND deleted_at IS NULL
RETURNING id, uuid, title, description, category, content_json, content_html, variables, signer_slots, signature_required, is_active, created_by, created_at, updated_at, deleted_at, otp_required
`

type UpdateContractPresetParams struct {
	Title             pgtype.Text `json:"title"`
	Description       pgtype.Text `json:"description"`
	Category          pgtype.Text `json:"category"`
	ContentJson       []byte      `json:"content_json"`
	ContentHtml       pgtype.Text `json:"content_html"`
	Variables         []byte      `json:"variables"`
	SignerSlots       []byte      `json:"signer_slots"`
	SignatureRequired pgtype.Bool `json:"signature_required"`
	OtpRequired       pgtype.Bool `json:"otp_required"`
	IsActive          pgtype.Bool `json:"is_active"`
	Uuid              uuid.UUID   `json:"uuid"`
}

func (q *Queries) UpdateContractPreset(ctx context.Context, arg UpdateContractPresetParams) (ContractPreset, error) {
	row := q.db.QueryRow(ctx, updateContractPreset,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.ContentJson,
		arg.ContentHtml,
		arg.Variables,
		arg.SignerSlots,
		arg.SignatureRequired,
		arg.OtpRequired,
		arg.IsActive,
		arg.Uuid,
	)
	var i ContractPreset
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ContentJson,
		&i.ContentHtml,
		&i.Variables,
		&i.SignerSlots,
		&i.SignatureRequired,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OtpRequired,
	)
	return i, err
}

const updateContractSignerPhone = `-- name: UpdateContractSignerPhone :exec
UPDATE contract_signers
SET phone = $2
WHERE id = $1
`

type UpdateContractSignerPhoneParams struct {
	ID    int64  `json:"id"`
	Phone string `json:"phone"`
}

func (q *Queries) UpdateContractSignerPhone(ctx context.Context, arg UpdateContractSignerPhoneParams) error {
	_, err := q.db.Exec(ctx, updateContractSignerPhone, arg.ID, arg.Phone)
	return err
}

const updateContractTemplate = `-- name: UpdateContractTemplate :one
UPDATE contract_templates
SET
    title = COALESCE($1, title),
    description = COALESCE($2, description),
    category = COALESCE($3, category),
    content_json = COALESCE($4, content_json),
    content_html = COALESCE($5, content_html),
    variables = COALESCE($6, variables),
    signer_slots = COALESCE($7, signer_slots),
    signature_required = COALESCE($8, signature_required),
    otp_required = COALESCE($9, otp_required),
    is_active = COALESCE($10, is_active)
WHERE uuid = $11
  AND organization_id = $12
  AND deleted_at IS NULL
RETURNING id, uuid, organization_id, preset_id, title, description, category, content_json, content_html, variables, signer_slots, signature_required, is_active, created_by, created_at, updated_at, deleted_at, otp_required
`

type UpdateContractTemplateParams struct {
	Title             pgtype.Text `json:"title"`
	Description       pgtype.Text `json:"description"`
	Category          pgtype.Text `json:"category"`
	ContentJson       []byte      `json:"content_json"`
	ContentHtml       pgtype.Text `json:"content_html"`
	Variables         []byte      `json:"variables"`
	SignerSlots       []byte      `json:"signer_slots"`
	SignatureRequired pgtype.Bool `json:"signature_required"`
	OtpRequired       pgtype.Bool `json:"otp_required"`
	IsActive          pgtype.Bool `json:"is_active"`
	Uuid              uuid.UUID   `json:"uuid"`
	OrganizationID    int64       `json:"organization_id"`
}

func (q *Queries) UpdateContractTemplate(ctx context.Context, arg UpdateContractTemplateParams) (ContractTemplate, error) {
	row := q.db.QueryRow(ctx, updateContractTemplate,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.ContentJson,
		arg.ContentHtml,
		arg.Variables,
		arg.SignerSlots,
		arg.SignatureRequired,
		arg.OtpRequired,
		arg.IsActive,
		arg.Uuid,
		arg.OrganizationID,
	)
	var i ContractTemplate
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.PresetID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ContentJson,
		&i.ContentHtml,
		&i.Variables,
		&i.SignerSlots,
		&i.SignatureRequired,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OtpRequired,
	)
	return i, err
}
