// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: export_jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAllExportJobs = `-- name: CountAllExportJobs :one
SELECT COUNT(*)::bigint FROM export_jobs
`

func (q *Queries) CountAllExportJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllExportJobs)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countExportJobsForActor = `-- name: CountExportJobsForActor :one
SELECT COUNT(*)::bigint FROM export_jobs WHERE actor_id = $1
`

func (q *Queries) CountExportJobsForActor(ctx context.Context, actorID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countExportJobsForActor, actorID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createExportJob = `-- name: CreateExportJob :one
INSERT INTO export_jobs (resource, actor_id, format, query_json, locale, status, expires_at)
VALUES ($1, $2, $3, $4, $5, 'queued', $6)
RETURNING id, uuid, resource, actor_id, format, query_json, locale, status, file_key, row_count, error, expires_at, created_at, updated_at
`

type CreateExportJobParams struct {
	Resource  string             `json:"resource"`
	ActorID   int64              `json:"actor_id"`
	Format    string             `json:"format"`
	QueryJson []byte             `json:"query_json"`
	Locale    string             `json:"locale"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateExportJob(ctx context.Context, arg CreateExportJobParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, createExportJob,
		arg.Resource,
		arg.ActorID,
		arg.Format,
		arg.QueryJson,
		arg.Locale,
		arg.ExpiresAt,
	)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.QueryJson,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.RowCount,
		&i.Error,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExportJobByID = `-- name: GetExportJobByID :one
SELECT id, uuid, resource, actor_id, format, query_json, locale, status, file_key, row_count, error, expires_at, created_at, updated_at FROM export_jobs WHERE id = $1
`

func (q *Queries) GetExportJobByID(ctx context.Context, id int64) (ExportJob, error) {
	row := q.db.QueryRow(ctx, getExportJobByID, id)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.QueryJson,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.RowCount,
		&i.Error,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExportJobByUUID = `-- name: GetExportJobByUUID :one
SELECT id, uuid, resource, actor_id, format, query_json, locale, status, file_key, row_count, error, expires_at, created_at, updated_at FROM export_jobs WHERE uuid = $1
`

func (q *Queries) GetExportJobByUUID(ctx context.Context, argUuid uuid.UUID) (ExportJob, error) {
	row := q.db.QueryRow(ctx, getExportJobByUUID, argUuid)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.QueryJson,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.RowCount,
		&i.Error,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllExportJobs = `-- name: ListAllExportJobs :many
SELECT id, uuid, resource, actor_id, format, query_json, locale, status, file_key, row_count, error, expires_at, created_at, updated_at FROM export_jobs
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListAllExportJobsParams struct {
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListAllExportJobs(ctx context.Context, arg ListAllExportJobsParams) ([]ExportJob, error) {
	rows, err := q.db.Query(ctx, listAllExportJobs, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportJob{}
	for rows.Next() {
		var i ExportJob
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Resource,
			&i.ActorID,
			&i.Format,
			&i.QueryJson,
			&i.Locale,
			&i.Status,
			&i.FileKey,
			&i.RowCount,
			&i.Error,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportJobsForActor = `-- name: ListExportJobsForActor :many
SELECT id, uuid, resource, actor_id, format, query_json, locale, status, file_key, row_count, error, expires_at, created_at, updated_at FROM export_jobs
WHERE actor_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListExportJobsForActorParams struct {
	ActorID     int64 `json:"actor_id"`
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListExportJobsForActor(ctx context.Context, arg ListExportJobsForActorParams) ([]ExportJob, error) {
	rows, err := q.db.Query(ctx, listExportJobsForActor, arg.ActorID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportJob{}
	for rows.Next() {
		var i ExportJob
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Resource,
			&i.ActorID,
			&i.Format,
			&i.QueryJson,
			&i.Locale,
			&i.Status,
			&i.FileKey,
			&i.RowCount,
			&i.Error,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExportJobCompleted = `-- name: MarkExportJobCompleted :one
UPDATE export_jobs
SET status = 'completed',
    file_key = $2,
    row_count = $3
WHERE id = $1
RETURNING id, uuid, resource, actor_id, format, query_json, locale, status, file_key, row_count, error, expires_at, created_at, updated_at
`

type MarkExportJobCompletedParams struct {
	ID       int64       `json:"id"`
	FileKey  pgtype.Text `json:"file_key"`
	RowCount int32       `json:"row_count"`
}

func (q *Queries) MarkExportJobCompleted(ctx context.Context, arg MarkExportJobCompletedParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, markExportJobCompleted, arg.ID, arg.FileKey, arg.RowCount)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.QueryJson,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.RowCount,
		&i.Error,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markExportJobFailed = `-- name: MarkExportJobFailed :one
UPDATE export_jobs
SET status = 'failed',
    error = $2
WHERE id = $1
RETURNING id, uuid, resource, actor_id, format, query_json, locale, status, file_key, row_count, error, expires_at, created_at, updated_at
`

type MarkExportJobFailedParams struct {
	ID    int64       `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) MarkExportJobFailed(ctx context.Context, arg MarkExportJobFailedParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, markExportJobFailed, arg.ID, arg.Error)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.QueryJson,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.RowCount,
		&i.Error,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markExportJobProcessing = `-- name: MarkExportJobProcessing :one
UPDATE export_jobs
SET status = 'processing'
WHERE id = $1 AND status = 'queued'
RETURNING id, uuid, resource, actor_id, format, query_json, locale, status, file_key, row_count, error, expires_at, created_at, updated_at
`

func (q *Queries) MarkExportJobProcessing(ctx context.Context, id int64) (ExportJob, error) {
	row := q.db.QueryRow(ctx, markExportJobProcessing, id)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.QueryJson,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.RowCount,
		&i.Error,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
