// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import_jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAllImportJobs = `-- name: CountAllImportJobs :one
SELECT COUNT(*)::bigint FROM import_jobs WHERE organization_id IS NULL
`

func (q *Queries) CountAllImportJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllImportJobs)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countImportJobsForActor = `-- name: CountImportJobsForActor :one
SELECT COUNT(*)::bigint FROM import_jobs WHERE actor_id = $1 AND organization_id IS NULL
`

func (q *Queries) CountImportJobsForActor(ctx context.Context, actorID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countImportJobsForActor, actorID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countImportJobsForOrganization = `-- name: CountImportJobsForOrganization :one
SELECT COUNT(*)::bigint FROM import_jobs WHERE organization_id = $1::bigint
`

func (q *Queries) CountImportJobsForOrganization(ctx context.Context, organizationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countImportJobsForOrganization, organizationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createImportJob = `-- name: CreateImportJob :one
INSERT INTO import_jobs (resource, actor_id, format, locale, status, file_key, organization_id)
VALUES ($1, $2, $3, $4, 'uploaded', $5, $6)
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id
`

type CreateImportJobParams struct {
	Resource       string      `json:"resource"`
	ActorID        int64       `json:"actor_id"`
	Format         string      `json:"format"`
	Locale         string      `json:"locale"`
	FileKey        pgtype.Text `json:"file_key"`
	OrganizationID pgtype.Int8 `json:"organization_id"`
}

func (q *Queries) CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, createImportJob,
		arg.Resource,
		arg.ActorID,
		arg.Format,
		arg.Locale,
		arg.FileKey,
		arg.OrganizationID,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getImportJobByID = `-- name: GetImportJobByID :one
SELECT id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id FROM import_jobs WHERE id = $1
`

func (q *Queries) GetImportJobByID(ctx context.Context, id int64) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJobByID, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getImportJobByUUID = `-- name: GetImportJobByUUID :one
SELECT id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id FROM import_jobs WHERE uuid = $1
`

func (q *Queries) GetImportJobByUUID(ctx context.Context, argUuid uuid.UUID) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJobByUUID, argUuid)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const insertImportChange = `-- name: InsertImportChange :one
INSERT INTO import_changes (job_id, entity_type, entity_uuid, op, previous_json)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, uuid, job_id, entity_type, entity_uuid, op, previous_json, created_at
`

type InsertImportChangeParams struct {
	JobID        int64     `json:"job_id"`
	EntityType   string    `json:"entity_type"`
	EntityUuid   uuid.UUID `json:"entity_uuid"`
	Op           string    `json:"op"`
	PreviousJson []byte    `json:"previous_json"`
}

func (q *Queries) InsertImportChange(ctx context.Context, arg InsertImportChangeParams) (ImportChange, error) {
	row := q.db.QueryRow(ctx, insertImportChange,
		arg.JobID,
		arg.EntityType,
		arg.EntityUuid,
		arg.Op,
		arg.PreviousJson,
	)
	var i ImportChange
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.JobID,
		&i.EntityType,
		&i.EntityUuid,
		&i.Op,
		&i.PreviousJson,
		&i.CreatedAt,
	)
	return i, err
}

const listAllImportJobs = `-- name: ListAllImportJobs :many
SELECT id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id FROM import_jobs
WHERE organization_id IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListAllImportJobsParams struct {
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListAllImportJobs(ctx context.Context, arg ListAllImportJobsParams) ([]ImportJob, error) {
	rows, err := q.db.Query(ctx, listAllImportJobs, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportJob{}
	for rows.Next() {
		var i ImportJob
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Resource,
			&i.ActorID,
			&i.Format,
			&i.Locale,
			&i.Status,
			&i.FileKey,
			&i.MappingJson,
			&i.DefaultsJson,
			&i.PreviewJson,
			&i.Error,
			&i.RollbackUntil,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportChangesForJob = `-- name: ListImportChangesForJob :many
SELECT id, uuid, job_id, entity_type, entity_uuid, op, previous_json, created_at FROM import_changes
WHERE job_id = $1
ORDER BY id ASC
`

func (q *Queries) ListImportChangesForJob(ctx context.Context, jobID int64) ([]ImportChange, error) {
	rows, err := q.db.Query(ctx, listImportChangesForJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportChange{}
	for rows.Next() {
		var i ImportChange
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.JobID,
			&i.EntityType,
			&i.EntityUuid,
			&i.Op,
			&i.PreviousJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportJobsForActor = `-- name: ListImportJobsForActor :many
SELECT id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id FROM import_jobs
WHERE actor_id = $1 AND organization_id IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListImportJobsForActorParams struct {
	ActorID     int64 `json:"actor_id"`
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListImportJobsForActor(ctx context.Context, arg ListImportJobsForActorParams) ([]ImportJob, error) {
	rows, err := q.db.Query(ctx, listImportJobsForActor, arg.ActorID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportJob{}
	for rows.Next() {
		var i ImportJob
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Resource,
			&i.ActorID,
			&i.Format,
			&i.Locale,
			&i.Status,
			&i.FileKey,
			&i.MappingJson,
			&i.DefaultsJson,
			&i.PreviewJson,
			&i.Error,
			&i.RollbackUntil,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportJobsForOrganization = `-- name: ListImportJobsForOrganization :many
SELECT id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id FROM import_jobs
WHERE organization_id = $1::bigint
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListImportJobsForOrganizationParams struct {
	OrganizationID int64 `json:"organization_id"`
	OffsetCount    int32 `json:"offset_count"`
	LimitCount     int32 `json:"limit_count"`
}

func (q *Queries) ListImportJobsForOrganization(ctx context.Context, arg ListImportJobsForOrganizationParams) ([]ImportJob, error) {
	rows, err := q.db.Query(ctx, listImportJobsForOrganization, arg.OrganizationID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportJob{}
	for rows.Next() {
		var i ImportJob
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Resource,
			&i.ActorID,
			&i.Format,
			&i.Locale,
			&i.Status,
			&i.FileKey,
			&i.MappingJson,
			&i.DefaultsJson,
			&i.PreviewJson,
			&i.Error,
			&i.RollbackUntil,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markImportJobApplied = `-- name: MarkImportJobApplied :one
UPDATE import_jobs
SET status = 'applied',
    applied_at = NOW(),
    rollback_until = NOW() + INTERVAL '24 hours',
    preview_json = $2
WHERE id = $1
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id
`

type MarkImportJobAppliedParams struct {
	ID          int64  `json:"id"`
	PreviewJson []byte `json:"preview_json"`
}

func (q *Queries) MarkImportJobApplied(ctx context.Context, arg MarkImportJobAppliedParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, markImportJobApplied, arg.ID, arg.PreviewJson)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const markImportJobApplying = `-- name: MarkImportJobApplying :one
UPDATE import_jobs
SET status = 'applying'
WHERE id = $1 AND status = 'queued'
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id
`

func (q *Queries) MarkImportJobApplying(ctx context.Context, id int64) (ImportJob, error) {
	row := q.db.QueryRow(ctx, markImportJobApplying, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const markImportJobFailed = `-- name: MarkImportJobFailed :one
UPDATE import_jobs
SET status = 'failed',
    error = $2
WHERE id = $1
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id
`

type MarkImportJobFailedParams struct {
	ID    int64       `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) MarkImportJobFailed(ctx context.Context, arg MarkImportJobFailedParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, markImportJobFailed, arg.ID, arg.Error)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const markImportJobRolledBack = `-- name: MarkImportJobRolledBack :one
UPDATE import_jobs
SET status = 'rolled_back'
WHERE id = $1 AND status = 'applied'
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id
`

func (q *Queries) MarkImportJobRolledBack(ctx context.Context, id int64) (ImportJob, error) {
	row := q.db.QueryRow(ctx, markImportJobRolledBack, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const queueImportJob = `-- name: QueueImportJob :one
UPDATE import_jobs
SET status = 'queued'
WHERE uuid = $1 AND status = 'previewed'
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id
`

func (q *Queries) QueueImportJob(ctx context.Context, argUuid uuid.UUID) (ImportJob, error) {
	row := q.db.QueryRow(ctx, queueImportJob, argUuid)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const updateImportJobFileKey = `-- name: UpdateImportJobFileKey :one
UPDATE import_jobs
SET file_key = $2
WHERE uuid = $1
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id
`

type UpdateImportJobFileKeyParams struct {
	Uuid    uuid.UUID   `json:"uuid"`
	FileKey pgtype.Text `json:"file_key"`
}

func (q *Queries) UpdateImportJobFileKey(ctx context.Context, arg UpdateImportJobFileKeyParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, updateImportJobFileKey, arg.Uuid, arg.FileKey)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const updateImportJobMapping = `-- name: UpdateImportJobMapping :one
UPDATE import_jobs
SET mapping_json = $2,
    defaults_json = $3,
    status = 'mapped'
WHERE uuid = $1 AND status IN ('uploaded', 'mapped', 'previewed')
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id
`

type UpdateImportJobMappingParams struct {
	Uuid         uuid.UUID `json:"uuid"`
	MappingJson  []byte    `json:"mapping_json"`
	DefaultsJson []byte    `json:"defaults_json"`
}

func (q *Queries) UpdateImportJobMapping(ctx context.Context, arg UpdateImportJobMappingParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, updateImportJobMapping, arg.Uuid, arg.MappingJson, arg.DefaultsJson)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const updateImportJobPreview = `-- name: UpdateImportJobPreview :one
UPDATE import_jobs
SET preview_json = $2,
    status = 'previewed'
WHERE uuid = $1 AND status IN ('mapped', 'previewed')
RETURNING id, uuid, resource, actor_id, format, locale, status, file_key, mapping_json, defaults_json, preview_json, error, rollback_until, applied_at, created_at, updated_at, organization_id
`

type UpdateImportJobPreviewParams struct {
	Uuid        uuid.UUID `json:"uuid"`
	PreviewJson []byte    `json:"preview_json"`
}

func (q *Queries) UpdateImportJobPreview(ctx context.Context, arg UpdateImportJobPreviewParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, updateImportJobPreview, arg.Uuid, arg.PreviewJson)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Resource,
		&i.ActorID,
		&i.Format,
		&i.Locale,
		&i.Status,
		&i.FileKey,
		&i.MappingJson,
		&i.DefaultsJson,
		&i.PreviewJson,
		&i.Error,
		&i.RollbackUntil,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}
