// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countServiceJobs = `-- name: CountServiceJobs :one
SELECT COUNT(*)::bigint
FROM service_jobs j
WHERE j.organization_id = $1
  AND ($2::text IS NULL OR j.status = $2)
  AND ($3::timestamptz IS NULL OR j.started_at >= $3)
  AND ($4::timestamptz IS NULL OR j.started_at < $4)
  AND (
    $5::text IS NULL
    OR j.plate ILIKE '%' || $5 || '%'
    OR j.customer_name ILIKE '%' || $5 || '%'
    OR j.vehicle_label ILIKE '%' || $5 || '%'
  )
`

type CountServiceJobsParams struct {
	OrganizationID int64              `json:"organization_id"`
	Status         pgtype.Text        `json:"status"`
	DateFrom       pgtype.Timestamptz `json:"date_from"`
	DateTo         pgtype.Timestamptz `json:"date_to"`
	Q              pgtype.Text        `json:"q"`
}

func (q *Queries) CountServiceJobs(ctx context.Context, arg CountServiceJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countServiceJobs,
		arg.OrganizationID,
		arg.Status,
		arg.DateFrom,
		arg.DateTo,
		arg.Q,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countServiceJobsByCustomer = `-- name: CountServiceJobsByCustomer :one
SELECT COUNT(*)::bigint
FROM service_jobs
WHERE organization_id = $1 AND customer_id = $2
`

type CountServiceJobsByCustomerParams struct {
	OrganizationID int64 `json:"organization_id"`
	CustomerID     int64 `json:"customer_id"`
}

func (q *Queries) CountServiceJobsByCustomer(ctx context.Context, arg CountServiceJobsByCustomerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countServiceJobsByCustomer, arg.OrganizationID, arg.CustomerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createServiceJob = `-- name: CreateServiceJob :one

INSERT INTO service_jobs (
    organization_id, customer_id, vehicle_id,
    customer_name, customer_phone, plate, vehicle_label,
    status, currency, notes, started_at, total_amount, created_by, assignee_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, uuid, organization_id, customer_id, vehicle_id, customer_name, customer_phone, plate, vehicle_label, status, currency, notes, started_at, completed_at, paid_at, assignee_user_id, total_amount, created_by, created_at, updated_at, payment_status
`

type CreateServiceJobParams struct {
	OrganizationID int64              `json:"organization_id"`
	CustomerID     int64              `json:"customer_id"`
	VehicleID      int64              `json:"vehicle_id"`
	CustomerName   string             `json:"customer_name"`
	CustomerPhone  string             `json:"customer_phone"`
	Plate          string             `json:"plate"`
	VehicleLabel   string             `json:"vehicle_label"`
	Status         string             `json:"status"`
	Currency       string             `json:"currency"`
	Notes          string             `json:"notes"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	TotalAmount    pgtype.Numeric     `json:"total_amount"`
	CreatedBy      int64              `json:"created_by"`
	AssigneeUserID pgtype.Int8        `json:"assignee_user_id"`
}

// Tenant service jobs (operations / iş emri).
func (q *Queries) CreateServiceJob(ctx context.Context, arg CreateServiceJobParams) (ServiceJob, error) {
	row := q.db.QueryRow(ctx, createServiceJob,
		arg.OrganizationID,
		arg.CustomerID,
		arg.VehicleID,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.Plate,
		arg.VehicleLabel,
		arg.Status,
		arg.Currency,
		arg.Notes,
		arg.StartedAt,
		arg.TotalAmount,
		arg.CreatedBy,
		arg.AssigneeUserID,
	)
	var i ServiceJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.VehicleID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.Plate,
		&i.VehicleLabel,
		&i.Status,
		&i.Currency,
		&i.Notes,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PaidAt,
		&i.AssigneeUserID,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentStatus,
	)
	return i, err
}

const createServiceJobLine = `-- name: CreateServiceJobLine :one
INSERT INTO service_job_lines (
    organization_id, job_id, line_type, service_id, name,
    unit_price, qty, vat_rate, line_total, currency, sort_order
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, uuid, organization_id, job_id, line_type, service_id, product_id, name, unit_price, qty, vat_rate, line_total, currency, sort_order, created_at, updated_at
`

type CreateServiceJobLineParams struct {
	OrganizationID int64          `json:"organization_id"`
	JobID          int64          `json:"job_id"`
	LineType       string         `json:"line_type"`
	ServiceID      pgtype.Int8    `json:"service_id"`
	Name           string         `json:"name"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	Qty            pgtype.Numeric `json:"qty"`
	VatRate        pgtype.Numeric `json:"vat_rate"`
	LineTotal      pgtype.Numeric `json:"line_total"`
	Currency       string         `json:"currency"`
	SortOrder      int32          `json:"sort_order"`
}

func (q *Queries) CreateServiceJobLine(ctx context.Context, arg CreateServiceJobLineParams) (ServiceJobLine, error) {
	row := q.db.QueryRow(ctx, createServiceJobLine,
		arg.OrganizationID,
		arg.JobID,
		arg.LineType,
		arg.ServiceID,
		arg.Name,
		arg.UnitPrice,
		arg.Qty,
		arg.VatRate,
		arg.LineTotal,
		arg.Currency,
		arg.SortOrder,
	)
	var i ServiceJobLine
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.JobID,
		&i.LineType,
		&i.ServiceID,
		&i.ProductID,
		&i.Name,
		&i.UnitPrice,
		&i.Qty,
		&i.VatRate,
		&i.LineTotal,
		&i.Currency,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServiceJobPayment = `-- name: CreateServiceJobPayment :one
INSERT INTO service_job_payments (
    organization_id, job_id, method, amount, currency, status,
    finance_account_id, finance_transaction_id, cari_entry_id, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, uuid, organization_id, job_id, method, amount, currency, status, finance_account_id, finance_transaction_id, cari_entry_id, created_by, voided_at, voided_by, created_at, updated_at
`

type CreateServiceJobPaymentParams struct {
	OrganizationID       int64          `json:"organization_id"`
	JobID                int64          `json:"job_id"`
	Method               string         `json:"method"`
	Amount               pgtype.Numeric `json:"amount"`
	Currency             string         `json:"currency"`
	Status               string         `json:"status"`
	FinanceAccountID     pgtype.Int8    `json:"finance_account_id"`
	FinanceTransactionID pgtype.Int8    `json:"finance_transaction_id"`
	CariEntryID          pgtype.Int8    `json:"cari_entry_id"`
	CreatedBy            int64          `json:"created_by"`
}

func (q *Queries) CreateServiceJobPayment(ctx context.Context, arg CreateServiceJobPaymentParams) (ServiceJobPayment, error) {
	row := q.db.QueryRow(ctx, createServiceJobPayment,
		arg.OrganizationID,
		arg.JobID,
		arg.Method,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.FinanceAccountID,
		arg.FinanceTransactionID,
		arg.CariEntryID,
		arg.CreatedBy,
	)
	var i ServiceJobPayment
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.JobID,
		&i.Method,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.FinanceAccountID,
		&i.FinanceTransactionID,
		&i.CariEntryID,
		&i.CreatedBy,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerVehicleDetailByUUID = `-- name: GetCustomerVehicleDetailByUUID :one
SELECT
    v.id, v.uuid, v.organization_id, v.customer_id, v.plate, v.model_id, v.year, v.created_at, v.updated_at, v.deleted_at,
    c.uuid AS customer_uuid,
    c.name AS customer_name,
    c.phone AS customer_phone,
    b.name AS brand_name,
    m.name AS model_name
FROM customer_vehicles v
JOIN customers c ON c.id = v.customer_id AND c.deleted_at IS NULL
JOIN vehicle_models m ON m.id = v.model_id
JOIN vehicle_brands b ON b.id = m.brand_id
WHERE v.uuid = $1 AND v.organization_id = $2 AND v.deleted_at IS NULL
`

type GetCustomerVehicleDetailByUUIDParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

type GetCustomerVehicleDetailByUUIDRow struct {
	ID             int64              `json:"id"`
	Uuid           uuid.UUID          `json:"uuid"`
	OrganizationID int64              `json:"organization_id"`
	CustomerID     int64              `json:"customer_id"`
	Plate          string             `json:"plate"`
	ModelID        int64              `json:"model_id"`
	Year           int16              `json:"year"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CustomerUuid   uuid.UUID          `json:"customer_uuid"`
	CustomerName   string             `json:"customer_name"`
	CustomerPhone  string             `json:"customer_phone"`
	BrandName      string             `json:"brand_name"`
	ModelName      string             `json:"model_name"`
}

func (q *Queries) GetCustomerVehicleDetailByUUID(ctx context.Context, arg GetCustomerVehicleDetailByUUIDParams) (GetCustomerVehicleDetailByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerVehicleDetailByUUID, arg.Uuid, arg.OrganizationID)
	var i GetCustomerVehicleDetailByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.Plate,
		&i.ModelID,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CustomerUuid,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.BrandName,
		&i.ModelName,
	)
	return i, err
}

const getServiceJobByID = `-- name: GetServiceJobByID :one
SELECT id, uuid, organization_id, customer_id, vehicle_id, customer_name, customer_phone, plate, vehicle_label, status, currency, notes, started_at, completed_at, paid_at, assignee_user_id, total_amount, created_by, created_at, updated_at, payment_status FROM service_jobs
WHERE id = $1 AND organization_id = $2
`

type GetServiceJobByIDParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) GetServiceJobByID(ctx context.Context, arg GetServiceJobByIDParams) (ServiceJob, error) {
	row := q.db.QueryRow(ctx, getServiceJobByID, arg.ID, arg.OrganizationID)
	var i ServiceJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.VehicleID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.Plate,
		&i.VehicleLabel,
		&i.Status,
		&i.Currency,
		&i.Notes,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PaidAt,
		&i.AssigneeUserID,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentStatus,
	)
	return i, err
}

const getServiceJobByUUID = `-- name: GetServiceJobByUUID :one
SELECT j.id, j.uuid, j.organization_id, j.customer_id, j.vehicle_id, j.customer_name, j.customer_phone, j.plate, j.vehicle_label, j.status, j.currency, j.notes, j.started_at, j.completed_at, j.paid_at, j.assignee_user_id, j.total_amount, j.created_by, j.created_at, j.updated_at, j.payment_status,
       c.uuid AS customer_uuid,
       v.uuid AS vehicle_uuid,
       au.uuid AS assignee_uuid,
       CASE WHEN au.id IS NULL THEN '' ELSE trim(both FROM concat(au.name, ' ', au.surname)) END::text AS assignee_name
FROM service_jobs j
JOIN customers c ON c.id = j.customer_id
JOIN customer_vehicles v ON v.id = j.vehicle_id
LEFT JOIN users au ON au.id = j.assignee_user_id
WHERE j.uuid = $1 AND j.organization_id = $2
`

type GetServiceJobByUUIDParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

type GetServiceJobByUUIDRow struct {
	ID             int64              `json:"id"`
	Uuid           uuid.UUID          `json:"uuid"`
	OrganizationID int64              `json:"organization_id"`
	CustomerID     int64              `json:"customer_id"`
	VehicleID      int64              `json:"vehicle_id"`
	CustomerName   string             `json:"customer_name"`
	CustomerPhone  string             `json:"customer_phone"`
	Plate          string             `json:"plate"`
	VehicleLabel   string             `json:"vehicle_label"`
	Status         string             `json:"status"`
	Currency       string             `json:"currency"`
	Notes          string             `json:"notes"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	AssigneeUserID pgtype.Int8        `json:"assignee_user_id"`
	TotalAmount    pgtype.Numeric     `json:"total_amount"`
	CreatedBy      int64              `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PaymentStatus  string             `json:"payment_status"`
	CustomerUuid   uuid.UUID          `json:"customer_uuid"`
	VehicleUuid    uuid.UUID          `json:"vehicle_uuid"`
	AssigneeUuid   pgtype.UUID        `json:"assignee_uuid"`
	AssigneeName   string             `json:"assignee_name"`
}

func (q *Queries) GetServiceJobByUUID(ctx context.Context, arg GetServiceJobByUUIDParams) (GetServiceJobByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getServiceJobByUUID, arg.Uuid, arg.OrganizationID)
	var i GetServiceJobByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.VehicleID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.Plate,
		&i.VehicleLabel,
		&i.Status,
		&i.Currency,
		&i.Notes,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PaidAt,
		&i.AssigneeUserID,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentStatus,
		&i.CustomerUuid,
		&i.VehicleUuid,
		&i.AssigneeUuid,
		&i.AssigneeName,
	)
	return i, err
}

const getServiceJobForSearch = `-- name: GetServiceJobForSearch :one
SELECT j.uuid, j.plate, j.vehicle_label, j.customer_name, j.status, j.total_amount,
       j.currency, j.organization_id,
       o.uuid AS organization_uuid, o.slug AS organization_slug
FROM service_jobs j
JOIN organizations o ON o.id = j.organization_id
WHERE j.uuid = $1 AND o.uuid = $2
`

type GetServiceJobForSearchParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	Uuid_2 uuid.UUID `json:"uuid_2"`
}

type GetServiceJobForSearchRow struct {
	Uuid             uuid.UUID      `json:"uuid"`
	Plate            string         `json:"plate"`
	VehicleLabel     string         `json:"vehicle_label"`
	CustomerName     string         `json:"customer_name"`
	Status           string         `json:"status"`
	TotalAmount      pgtype.Numeric `json:"total_amount"`
	Currency         string         `json:"currency"`
	OrganizationID   int64          `json:"organization_id"`
	OrganizationUuid uuid.UUID      `json:"organization_uuid"`
	OrganizationSlug string         `json:"organization_slug"`
}

func (q *Queries) GetServiceJobForSearch(ctx context.Context, arg GetServiceJobForSearchParams) (GetServiceJobForSearchRow, error) {
	row := q.db.QueryRow(ctx, getServiceJobForSearch, arg.Uuid, arg.Uuid_2)
	var i GetServiceJobForSearchRow
	err := row.Scan(
		&i.Uuid,
		&i.Plate,
		&i.VehicleLabel,
		&i.CustomerName,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.OrganizationID,
		&i.OrganizationUuid,
		&i.OrganizationSlug,
	)
	return i, err
}

const linkServiceJobPaymentCari = `-- name: LinkServiceJobPaymentCari :one
UPDATE service_job_payments
SET cari_entry_id = $3
WHERE id = $1 AND organization_id = $2
RETURNING id, uuid, organization_id, job_id, method, amount, currency, status, finance_account_id, finance_transaction_id, cari_entry_id, created_by, voided_at, voided_by, created_at, updated_at
`

type LinkServiceJobPaymentCariParams struct {
	ID             int64       `json:"id"`
	OrganizationID int64       `json:"organization_id"`
	CariEntryID    pgtype.Int8 `json:"cari_entry_id"`
}

func (q *Queries) LinkServiceJobPaymentCari(ctx context.Context, arg LinkServiceJobPaymentCariParams) (ServiceJobPayment, error) {
	row := q.db.QueryRow(ctx, linkServiceJobPaymentCari, arg.ID, arg.OrganizationID, arg.CariEntryID)
	var i ServiceJobPayment
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.JobID,
		&i.Method,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.FinanceAccountID,
		&i.FinanceTransactionID,
		&i.CariEntryID,
		&i.CreatedBy,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkServiceJobPaymentFinance = `-- name: LinkServiceJobPaymentFinance :one
UPDATE service_job_payments
SET finance_transaction_id = $3, finance_account_id = $4
WHERE id = $1 AND organization_id = $2
RETURNING id, uuid, organization_id, job_id, method, amount, currency, status, finance_account_id, finance_transaction_id, cari_entry_id, created_by, voided_at, voided_by, created_at, updated_at
`

type LinkServiceJobPaymentFinanceParams struct {
	ID                   int64       `json:"id"`
	OrganizationID       int64       `json:"organization_id"`
	FinanceTransactionID pgtype.Int8 `json:"finance_transaction_id"`
	FinanceAccountID     pgtype.Int8 `json:"finance_account_id"`
}

func (q *Queries) LinkServiceJobPaymentFinance(ctx context.Context, arg LinkServiceJobPaymentFinanceParams) (ServiceJobPayment, error) {
	row := q.db.QueryRow(ctx, linkServiceJobPaymentFinance,
		arg.ID,
		arg.OrganizationID,
		arg.FinanceTransactionID,
		arg.FinanceAccountID,
	)
	var i ServiceJobPayment
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.JobID,
		&i.Method,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.FinanceAccountID,
		&i.FinanceTransactionID,
		&i.CariEntryID,
		&i.CreatedBy,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServiceJobLines = `-- name: ListServiceJobLines :many
SELECT l.id, l.uuid, l.organization_id, l.job_id, l.line_type, l.service_id, l.product_id, l.name, l.unit_price, l.qty, l.vat_rate, l.line_total, l.currency, l.sort_order, l.created_at, l.updated_at,
       s.uuid AS service_uuid
FROM service_job_lines l
LEFT JOIN services s ON s.id = l.service_id
WHERE l.job_id = $1 AND l.organization_id = $2
ORDER BY l.sort_order ASC, l.id ASC
`

type ListServiceJobLinesParams struct {
	JobID          int64 `json:"job_id"`
	OrganizationID int64 `json:"organization_id"`
}

type ListServiceJobLinesRow struct {
	ID             int64              `json:"id"`
	Uuid           uuid.UUID          `json:"uuid"`
	OrganizationID int64              `json:"organization_id"`
	JobID          int64              `json:"job_id"`
	LineType       string             `json:"line_type"`
	ServiceID      pgtype.Int8        `json:"service_id"`
	ProductID      pgtype.Int8        `json:"product_id"`
	Name           string             `json:"name"`
	UnitPrice      pgtype.Numeric     `json:"unit_price"`
	Qty            pgtype.Numeric     `json:"qty"`
	VatRate        pgtype.Numeric     `json:"vat_rate"`
	LineTotal      pgtype.Numeric     `json:"line_total"`
	Currency       string             `json:"currency"`
	SortOrder      int32              `json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ServiceUuid    pgtype.UUID        `json:"service_uuid"`
}

func (q *Queries) ListServiceJobLines(ctx context.Context, arg ListServiceJobLinesParams) ([]ListServiceJobLinesRow, error) {
	rows, err := q.db.Query(ctx, listServiceJobLines, arg.JobID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceJobLinesRow{}
	for rows.Next() {
		var i ListServiceJobLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.JobID,
			&i.LineType,
			&i.ServiceID,
			&i.ProductID,
			&i.Name,
			&i.UnitPrice,
			&i.Qty,
			&i.VatRate,
			&i.LineTotal,
			&i.Currency,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceJobPayments = `-- name: ListServiceJobPayments :many
SELECT p.id, p.uuid, p.organization_id, p.job_id, p.method, p.amount, p.currency, p.status, p.finance_account_id, p.finance_transaction_id, p.cari_entry_id, p.created_by, p.voided_at, p.voided_by, p.created_at, p.updated_at,
       fa.uuid AS finance_account_uuid,
       fa.name AS finance_account_name,
       ft.uuid AS finance_transaction_uuid,
       ce.uuid AS cari_entry_uuid
FROM service_job_payments p
LEFT JOIN finance_accounts fa ON fa.id = p.finance_account_id
LEFT JOIN finance_transactions ft ON ft.id = p.finance_transaction_id
LEFT JOIN cari_entries ce ON ce.id = p.cari_entry_id
WHERE p.job_id = $1 AND p.organization_id = $2
ORDER BY p.created_at ASC
`

type ListServiceJobPaymentsParams struct {
	JobID          int64 `json:"job_id"`
	OrganizationID int64 `json:"organization_id"`
}

type ListServiceJobPaymentsRow struct {
	ID                     int64              `json:"id"`
	Uuid                   uuid.UUID          `json:"uuid"`
	OrganizationID         int64              `json:"organization_id"`
	JobID                  int64              `json:"job_id"`
	Method                 string             `json:"method"`
	Amount                 pgtype.Numeric     `json:"amount"`
	Currency               string             `json:"currency"`
	Status                 string             `json:"status"`
	FinanceAccountID       pgtype.Int8        `json:"finance_account_id"`
	FinanceTransactionID   pgtype.Int8        `json:"finance_transaction_id"`
	CariEntryID            pgtype.Int8        `json:"cari_entry_id"`
	CreatedBy              int64              `json:"created_by"`
	VoidedAt               pgtype.Timestamptz `json:"voided_at"`
	VoidedBy               pgtype.Int8        `json:"voided_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	FinanceAccountUuid     pgtype.UUID        `json:"finance_account_uuid"`
	FinanceAccountName     pgtype.Text        `json:"finance_account_name"`
	FinanceTransactionUuid pgtype.UUID        `json:"finance_transaction_uuid"`
	CariEntryUuid          pgtype.UUID        `json:"cari_entry_uuid"`
}

func (q *Queries) ListServiceJobPayments(ctx context.Context, arg ListServiceJobPaymentsParams) ([]ListServiceJobPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listServiceJobPayments, arg.JobID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceJobPaymentsRow{}
	for rows.Next() {
		var i ListServiceJobPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.JobID,
			&i.Method,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.FinanceAccountID,
			&i.FinanceTransactionID,
			&i.CariEntryID,
			&i.CreatedBy,
			&i.VoidedAt,
			&i.VoidedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinanceAccountUuid,
			&i.FinanceAccountName,
			&i.FinanceTransactionUuid,
			&i.CariEntryUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceJobs = `-- name: ListServiceJobs :many
SELECT j.id, j.uuid, j.organization_id, j.customer_id, j.vehicle_id, j.customer_name, j.customer_phone, j.plate, j.vehicle_label, j.status, j.currency, j.notes, j.started_at, j.completed_at, j.paid_at, j.assignee_user_id, j.total_amount, j.created_by, j.created_at, j.updated_at, j.payment_status,
       c.uuid AS customer_uuid,
       v.uuid AS vehicle_uuid,
       au.uuid AS assignee_uuid,
       CASE WHEN au.id IS NULL THEN '' ELSE trim(both FROM concat(au.name, ' ', au.surname)) END::text AS assignee_name
FROM service_jobs j
JOIN customers c ON c.id = j.customer_id
JOIN customer_vehicles v ON v.id = j.vehicle_id
LEFT JOIN users au ON au.id = j.assignee_user_id
WHERE j.organization_id = $1
  AND ($2::text IS NULL OR j.status = $2)
  AND ($3::timestamptz IS NULL OR j.started_at >= $3)
  AND ($4::timestamptz IS NULL OR j.started_at < $4)
  AND (
    $5::text IS NULL
    OR j.plate ILIKE '%' || $5 || '%'
    OR j.customer_name ILIKE '%' || $5 || '%'
    OR j.vehicle_label ILIKE '%' || $5 || '%'
  )
ORDER BY
    CASE WHEN $6::text = 'started_at' THEN j.started_at END ASC,
    CASE WHEN $6::text = '-started_at' THEN j.started_at END DESC,
    CASE WHEN $6::text = 'total_amount' THEN j.total_amount END ASC,
    CASE WHEN $6::text = '-total_amount' THEN j.total_amount END DESC,
    CASE WHEN $6::text = 'plate' THEN j.plate END ASC,
    CASE WHEN $6::text = '-plate' THEN j.plate END DESC,
    j.started_at DESC
LIMIT $8 OFFSET $7
`

type ListServiceJobsParams struct {
	OrganizationID int64              `json:"organization_id"`
	Status         pgtype.Text        `json:"status"`
	DateFrom       pgtype.Timestamptz `json:"date_from"`
	DateTo         pgtype.Timestamptz `json:"date_to"`
	Q              pgtype.Text        `json:"q"`
	Sort           string             `json:"sort"`
	OffsetCount    int32              `json:"offset_count"`
	LimitCount     int32              `json:"limit_count"`
}

type ListServiceJobsRow struct {
	ID             int64              `json:"id"`
	Uuid           uuid.UUID          `json:"uuid"`
	OrganizationID int64              `json:"organization_id"`
	CustomerID     int64              `json:"customer_id"`
	VehicleID      int64              `json:"vehicle_id"`
	CustomerName   string             `json:"customer_name"`
	CustomerPhone  string             `json:"customer_phone"`
	Plate          string             `json:"plate"`
	VehicleLabel   string             `json:"vehicle_label"`
	Status         string             `json:"status"`
	Currency       string             `json:"currency"`
	Notes          string             `json:"notes"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	AssigneeUserID pgtype.Int8        `json:"assignee_user_id"`
	TotalAmount    pgtype.Numeric     `json:"total_amount"`
	CreatedBy      int64              `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PaymentStatus  string             `json:"payment_status"`
	CustomerUuid   uuid.UUID          `json:"customer_uuid"`
	VehicleUuid    uuid.UUID          `json:"vehicle_uuid"`
	AssigneeUuid   pgtype.UUID        `json:"assignee_uuid"`
	AssigneeName   string             `json:"assignee_name"`
}

func (q *Queries) ListServiceJobs(ctx context.Context, arg ListServiceJobsParams) ([]ListServiceJobsRow, error) {
	rows, err := q.db.Query(ctx, listServiceJobs,
		arg.OrganizationID,
		arg.Status,
		arg.DateFrom,
		arg.DateTo,
		arg.Q,
		arg.Sort,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceJobsRow{}
	for rows.Next() {
		var i ListServiceJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.CustomerID,
			&i.VehicleID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.Plate,
			&i.VehicleLabel,
			&i.Status,
			&i.Currency,
			&i.Notes,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PaidAt,
			&i.AssigneeUserID,
			&i.TotalAmount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaymentStatus,
			&i.CustomerUuid,
			&i.VehicleUuid,
			&i.AssigneeUuid,
			&i.AssigneeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceJobsByCustomer = `-- name: ListServiceJobsByCustomer :many
SELECT j.id, j.uuid, j.organization_id, j.customer_id, j.vehicle_id, j.customer_name, j.customer_phone, j.plate, j.vehicle_label, j.status, j.currency, j.notes, j.started_at, j.completed_at, j.paid_at, j.assignee_user_id, j.total_amount, j.created_by, j.created_at, j.updated_at, j.payment_status,
       c.uuid AS customer_uuid,
       v.uuid AS vehicle_uuid
FROM service_jobs j
JOIN customers c ON c.id = j.customer_id
JOIN customer_vehicles v ON v.id = j.vehicle_id
WHERE j.organization_id = $1 AND j.customer_id = $2
ORDER BY j.started_at DESC
LIMIT $3 OFFSET $4
`

type ListServiceJobsByCustomerParams struct {
	OrganizationID int64 `json:"organization_id"`
	CustomerID     int64 `json:"customer_id"`
	Limit          int32 `json:"limit"`
	Offset         int32 `json:"offset"`
}

type ListServiceJobsByCustomerRow struct {
	ID             int64              `json:"id"`
	Uuid           uuid.UUID          `json:"uuid"`
	OrganizationID int64              `json:"organization_id"`
	CustomerID     int64              `json:"customer_id"`
	VehicleID      int64              `json:"vehicle_id"`
	CustomerName   string             `json:"customer_name"`
	CustomerPhone  string             `json:"customer_phone"`
	Plate          string             `json:"plate"`
	VehicleLabel   string             `json:"vehicle_label"`
	Status         string             `json:"status"`
	Currency       string             `json:"currency"`
	Notes          string             `json:"notes"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	AssigneeUserID pgtype.Int8        `json:"assignee_user_id"`
	TotalAmount    pgtype.Numeric     `json:"total_amount"`
	CreatedBy      int64              `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	PaymentStatus  string             `json:"payment_status"`
	CustomerUuid   uuid.UUID          `json:"customer_uuid"`
	VehicleUuid    uuid.UUID          `json:"vehicle_uuid"`
}

func (q *Queries) ListServiceJobsByCustomer(ctx context.Context, arg ListServiceJobsByCustomerParams) ([]ListServiceJobsByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listServiceJobsByCustomer,
		arg.OrganizationID,
		arg.CustomerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceJobsByCustomerRow{}
	for rows.Next() {
		var i ListServiceJobsByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.CustomerID,
			&i.VehicleID,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.Plate,
			&i.VehicleLabel,
			&i.Status,
			&i.Currency,
			&i.Notes,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PaidAt,
			&i.AssigneeUserID,
			&i.TotalAmount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaymentStatus,
			&i.CustomerUuid,
			&i.VehicleUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceJobsForExport = `-- name: ListServiceJobsForExport :many
SELECT j.uuid, j.status, j.plate, j.vehicle_label, j.customer_name, j.customer_phone,
       j.total_amount, j.currency, j.started_at, j.paid_at, j.notes
FROM service_jobs j
WHERE j.organization_id = $1
  AND ($2::text IS NULL OR j.status = $2)
  AND ($3::timestamptz IS NULL OR j.started_at >= $3)
  AND ($4::timestamptz IS NULL OR j.started_at < $4)
  AND (
    $5::text IS NULL
    OR j.plate ILIKE '%' || $5 || '%'
    OR j.customer_name ILIKE '%' || $5 || '%'
  )
ORDER BY j.started_at DESC
`

type ListServiceJobsForExportParams struct {
	OrganizationID int64              `json:"organization_id"`
	Status         pgtype.Text        `json:"status"`
	DateFrom       pgtype.Timestamptz `json:"date_from"`
	DateTo         pgtype.Timestamptz `json:"date_to"`
	Q              pgtype.Text        `json:"q"`
}

type ListServiceJobsForExportRow struct {
	Uuid          uuid.UUID          `json:"uuid"`
	Status        string             `json:"status"`
	Plate         string             `json:"plate"`
	VehicleLabel  string             `json:"vehicle_label"`
	CustomerName  string             `json:"customer_name"`
	CustomerPhone string             `json:"customer_phone"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	Currency      string             `json:"currency"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	Notes         string             `json:"notes"`
}

func (q *Queries) ListServiceJobsForExport(ctx context.Context, arg ListServiceJobsForExportParams) ([]ListServiceJobsForExportRow, error) {
	rows, err := q.db.Query(ctx, listServiceJobsForExport,
		arg.OrganizationID,
		arg.Status,
		arg.DateFrom,
		arg.DateTo,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceJobsForExportRow{}
	for rows.Next() {
		var i ListServiceJobsForExportRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Status,
			&i.Plate,
			&i.VehicleLabel,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.TotalAmount,
			&i.Currency,
			&i.StartedAt,
			&i.PaidAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceJobsForSearch = `-- name: ListServiceJobsForSearch :many
SELECT j.uuid, j.plate, j.vehicle_label, j.customer_name, j.status, j.total_amount,
       j.currency, j.organization_id,
       o.uuid AS organization_uuid, o.slug AS organization_slug
FROM service_jobs j
JOIN organizations o ON o.id = j.organization_id
WHERE j.status NOT IN ('cancelled', 'voided')
`

type ListServiceJobsForSearchRow struct {
	Uuid             uuid.UUID      `json:"uuid"`
	Plate            string         `json:"plate"`
	VehicleLabel     string         `json:"vehicle_label"`
	CustomerName     string         `json:"customer_name"`
	Status           string         `json:"status"`
	TotalAmount      pgtype.Numeric `json:"total_amount"`
	Currency         string         `json:"currency"`
	OrganizationID   int64          `json:"organization_id"`
	OrganizationUuid uuid.UUID      `json:"organization_uuid"`
	OrganizationSlug string         `json:"organization_slug"`
}

func (q *Queries) ListServiceJobsForSearch(ctx context.Context) ([]ListServiceJobsForSearchRow, error) {
	rows, err := q.db.Query(ctx, listServiceJobsForSearch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceJobsForSearchRow{}
	for rows.Next() {
		var i ListServiceJobsForSearchRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Plate,
			&i.VehicleLabel,
			&i.CustomerName,
			&i.Status,
			&i.TotalAmount,
			&i.Currency,
			&i.OrganizationID,
			&i.OrganizationUuid,
			&i.OrganizationSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markServiceJobCancelled = `-- name: MarkServiceJobCancelled :one
UPDATE service_jobs
SET status = 'cancelled', completed_at = COALESCE(completed_at, NOW())
WHERE uuid = $1 AND organization_id = $2
  AND status IN ('in_progress', 'ready')
RETURNING id, uuid, organization_id, customer_id, vehicle_id, customer_name, customer_phone, plate, vehicle_label, status, currency, notes, started_at, completed_at, paid_at, assignee_user_id, total_amount, created_by, created_at, updated_at, payment_status
`

type MarkServiceJobCancelledParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) MarkServiceJobCancelled(ctx context.Context, arg MarkServiceJobCancelledParams) (ServiceJob, error) {
	row := q.db.QueryRow(ctx, markServiceJobCancelled, arg.Uuid, arg.OrganizationID)
	var i ServiceJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.VehicleID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.Plate,
		&i.VehicleLabel,
		&i.Status,
		&i.Currency,
		&i.Notes,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PaidAt,
		&i.AssigneeUserID,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentStatus,
	)
	return i, err
}

const markServiceJobDelivered = `-- name: MarkServiceJobDelivered :one
UPDATE service_jobs
SET status = 'delivered'
WHERE uuid = $1 AND organization_id = $2
  AND status IN ('ready', 'in_progress')
RETURNING id, uuid, organization_id, customer_id, vehicle_id, customer_name, customer_phone, plate, vehicle_label, status, currency, notes, started_at, completed_at, paid_at, assignee_user_id, total_amount, created_by, created_at, updated_at, payment_status
`

type MarkServiceJobDeliveredParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) MarkServiceJobDelivered(ctx context.Context, arg MarkServiceJobDeliveredParams) (ServiceJob, error) {
	row := q.db.QueryRow(ctx, markServiceJobDelivered, arg.Uuid, arg.OrganizationID)
	var i ServiceJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.VehicleID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.Plate,
		&i.VehicleLabel,
		&i.Status,
		&i.Currency,
		&i.Notes,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PaidAt,
		&i.AssigneeUserID,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentStatus,
	)
	return i, err
}

const markServiceJobDone = `-- name: MarkServiceJobDone :one
UPDATE service_jobs
SET status = 'ready', completed_at = COALESCE(completed_at, NOW())
WHERE uuid = $1 AND organization_id = $2
  AND status = 'in_progress'
RETURNING id, uuid, organization_id, customer_id, vehicle_id, customer_name, customer_phone, plate, vehicle_label, status, currency, notes, started_at, completed_at, paid_at, assignee_user_id, total_amount, created_by, created_at, updated_at, payment_status
`

type MarkServiceJobDoneParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) MarkServiceJobDone(ctx context.Context, arg MarkServiceJobDoneParams) (ServiceJob, error) {
	row := q.db.QueryRow(ctx, markServiceJobDone, arg.Uuid, arg.OrganizationID)
	var i ServiceJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.VehicleID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.Plate,
		&i.VehicleLabel,
		&i.Status,
		&i.Currency,
		&i.Notes,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PaidAt,
		&i.AssigneeUserID,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentStatus,
	)
	return i, err
}

const markServiceJobPaid = `-- name: MarkServiceJobPaid :one
UPDATE service_jobs
SET payment_status = 'paid',
    completed_at = COALESCE(completed_at, NOW()),
    paid_at = NOW()
WHERE uuid = $1 AND organization_id = $2
  AND payment_status = 'unpaid'
  AND status IN ('in_progress', 'ready', 'delivered')
RETURNING id, uuid, organization_id, customer_id, vehicle_id, customer_name, customer_phone, plate, vehicle_label, status, currency, notes, started_at, completed_at, paid_at, assignee_user_id, total_amount, created_by, created_at, updated_at, payment_status
`

type MarkServiceJobPaidParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) MarkServiceJobPaid(ctx context.Context, arg MarkServiceJobPaidParams) (ServiceJob, error) {
	row := q.db.QueryRow(ctx, markServiceJobPaid, arg.Uuid, arg.OrganizationID)
	var i ServiceJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.VehicleID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.Plate,
		&i.VehicleLabel,
		&i.Status,
		&i.Currency,
		&i.Notes,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PaidAt,
		&i.AssigneeUserID,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentStatus,
	)
	return i, err
}

const markServiceJobVoided = `-- name: MarkServiceJobVoided :one
UPDATE service_jobs
SET status = 'voided'
WHERE uuid = $1 AND organization_id = $2
  AND payment_status = 'paid'
RETURNING id, uuid, organization_id, customer_id, vehicle_id, customer_name, customer_phone, plate, vehicle_label, status, currency, notes, started_at, completed_at, paid_at, assignee_user_id, total_amount, created_by, created_at, updated_at, payment_status
`

type MarkServiceJobVoidedParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) MarkServiceJobVoided(ctx context.Context, arg MarkServiceJobVoidedParams) (ServiceJob, error) {
	row := q.db.QueryRow(ctx, markServiceJobVoided, arg.Uuid, arg.OrganizationID)
	var i ServiceJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.VehicleID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.Plate,
		&i.VehicleLabel,
		&i.Status,
		&i.Currency,
		&i.Notes,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PaidAt,
		&i.AssigneeUserID,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentStatus,
	)
	return i, err
}

const sumServiceJobsDaily = `-- name: SumServiceJobsDaily :one
SELECT
    COUNT(*)::bigint AS job_count,
    COALESCE(SUM(j.total_amount) FILTER (
        WHERE j.payment_status = 'paid'
          AND EXISTS (
              SELECT 1 FROM service_job_payments p
              WHERE p.job_id = j.id AND p.status = 'posted' AND p.method = 'card'
          )
    ), 0)::numeric AS card_total,
    COALESCE(SUM(j.total_amount) FILTER (
        WHERE j.payment_status = 'paid'
          AND EXISTS (
              SELECT 1 FROM service_job_payments p
              WHERE p.job_id = j.id AND p.status = 'posted' AND p.method = 'cari'
          )
    ), 0)::numeric AS cari_total,
    COALESCE(SUM(j.total_amount) FILTER (
        WHERE j.payment_status = 'paid'
          AND EXISTS (
              SELECT 1 FROM service_job_payments p
              WHERE p.job_id = j.id AND p.status = 'posted' AND p.method IN ('cash', 'card')
          )
    ), 0)::numeric AS net_total,
    COALESCE(SUM(j.total_amount) FILTER (WHERE j.payment_status = 'paid'), 0)::numeric AS paid_total
FROM service_jobs j
WHERE j.organization_id = $1
  AND j.started_at >= $2
  AND j.started_at < $3
`

type SumServiceJobsDailyParams struct {
	OrganizationID int64              `json:"organization_id"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	StartedAt_2    pgtype.Timestamptz `json:"started_at_2"`
}

type SumServiceJobsDailyRow struct {
	JobCount  int64          `json:"job_count"`
	CardTotal pgtype.Numeric `json:"card_total"`
	CariTotal pgtype.Numeric `json:"cari_total"`
	NetTotal  pgtype.Numeric `json:"net_total"`
	PaidTotal pgtype.Numeric `json:"paid_total"`
}

func (q *Queries) SumServiceJobsDaily(ctx context.Context, arg SumServiceJobsDailyParams) (SumServiceJobsDailyRow, error) {
	row := q.db.QueryRow(ctx, sumServiceJobsDaily, arg.OrganizationID, arg.StartedAt, arg.StartedAt_2)
	var i SumServiceJobsDailyRow
	err := row.Scan(
		&i.JobCount,
		&i.CardTotal,
		&i.CariTotal,
		&i.NetTotal,
		&i.PaidTotal,
	)
	return i, err
}

const updateServiceJobAssignee = `-- name: UpdateServiceJobAssignee :one
UPDATE service_jobs
SET assignee_user_id = $1
WHERE uuid = $2 AND organization_id = $3
  AND status IN ('in_progress', 'ready', 'delivered')
RETURNING id, uuid, organization_id, customer_id, vehicle_id, customer_name, customer_phone, plate, vehicle_label, status, currency, notes, started_at, completed_at, paid_at, assignee_user_id, total_amount, created_by, created_at, updated_at, payment_status
`

type UpdateServiceJobAssigneeParams struct {
	AssigneeUserID pgtype.Int8 `json:"assignee_user_id"`
	Uuid           uuid.UUID   `json:"uuid"`
	OrganizationID int64       `json:"organization_id"`
}

func (q *Queries) UpdateServiceJobAssignee(ctx context.Context, arg UpdateServiceJobAssigneeParams) (ServiceJob, error) {
	row := q.db.QueryRow(ctx, updateServiceJobAssignee, arg.AssigneeUserID, arg.Uuid, arg.OrganizationID)
	var i ServiceJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.VehicleID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.Plate,
		&i.VehicleLabel,
		&i.Status,
		&i.Currency,
		&i.Notes,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PaidAt,
		&i.AssigneeUserID,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentStatus,
	)
	return i, err
}

const updateServiceJobNotes = `-- name: UpdateServiceJobNotes :one
UPDATE service_jobs
SET notes = $3
WHERE uuid = $1 AND organization_id = $2
  AND status IN ('in_progress', 'ready')
RETURNING id, uuid, organization_id, customer_id, vehicle_id, customer_name, customer_phone, plate, vehicle_label, status, currency, notes, started_at, completed_at, paid_at, assignee_user_id, total_amount, created_by, created_at, updated_at, payment_status
`

type UpdateServiceJobNotesParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
	Notes          string    `json:"notes"`
}

func (q *Queries) UpdateServiceJobNotes(ctx context.Context, arg UpdateServiceJobNotesParams) (ServiceJob, error) {
	row := q.db.QueryRow(ctx, updateServiceJobNotes, arg.Uuid, arg.OrganizationID, arg.Notes)
	var i ServiceJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.CustomerID,
		&i.VehicleID,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.Plate,
		&i.VehicleLabel,
		&i.Status,
		&i.Currency,
		&i.Notes,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PaidAt,
		&i.AssigneeUserID,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaymentStatus,
	)
	return i, err
}

const voidServiceJobPayment = `-- name: VoidServiceJobPayment :one
UPDATE service_job_payments
SET status = 'void', voided_at = NOW(), voided_by = $3
WHERE uuid = $1 AND organization_id = $2 AND status = 'posted'
RETURNING id, uuid, organization_id, job_id, method, amount, currency, status, finance_account_id, finance_transaction_id, cari_entry_id, created_by, voided_at, voided_by, created_at, updated_at
`

type VoidServiceJobPaymentParams struct {
	Uuid           uuid.UUID   `json:"uuid"`
	OrganizationID int64       `json:"organization_id"`
	VoidedBy       pgtype.Int8 `json:"voided_by"`
}

func (q *Queries) VoidServiceJobPayment(ctx context.Context, arg VoidServiceJobPaymentParams) (ServiceJobPayment, error) {
	row := q.db.QueryRow(ctx, voidServiceJobPayment, arg.Uuid, arg.OrganizationID, arg.VoidedBy)
	var i ServiceJobPayment
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.JobID,
		&i.Method,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.FinanceAccountID,
		&i.FinanceTransactionID,
		&i.CariEntryID,
		&i.CreatedBy,
		&i.VoidedAt,
		&i.VoidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
