// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearOrganizationLogo = `-- name: ClearOrganizationLogo :one
UPDATE organizations
SET logo_object_key = NULL
WHERE uuid = $1 AND deleted_at IS NULL
RETURNING id, uuid, slug, name, city, district, phone, address, logo_object_key, status, plan_code, access_starts_at, access_ends_at, created_at, updated_at, deleted_at, email, website, tagline, footer_text, paper_size, primary_color
`

func (q *Queries) ClearOrganizationLogo(ctx context.Context, argUuid uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, clearOrganizationLogo, argUuid)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.Name,
		&i.City,
		&i.District,
		&i.Phone,
		&i.Address,
		&i.LogoObjectKey,
		&i.Status,
		&i.PlanCode,
		&i.AccessStartsAt,
		&i.AccessEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Website,
		&i.Tagline,
		&i.FooterText,
		&i.PaperSize,
		&i.PrimaryColor,
	)
	return i, err
}

const countOrganizations = `-- name: CountOrganizations :one
SELECT COUNT(*)::bigint
FROM organizations
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1)
  AND (
    $2::text IS NULL
    OR name ILIKE '%' || $2 || '%'
    OR slug ILIKE '%' || $2 || '%'
    OR city ILIKE '%' || $2 || '%'
    OR phone ILIKE '%' || $2 || '%'
  )
`

type CountOrganizationsParams struct {
	Status pgtype.Text `json:"status"`
	Q      pgtype.Text `json:"q"`
}

func (q *Queries) CountOrganizations(ctx context.Context, arg CountOrganizationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations, arg.Status, arg.Q)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    slug, name, city, district, phone, address, status, plan_code,
    access_starts_at, access_ends_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, uuid, slug, name, city, district, phone, address, logo_object_key, status, plan_code, access_starts_at, access_ends_at, created_at, updated_at, deleted_at, email, website, tagline, footer_text, paper_size, primary_color
`

type CreateOrganizationParams struct {
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	City           string             `json:"city"`
	District       string             `json:"district"`
	Phone          string             `json:"phone"`
	Address        string             `json:"address"`
	Status         string             `json:"status"`
	PlanCode       pgtype.Text        `json:"plan_code"`
	AccessStartsAt pgtype.Timestamptz `json:"access_starts_at"`
	AccessEndsAt   pgtype.Timestamptz `json:"access_ends_at"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Slug,
		arg.Name,
		arg.City,
		arg.District,
		arg.Phone,
		arg.Address,
		arg.Status,
		arg.PlanCode,
		arg.AccessStartsAt,
		arg.AccessEndsAt,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.Name,
		&i.City,
		&i.District,
		&i.Phone,
		&i.Address,
		&i.LogoObjectKey,
		&i.Status,
		&i.PlanCode,
		&i.AccessStartsAt,
		&i.AccessEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Website,
		&i.Tagline,
		&i.FooterText,
		&i.PaperSize,
		&i.PrimaryColor,
	)
	return i, err
}

const createOrganizationMember = `-- name: CreateOrganizationMember :one
INSERT INTO organization_members (organization_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, organization_id, user_id, role, created_at
`

type CreateOrganizationMemberParams struct {
	OrganizationID int64  `json:"organization_id"`
	UserID         int64  `json:"user_id"`
	Role           string `json:"role"`
}

func (q *Queries) CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, createOrganizationMember, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, uuid, slug, name, city, district, phone, address, logo_object_key, status, plan_code, access_starts_at, access_ends_at, created_at, updated_at, deleted_at, email, website, tagline, footer_text, paper_size, primary_color FROM organizations
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.Name,
		&i.City,
		&i.District,
		&i.Phone,
		&i.Address,
		&i.LogoObjectKey,
		&i.Status,
		&i.PlanCode,
		&i.AccessStartsAt,
		&i.AccessEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Website,
		&i.Tagline,
		&i.FooterText,
		&i.PaperSize,
		&i.PrimaryColor,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, uuid, slug, name, city, district, phone, address, logo_object_key, status, plan_code, access_starts_at, access_ends_at, created_at, updated_at, deleted_at, email, website, tagline, footer_text, paper_size, primary_color FROM organizations
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.Name,
		&i.City,
		&i.District,
		&i.Phone,
		&i.Address,
		&i.LogoObjectKey,
		&i.Status,
		&i.PlanCode,
		&i.AccessStartsAt,
		&i.AccessEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Website,
		&i.Tagline,
		&i.FooterText,
		&i.PaperSize,
		&i.PrimaryColor,
	)
	return i, err
}

const getOrganizationByUUID = `-- name: GetOrganizationByUUID :one
SELECT id, uuid, slug, name, city, district, phone, address, logo_object_key, status, plan_code, access_starts_at, access_ends_at, created_at, updated_at, deleted_at, email, website, tagline, footer_text, paper_size, primary_color FROM organizations
WHERE uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByUUID(ctx context.Context, argUuid uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByUUID, argUuid)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.Name,
		&i.City,
		&i.District,
		&i.Phone,
		&i.Address,
		&i.LogoObjectKey,
		&i.Status,
		&i.PlanCode,
		&i.AccessStartsAt,
		&i.AccessEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Website,
		&i.Tagline,
		&i.FooterText,
		&i.PaperSize,
		&i.PrimaryColor,
	)
	return i, err
}

const getOrganizationMember = `-- name: GetOrganizationMember :one
SELECT om.id, om.organization_id, om.user_id, om.role, om.created_at, o.uuid AS organization_uuid, o.slug AS organization_slug
FROM organization_members om
JOIN organizations o ON o.id = om.organization_id AND o.deleted_at IS NULL
WHERE om.organization_id = $1 AND om.user_id = $2
`

type GetOrganizationMemberParams struct {
	OrganizationID int64 `json:"organization_id"`
	UserID         int64 `json:"user_id"`
}

type GetOrganizationMemberRow struct {
	ID               int64              `json:"id"`
	OrganizationID   int64              `json:"organization_id"`
	UserID           int64              `json:"user_id"`
	Role             string             `json:"role"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	OrganizationUuid uuid.UUID          `json:"organization_uuid"`
	OrganizationSlug string             `json:"organization_slug"`
}

func (q *Queries) GetOrganizationMember(ctx context.Context, arg GetOrganizationMemberParams) (GetOrganizationMemberRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationMember, arg.OrganizationID, arg.UserID)
	var i GetOrganizationMemberRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.OrganizationUuid,
		&i.OrganizationSlug,
	)
	return i, err
}

const getOrganizationMemberByUserAndOrgUUID = `-- name: GetOrganizationMemberByUserAndOrgUUID :one
SELECT om.id, om.organization_id, om.user_id, om.role, om.created_at,
       o.uuid AS organization_uuid, o.slug AS organization_slug, o.status AS organization_status,
       o.access_starts_at, o.access_ends_at, o.name AS organization_name
FROM organization_members om
JOIN organizations o ON o.id = om.organization_id AND o.deleted_at IS NULL
WHERE om.user_id = $1 AND o.uuid = $2
`

type GetOrganizationMemberByUserAndOrgUUIDParams struct {
	UserID int64     `json:"user_id"`
	Uuid   uuid.UUID `json:"uuid"`
}

type GetOrganizationMemberByUserAndOrgUUIDRow struct {
	ID                 int64              `json:"id"`
	OrganizationID     int64              `json:"organization_id"`
	UserID             int64              `json:"user_id"`
	Role               string             `json:"role"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	OrganizationUuid   uuid.UUID          `json:"organization_uuid"`
	OrganizationSlug   string             `json:"organization_slug"`
	OrganizationStatus string             `json:"organization_status"`
	AccessStartsAt     pgtype.Timestamptz `json:"access_starts_at"`
	AccessEndsAt       pgtype.Timestamptz `json:"access_ends_at"`
	OrganizationName   string             `json:"organization_name"`
}

func (q *Queries) GetOrganizationMemberByUserAndOrgUUID(ctx context.Context, arg GetOrganizationMemberByUserAndOrgUUIDParams) (GetOrganizationMemberByUserAndOrgUUIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationMemberByUserAndOrgUUID, arg.UserID, arg.Uuid)
	var i GetOrganizationMemberByUserAndOrgUUIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.OrganizationUuid,
		&i.OrganizationSlug,
		&i.OrganizationStatus,
		&i.AccessStartsAt,
		&i.AccessEndsAt,
		&i.OrganizationName,
	)
	return i, err
}

const getOrganizationMemberByUserAndSlug = `-- name: GetOrganizationMemberByUserAndSlug :one
SELECT om.id, om.organization_id, om.user_id, om.role, om.created_at, o.uuid AS organization_uuid, o.slug AS organization_slug, o.status AS organization_status,
       o.access_starts_at, o.access_ends_at, o.name AS organization_name, o.logo_object_key
FROM organization_members om
JOIN organizations o ON o.id = om.organization_id AND o.deleted_at IS NULL
WHERE om.user_id = $1 AND o.slug = $2
`

type GetOrganizationMemberByUserAndSlugParams struct {
	UserID int64  `json:"user_id"`
	Slug   string `json:"slug"`
}

type GetOrganizationMemberByUserAndSlugRow struct {
	ID                 int64              `json:"id"`
	OrganizationID     int64              `json:"organization_id"`
	UserID             int64              `json:"user_id"`
	Role               string             `json:"role"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	OrganizationUuid   uuid.UUID          `json:"organization_uuid"`
	OrganizationSlug   string             `json:"organization_slug"`
	OrganizationStatus string             `json:"organization_status"`
	AccessStartsAt     pgtype.Timestamptz `json:"access_starts_at"`
	AccessEndsAt       pgtype.Timestamptz `json:"access_ends_at"`
	OrganizationName   string             `json:"organization_name"`
	LogoObjectKey      pgtype.Text        `json:"logo_object_key"`
}

func (q *Queries) GetOrganizationMemberByUserAndSlug(ctx context.Context, arg GetOrganizationMemberByUserAndSlugParams) (GetOrganizationMemberByUserAndSlugRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationMemberByUserAndSlug, arg.UserID, arg.Slug)
	var i GetOrganizationMemberByUserAndSlugRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.OrganizationUuid,
		&i.OrganizationSlug,
		&i.OrganizationStatus,
		&i.AccessStartsAt,
		&i.AccessEndsAt,
		&i.OrganizationName,
		&i.LogoObjectKey,
	)
	return i, err
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT u.uuid, u.email, u.name, u.surname, u.status, om.role, om.created_at
FROM organization_members om
JOIN users u ON u.id = om.user_id AND u.deleted_at IS NULL
WHERE om.organization_id = $1
ORDER BY om.created_at ASC
`

type ListOrganizationMembersRow struct {
	Uuid      uuid.UUID          `json:"uuid"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Surname   string             `json:"surname"`
	Status    string             `json:"status"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, organizationID int64) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersRow{}
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Email,
			&i.Name,
			&i.Surname,
			&i.Status,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationMembersByUserID = `-- name: ListOrganizationMembersByUserID :many
SELECT om.role, o.uuid, o.slug, o.name, o.logo_object_key, o.status, o.access_ends_at
FROM organization_members om
JOIN organizations o ON o.id = om.organization_id AND o.deleted_at IS NULL
WHERE om.user_id = $1
ORDER BY o.name ASC
`

type ListOrganizationMembersByUserIDRow struct {
	Role          string             `json:"role"`
	Uuid          uuid.UUID          `json:"uuid"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	LogoObjectKey pgtype.Text        `json:"logo_object_key"`
	Status        string             `json:"status"`
	AccessEndsAt  pgtype.Timestamptz `json:"access_ends_at"`
}

func (q *Queries) ListOrganizationMembersByUserID(ctx context.Context, userID int64) ([]ListOrganizationMembersByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersByUserIDRow{}
	for rows.Next() {
		var i ListOrganizationMembersByUserIDRow
		if err := rows.Scan(
			&i.Role,
			&i.Uuid,
			&i.Slug,
			&i.Name,
			&i.LogoObjectKey,
			&i.Status,
			&i.AccessEndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsFiltered = `-- name: ListOrganizationsFiltered :many
SELECT id, uuid, slug, name, city, district, phone, address, logo_object_key, status, plan_code, access_starts_at, access_ends_at, created_at, updated_at, deleted_at, email, website, tagline, footer_text, paper_size, primary_color
FROM organizations
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1)
  AND (
    $2::text IS NULL
    OR name ILIKE '%' || $2 || '%'
    OR slug ILIKE '%' || $2 || '%'
    OR city ILIKE '%' || $2 || '%'
    OR phone ILIKE '%' || $2 || '%'
  )
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListOrganizationsFilteredParams struct {
	Status      pgtype.Text `json:"status"`
	Q           pgtype.Text `json:"q"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListOrganizationsFiltered(ctx context.Context, arg ListOrganizationsFilteredParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizationsFiltered,
		arg.Status,
		arg.Q,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Slug,
			&i.Name,
			&i.City,
			&i.District,
			&i.Phone,
			&i.Address,
			&i.LogoObjectKey,
			&i.Status,
			&i.PlanCode,
			&i.AccessStartsAt,
			&i.AccessEndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Email,
			&i.Website,
			&i.Tagline,
			&i.FooterText,
			&i.PaperSize,
			&i.PrimaryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrganizationLogo = `-- name: SetOrganizationLogo :one
UPDATE organizations
SET logo_object_key = $2
WHERE uuid = $1 AND deleted_at IS NULL
RETURNING id, uuid, slug, name, city, district, phone, address, logo_object_key, status, plan_code, access_starts_at, access_ends_at, created_at, updated_at, deleted_at, email, website, tagline, footer_text, paper_size, primary_color
`

type SetOrganizationLogoParams struct {
	Uuid          uuid.UUID   `json:"uuid"`
	LogoObjectKey pgtype.Text `json:"logo_object_key"`
}

func (q *Queries) SetOrganizationLogo(ctx context.Context, arg SetOrganizationLogoParams) (Organization, error) {
	row := q.db.QueryRow(ctx, setOrganizationLogo, arg.Uuid, arg.LogoObjectKey)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.Name,
		&i.City,
		&i.District,
		&i.Phone,
		&i.Address,
		&i.LogoObjectKey,
		&i.Status,
		&i.PlanCode,
		&i.AccessStartsAt,
		&i.AccessEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Website,
		&i.Tagline,
		&i.FooterText,
		&i.PaperSize,
		&i.PrimaryColor,
	)
	return i, err
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS(
    SELECT 1 FROM organizations WHERE slug = $1 AND deleted_at IS NULL
) AS exists
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateOrganizationLetterhead = `-- name: UpdateOrganizationLetterhead :one
UPDATE organizations
SET name = COALESCE($1, name),
    city = COALESCE($2, city),
    district = COALESCE($3, district),
    phone = COALESCE($4, phone),
    address = COALESCE($5, address),
    email = COALESCE($6, email),
    website = COALESCE($7, website),
    tagline = COALESCE($8, tagline),
    footer_text = COALESCE($9, footer_text),
    paper_size = COALESCE($10, paper_size),
    primary_color = COALESCE($11, primary_color)
WHERE id = $12 AND deleted_at IS NULL
RETURNING id, uuid, slug, name, city, district, phone, address, logo_object_key, status, plan_code, access_starts_at, access_ends_at, created_at, updated_at, deleted_at, email, website, tagline, footer_text, paper_size, primary_color
`

type UpdateOrganizationLetterheadParams struct {
	Name         pgtype.Text `json:"name"`
	City         pgtype.Text `json:"city"`
	District     pgtype.Text `json:"district"`
	Phone        pgtype.Text `json:"phone"`
	Address      pgtype.Text `json:"address"`
	Email        pgtype.Text `json:"email"`
	Website      pgtype.Text `json:"website"`
	Tagline      pgtype.Text `json:"tagline"`
	FooterText   pgtype.Text `json:"footer_text"`
	PaperSize    pgtype.Text `json:"paper_size"`
	PrimaryColor pgtype.Text `json:"primary_color"`
	ID           int64       `json:"id"`
}

func (q *Queries) UpdateOrganizationLetterhead(ctx context.Context, arg UpdateOrganizationLetterheadParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationLetterhead,
		arg.Name,
		arg.City,
		arg.District,
		arg.Phone,
		arg.Address,
		arg.Email,
		arg.Website,
		arg.Tagline,
		arg.FooterText,
		arg.PaperSize,
		arg.PrimaryColor,
		arg.ID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.Name,
		&i.City,
		&i.District,
		&i.Phone,
		&i.Address,
		&i.LogoObjectKey,
		&i.Status,
		&i.PlanCode,
		&i.AccessStartsAt,
		&i.AccessEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Website,
		&i.Tagline,
		&i.FooterText,
		&i.PaperSize,
		&i.PrimaryColor,
	)
	return i, err
}

const updateOrganizationPlatform = `-- name: UpdateOrganizationPlatform :one
UPDATE organizations
SET name = COALESCE($1, name),
    city = COALESCE($2, city),
    district = COALESCE($3, district),
    phone = COALESCE($4, phone),
    address = COALESCE($5, address),
    status = COALESCE($6, status),
    plan_code = COALESCE($7, plan_code),
    access_starts_at = COALESCE($8, access_starts_at),
    access_ends_at = $9
WHERE uuid = $10 AND deleted_at IS NULL
RETURNING id, uuid, slug, name, city, district, phone, address, logo_object_key, status, plan_code, access_starts_at, access_ends_at, created_at, updated_at, deleted_at, email, website, tagline, footer_text, paper_size, primary_color
`

type UpdateOrganizationPlatformParams struct {
	Name           pgtype.Text        `json:"name"`
	City           pgtype.Text        `json:"city"`
	District       pgtype.Text        `json:"district"`
	Phone          pgtype.Text        `json:"phone"`
	Address        pgtype.Text        `json:"address"`
	Status         pgtype.Text        `json:"status"`
	PlanCode       pgtype.Text        `json:"plan_code"`
	AccessStartsAt pgtype.Timestamptz `json:"access_starts_at"`
	AccessEndsAt   pgtype.Timestamptz `json:"access_ends_at"`
	Uuid           uuid.UUID          `json:"uuid"`
}

func (q *Queries) UpdateOrganizationPlatform(ctx context.Context, arg UpdateOrganizationPlatformParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationPlatform,
		arg.Name,
		arg.City,
		arg.District,
		arg.Phone,
		arg.Address,
		arg.Status,
		arg.PlanCode,
		arg.AccessStartsAt,
		arg.AccessEndsAt,
		arg.Uuid,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Slug,
		&i.Name,
		&i.City,
		&i.District,
		&i.Phone,
		&i.Address,
		&i.LogoObjectKey,
		&i.Status,
		&i.PlanCode,
		&i.AccessStartsAt,
		&i.AccessEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Website,
		&i.Tagline,
		&i.FooterText,
		&i.PaperSize,
		&i.PrimaryColor,
	)
	return i, err
}
