// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Turkish-folded search for the assistant: name (diacritics-insensitive),
	// phone digits, or normalized plate.
	AISearchCustomers(ctx context.Context, arg AISearchCustomersParams) ([]AISearchCustomersRow, error)
	AddVehicleModelYear(ctx context.Context, arg AddVehicleModelYearParams) error
	AdjustCariAccountBalance(ctx context.Context, arg AdjustCariAccountBalanceParams) (CariAccount, error)
	AdjustFinanceAccountBalance(ctx context.Context, arg AdjustFinanceAccountBalanceParams) (FinanceAccount, error)
	AdjustProductStock(ctx context.Context, arg AdjustProductStockParams) (Product, error)
	AdjustProductStockByID(ctx context.Context, arg AdjustProductStockByIDParams) error
	AssignUserRoleBySlug(ctx context.Context, arg AssignUserRoleBySlugParams) error
	AttachAIPendingActionsToMessage(ctx context.Context, arg AttachAIPendingActionsToMessageParams) error
	BillingApprovedThisMonth(ctx context.Context, arg BillingApprovedThisMonthParams) (BillingApprovedThisMonthRow, error)
	BillingDiscountSummaries(ctx context.Context) ([]BillingDiscountSummariesRow, error)
	BillingExpiringCounts(ctx context.Context, arg BillingExpiringCountsParams) (BillingExpiringCountsRow, error)
	BillingPlanDistribution(ctx context.Context) ([]BillingPlanDistributionRow, error)
	BillingSubscriptionStatusCounts(ctx context.Context) (BillingSubscriptionStatusCountsRow, error)
	// Trials started in the window (any current status) and how many of those
	// organizations later moved to a non-trial plan.
	BillingTrialConversion(ctx context.Context, sinceAt pgtype.Timestamptz) (BillingTrialConversionRow, error)
	CancelAIPendingAction(ctx context.Context, id int64) (AiPendingAction, error)
	CancelOpenQuoteReminders(ctx context.Context, quoteID int64) ([]QuoteReminder, error)
	CancelScheduledNotificationsBySubject(ctx context.Context, arg CancelScheduledNotificationsBySubjectParams) (int64, error)
	// The pending → executing transition is the idempotency lock for confirm.
	ClaimAIPendingAction(ctx context.Context, arg ClaimAIPendingActionParams) (AiPendingAction, error)
	// Marks today's summary as sent; 0 rows when another sweep already claimed it.
	ClaimDailySummary(ctx context.Context, arg ClaimDailySummaryParams) (int64, error)
	// Atomic batch claim; concurrent sweepers skip each other's rows.
	ClaimDueScheduledNotifications(ctx context.Context, arg ClaimDueScheduledNotificationsParams) ([]ScheduledNotification, error)
	// queued → sending; a second delivery of the same task finds no row.
	ClaimOutboundMessage(ctx context.Context, id int64) (OutboundMessage, error)
	ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]OutboxEvent, error)
	ClaimScheduledNotificationByID(ctx context.Context, id int64) (ScheduledNotification, error)
	// Serialises flushes per org and enforces the batch window.
	ClaimVehicleAlertFlush(ctx context.Context, organizationID int64) (int64, error)
	ClearAppSettingsLogo(ctx context.Context) (AppSetting, error)
	ClearFinanceAccountDefault(ctx context.Context, organizationID int64) error
	ClearOrganizationAccessEnd(ctx context.Context, id int64) error
	ClearOrganizationLogo(ctx context.Context, argUuid uuid.UUID) (Organization, error)
	CloseSubscription(ctx context.Context, arg CloseSubscriptionParams) error
	ConfirmUserTOTP(ctx context.Context, arg ConfirmUserTOTPParams) (UserTotp, error)
	ConsumeOTP(ctx context.Context, id int64) (int64, error)
	ConsumeUsage(ctx context.Context, arg ConsumeUsageParams) (int64, error)
	CountAIConversations(ctx context.Context, arg CountAIConversationsParams) (int64, error)
	CountActiveJobsInRange(ctx context.Context, arg CountActiveJobsInRangeParams) (int64, error)
	CountActiveVehicleModelsByBrand(ctx context.Context, brandID int64) (int64, error)
	CountActivityEvents(ctx context.Context, arg CountActivityEventsParams) (int64, error)
	CountAllBulkJobs(ctx context.Context) (int64, error)
	CountAllExportJobs(ctx context.Context) (int64, error)
	CountAllImportJobs(ctx context.Context) (int64, error)
	CountAppLogs(ctx context.Context, arg CountAppLogsParams) (int64, error)
	CountAppLogsByLevel(ctx context.Context) ([]CountAppLogsByLevelRow, error)
	CountApprovedOrdersForOrg(ctx context.Context, organizationID int64) (int64, error)
	CountBulkJobsForActor(ctx context.Context, actorID int64) (int64, error)
	CountCariAccounts(ctx context.Context, arg CountCariAccountsParams) (int64, error)
	CountCariEntries(ctx context.Context, arg CountCariEntriesParams) (int64, error)
	CountCatalogCategories(ctx context.Context, arg CountCatalogCategoriesParams) (int64, error)
	CountContractInstances(ctx context.Context, arg CountContractInstancesParams) (int64, error)
	CountContractPresets(ctx context.Context, arg CountContractPresetsParams) (int64, error)
	CountContractSignerOTPsSince(ctx context.Context, arg CountContractSignerOTPsSinceParams) (int64, error)
	CountContractTemplates(ctx context.Context, arg CountContractTemplatesParams) (int64, error)
	CountCustomerVehiclesByModel(ctx context.Context, modelID int64) (int64, error)
	CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error)
	CountDiscountCodes(ctx context.Context, q_ string) (int64, error)
	CountDiscountUses(ctx context.Context, discountCodeID int64) (int64, error)
	CountDiscountUsesByOrg(ctx context.Context, arg CountDiscountUsesByOrgParams) (int64, error)
	CountExportJobsForActor(ctx context.Context, actorID int64) (int64, error)
	CountExportJobsForOrganization(ctx context.Context, organizationID pgtype.Int8) (int64, error)
	CountFinanceAccounts(ctx context.Context, arg CountFinanceAccountsParams) (int64, error)
	CountFinanceTransactions(ctx context.Context, arg CountFinanceTransactionsParams) (int64, error)
	CountImportJobsForActor(ctx context.Context, actorID int64) (int64, error)
	CountImportJobsForOrganization(ctx context.Context, organizationID int64) (int64, error)
	CountInvoices(ctx context.Context, arg CountInvoicesParams) (int64, error)
	CountInvoicesForOrg(ctx context.Context, organizationID int64) (int64, error)
	CountLeads(ctx context.Context, arg CountLeadsParams) (int64, error)
	CountLiveSubscriptionsByPlan(ctx context.Context, planID int64) (int64, error)
	CountNotificationsForUser(ctx context.Context, arg CountNotificationsForUserParams) (int64, error)
	CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error)
	CountOrdersForOrg(ctx context.Context, arg CountOrdersForOrgParams) (int64, error)
	CountOrgCustomers(ctx context.Context, organizationID int64) (int64, error)
	// Staff seats only: owners are not counted against staff.count.
	CountOrgMembers(ctx context.Context, organizationID int64) (int64, error)
	CountOrganizations(ctx context.Context, arg CountOrganizationsParams) (int64, error)
	CountOutboxByStatus(ctx context.Context, status string) (int64, error)
	CountPendingRequiredSigners(ctx context.Context, instanceID int64) (int64, error)
	CountPermissions(ctx context.Context, q_ pgtype.Text) (int64, error)
	CountPlatformNotifications(ctx context.Context, arg CountPlatformNotificationsParams) (int64, error)
	CountPostedPurchasesBySupplier(ctx context.Context, arg CountPostedPurchasesBySupplierParams) (int64, error)
	CountProductSales(ctx context.Context, arg CountProductSalesParams) (int64, error)
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CountPurchases(ctx context.Context, arg CountPurchasesParams) (int64, error)
	CountQuotes(ctx context.Context, arg CountQuotesParams) (int64, error)
	CountRoles(ctx context.Context, q_ pgtype.Text) (int64, error)
	CountServiceJobs(ctx context.Context, arg CountServiceJobsParams) (int64, error)
	CountServiceJobsByCustomer(ctx context.Context, arg CountServiceJobsByCustomerParams) (int64, error)
	CountServiceProductsByService(ctx context.Context, organizationID int64) ([]CountServiceProductsByServiceRow, error)
	CountServices(ctx context.Context, arg CountServicesParams) (int64, error)
	CountStorageActivity(ctx context.Context, objectKey string) (int64, error)
	CountStorageTrash(ctx context.Context) (int64, error)
	CountSubscriptionsAdmin(ctx context.Context, arg CountSubscriptionsAdminParams) (int64, error)
	CountSuppliers(ctx context.Context, arg CountSuppliersParams) (int64, error)
	CountTodos(ctx context.Context, arg CountTodosParams) (int64, error)
	CountUnreadInappForUser(ctx context.Context, userID pgtype.Int8) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CountUsersWithRole(ctx context.Context, roleSlug string) (int64, error)
	CountVehicleBrands(ctx context.Context, arg CountVehicleBrandsParams) (int64, error)
	CreateAIConversation(ctx context.Context, arg CreateAIConversationParams) (AiConversation, error)
	CreateBillingPlan(ctx context.Context, arg CreateBillingPlanParams) (BillingPlan, error)
	CreateBulkJob(ctx context.Context, arg CreateBulkJobParams) (BulkJob, error)
	// Tenant cari (accounts receivable) accounts and ledger entries.
	CreateCariAccount(ctx context.Context, arg CreateCariAccountParams) (CariAccount, error)
	CreateCariEntry(ctx context.Context, arg CreateCariEntryParams) (CariEntry, error)
	// Catalog module queries (tenant-scoped via organization_id).
	// ============================================================================
	// Categories
	// ============================================================================
	CreateCatalogCategory(ctx context.Context, arg CreateCatalogCategoryParams) (CatalogCategory, error)
	CreateContractInstance(ctx context.Context, arg CreateContractInstanceParams) (ContractInstance, error)
	CreateContractMedia(ctx context.Context, arg CreateContractMediaParams) (ContractMedium, error)
	CreateContractPreset(ctx context.Context, arg CreateContractPresetParams) (ContractPreset, error)
	CreateContractSignature(ctx context.Context, arg CreateContractSignatureParams) (ContractSignature, error)
	CreateContractSigner(ctx context.Context, arg CreateContractSignerParams) (ContractSigner, error)
	CreateContractSignerOTP(ctx context.Context, arg CreateContractSignerOTPParams) (ContractSignerOtp, error)
	CreateContractTemplate(ctx context.Context, arg CreateContractTemplateParams) (ContractTemplate, error)
	// Tenant customers and their vehicles.
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateCustomerVehicle(ctx context.Context, arg CreateCustomerVehicleParams) (CustomerVehicle, error)
	CreateDiscountCode(ctx context.Context, arg CreateDiscountCodeParams) (BillingDiscountCode, error)
	CreateDisplayFeature(ctx context.Context, arg CreateDisplayFeatureParams) (BillingFeature, error)
	CreateExportJob(ctx context.Context, arg CreateExportJobParams) (ExportJob, error)
	// Finance module queries (tenant-scoped via organization_id).
	// TODO(finance): Add GetFinanceCategoryByID and composite indexes if list/filter
	// latency grows (organization_id + transaction_date DESC).
	CreateFinanceAccount(ctx context.Context, arg CreateFinanceAccountParams) (FinanceAccount, error)
	CreateFinanceCategory(ctx context.Context, arg CreateFinanceCategoryParams) (FinanceCategory, error)
	CreateFinanceTransaction(ctx context.Context, arg CreateFinanceTransactionParams) (FinanceTransaction, error)
	CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportJob, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (BillingInvoice, error)
	CreateJobConsumption(ctx context.Context, arg CreateJobConsumptionParams) (ServiceJobConsumption, error)
	// Tenant leads and their timeline. Every query is scoped by organization_id.
	CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error)
	CreateLeadEvent(ctx context.Context, arg CreateLeadEventParams) (LeadEvent, error)
	CreateLogPurgeRule(ctx context.Context, arg CreateLogPurgeRuleParams) (LogPurgeRule, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error)
	CreateOTPCode(ctx context.Context, arg CreateOTPCodeParams) (OtpCode, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (BillingOrder, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) (OrganizationMember, error)
	// ============================================================================
	// Products
	// ============================================================================
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// Tenant quick product sales.
	CreateProductSale(ctx context.Context, arg CreateProductSaleParams) (ProductSale, error)
	CreateProductSaleLine(ctx context.Context, arg CreateProductSaleLineParams) (ProductSaleLine, error)
	// Tenant stock purchases.
	CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error)
	CreatePurchaseLine(ctx context.Context, arg CreatePurchaseLineParams) (PurchaseLine, error)
	CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error)
	CreateQuoteDelivery(ctx context.Context, arg CreateQuoteDeliveryParams) (QuoteDelivery, error)
	CreateQuoteEvent(ctx context.Context, arg CreateQuoteEventParams) (QuoteEvent, error)
	CreateQuoteLine(ctx context.Context, arg CreateQuoteLineParams) (QuoteLine, error)
	CreateQuoteReminder(ctx context.Context, arg CreateQuoteReminderParams) (QuoteReminder, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	// ============================================================================
	// Services
	// ============================================================================
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	// Tenant service jobs (operations / iş emri).
	CreateServiceJob(ctx context.Context, arg CreateServiceJobParams) (ServiceJob, error)
	CreateServiceJobLine(ctx context.Context, arg CreateServiceJobLineParams) (ServiceJobLine, error)
	CreateServiceJobPayment(ctx context.Context, arg CreateServiceJobPaymentParams) (ServiceJobPayment, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (BillingSubscription, error)
	CreateSubscriptionWithCredit(ctx context.Context, arg CreateSubscriptionWithCreditParams) (BillingSubscription, error)
	// Tenant suppliers (firmalar).
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// System-wide vehicle brand / model / year catalog.
	CreateVehicleBrand(ctx context.Context, arg CreateVehicleBrandParams) (VehicleBrand, error)
	CreateVehicleModel(ctx context.Context, arg CreateVehicleModelParams) (VehicleModel, error)
	CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) (WebauthnCredential, error)
	DailySummaryAccounts(ctx context.Context, organizationID int64) ([]DailySummaryAccountsRow, error)
	// Posted expenses for the day, excluding stock purchases (reported separately).
	DailySummaryExpenses(ctx context.Context, arg DailySummaryExpensesParams) (DailySummaryExpensesRow, error)
	DailySummaryJobCounts(ctx context.Context, arg DailySummaryJobCountsParams) (DailySummaryJobCountsRow, error)
	DailySummaryPurchases(ctx context.Context, arg DailySummaryPurchasesParams) (DailySummaryPurchasesRow, error)
	DailySummarySales(ctx context.Context, arg DailySummarySalesParams) (DailySummarySalesRow, error)
	// Vehicles per service for the day ("12 × Yıkama, 1 × PPF").
	DailySummaryServiceBreakdown(ctx context.Context, arg DailySummaryServiceBreakdownParams) ([]DailySummaryServiceBreakdownRow, error)
	DeactivateDiscountCode(ctx context.Context, argUuid uuid.UUID) error
	// Self-service account deletion: keep every row, mark the user disabled.
	DeactivateUser(ctx context.Context, id int64) (User, error)
	DeleteAppLogByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error)
	DeleteAppLogsByUUIDs(ctx context.Context, uuids []uuid.UUID) (int64, error)
	DeleteAppLogsMatching(ctx context.Context, arg DeleteAppLogsMatchingParams) (int64, error)
	DeleteContractMedia(ctx context.Context, arg DeleteContractMediaParams) error
	DeleteJobConsumption(ctx context.Context, arg DeleteJobConsumptionParams) error
	DeleteLogPurgeRule(ctx context.Context, argUuid uuid.UUID) (int64, error)
	DeleteMessageTemplate(ctx context.Context, arg DeleteMessageTemplateParams) error
	DeleteMessageTemplateByKey(ctx context.Context, arg DeleteMessageTemplateByKeyParams) (int64, error)
	DeleteOAuthAccountByProviderAccount(ctx context.Context, arg DeleteOAuthAccountByProviderAccountParams) error
	DeleteOAuthAccountByUserProvider(ctx context.Context, arg DeleteOAuthAccountByUserProviderParams) error
	DeletePlanFeatures(ctx context.Context, planID int64) error
	DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error
	DeleteQuoteLines(ctx context.Context, arg DeleteQuoteLinesParams) error
	DeleteRole(ctx context.Context, argUuid uuid.UUID) error
	DeleteServiceProducts(ctx context.Context, arg DeleteServiceProductsParams) error
	DeleteStorageShare(ctx context.Context, argUuid uuid.UUID) error
	DeleteStorageStar(ctx context.Context, arg DeleteStorageStarParams) error
	DeleteStorageTrashByUUID(ctx context.Context, argUuid uuid.UUID) error
	DeleteTodo(ctx context.Context, arg DeleteTodoParams) error
	DeleteUnusedDiscountCode(ctx context.Context, argUuid uuid.UUID) (int64, error)
	DeleteUserTOTP(ctx context.Context, userID int64) error
	DeleteVehicleModelYear(ctx context.Context, arg DeleteVehicleModelYearParams) error
	DeleteWebAuthnCredentialByCredentialID(ctx context.Context, credentialID string) error
	DeleteWebAuthnCredentialByUUID(ctx context.Context, arg DeleteWebAuthnCredentialByUUIDParams) error
	DescribeTodoLeadLinks(ctx context.Context, arg DescribeTodoLeadLinksParams) ([]DescribeTodoLeadLinksRow, error)
	DescribeTodoQuoteLinks(ctx context.Context, arg DescribeTodoQuoteLinksParams) ([]DescribeTodoQuoteLinksRow, error)
	// Lines older than the cutoff are not worth a late WhatsApp (line was down).
	DropStaleVehicleAlertEvents(ctx context.Context, arg DropStaleVehicleAlertEventsParams) error
	// Expires pending actions of a conversation: all of them (the user moved on)
	// or only those past expires_at.
	ExpireAIPendingActions(ctx context.Context, arg ExpireAIPendingActionsParams) ([]AiPendingAction, error)
	ExpireDueOrders(ctx context.Context) ([]ExpireDueOrdersRow, error)
	// Marks open quotes whose valid_until day has passed as expired. Idempotent:
	// a second run finds nothing; accepted / rejected / cancelled rows are never touched.
	ExpireDueQuotes(ctx context.Context, arg ExpireDueQuotesParams) ([]ExpireDueQuotesRow, error)
	ExtensionExists(ctx context.Context, extname string) (bool, error)
	// Async WhatsApp failure reported after the delivery was handed off.
	FailQuoteDeliveryByRef(ctx context.Context, arg FailQuoteDeliveryByRefParams) (QuoteDelivery, error)
	// Async WhatsApp failure of a reminder that was already handed off.
	FailQuoteReminderByRef(ctx context.Context, arg FailQuoteReminderByRefParams) (QuoteReminder, error)
	// Resolves actions stuck in 'executing' (the server stopped mid-execution) as
	// failed: for one conversation, or for all conversations when it is NULL.
	FailStaleAIPendingActions(ctx context.Context, arg FailStaleAIPendingActionsParams) ([]AiPendingAction, error)
	FinishAIPendingAction(ctx context.Context, arg FinishAIPendingActionParams) (AiPendingAction, error)
	FinishOutboundMessage(ctx context.Context, arg FinishOutboundMessageParams) (OutboundMessage, error)
	FinishQuoteDelivery(ctx context.Context, arg FinishQuoteDeliveryParams) (QuoteDelivery, error)
	FinishQuoteReminder(ctx context.Context, arg FinishQuoteReminderParams) (QuoteReminder, error)
	GetAIConversation(ctx context.Context, arg GetAIConversationParams) (AiConversation, error)
	GetAIMessageByID(ctx context.Context, id int64) (AiMessage, error)
	GetAIOrganizationByUUID(ctx context.Context, argUuid uuid.UUID) (GetAIOrganizationByUUIDRow, error)
	GetAIOrganizationSettings(ctx context.Context, organizationID int64) (AiOrganizationSetting, error)
	GetAIPendingActionForUser(ctx context.Context, arg GetAIPendingActionForUserParams) (GetAIPendingActionForUserRow, error)
	GetAISettings(ctx context.Context) (AiSetting, error)
	GetAIUserDisplay(ctx context.Context, id int64) (GetAIUserDisplayRow, error)
	GetActiveJobConsumptionByProduct(ctx context.Context, arg GetActiveJobConsumptionByProductParams) (ServiceJobConsumption, error)
	GetActiveOTPByEmailType(ctx context.Context, arg GetActiveOTPByEmailTypeParams) (OtpCode, error)
	GetAppLogByUUID(ctx context.Context, argUuid uuid.UUID) (AppLog, error)
	GetAppSettings(ctx context.Context) (AppSetting, error)
	GetAuthSettings(ctx context.Context) (GetAuthSettingsRow, error)
	GetBillingPlanByCode(ctx context.Context, code string) (BillingPlan, error)
	GetBillingPlanByUUID(ctx context.Context, argUuid uuid.UUID) (BillingPlan, error)
	// Billing settings, discounts, orders and admin subscription queries.
	GetBillingSettings(ctx context.Context) (BillingSetting, error)
	GetBulkJobByID(ctx context.Context, id int64) (BulkJob, error)
	GetBulkJobByUUID(ctx context.Context, argUuid uuid.UUID) (BulkJob, error)
	GetCariAccountByCustomerID(ctx context.Context, arg GetCariAccountByCustomerIDParams) (CariAccount, error)
	GetCariAccountByID(ctx context.Context, arg GetCariAccountByIDParams) (CariAccount, error)
	GetCariAccountByUUID(ctx context.Context, arg GetCariAccountByUUIDParams) (GetCariAccountByUUIDRow, error)
	GetCariAccountForSearch(ctx context.Context, arg GetCariAccountForSearchParams) (GetCariAccountForSearchRow, error)
	GetCariEntryBySource(ctx context.Context, arg GetCariEntryBySourceParams) (CariEntry, error)
	GetCariEntryByUUID(ctx context.Context, arg GetCariEntryByUUIDParams) (GetCariEntryByUUIDRow, error)
	GetCatalogCategoryByID(ctx context.Context, arg GetCatalogCategoryByIDParams) (CatalogCategory, error)
	GetCatalogCategoryByName(ctx context.Context, arg GetCatalogCategoryByNameParams) (CatalogCategory, error)
	GetCatalogCategoryByUUID(ctx context.Context, arg GetCatalogCategoryByUUIDParams) (CatalogCategory, error)
	// Each aggregate reads its own table: joining products, services and
	// categories together multiplies the product sums by the other row counts.
	GetCatalogStats(ctx context.Context, organizationID int64) (GetCatalogStatsRow, error)
	GetContractInstanceByID(ctx context.Context, id int64) (ContractInstance, error)
	GetContractInstanceByUUID(ctx context.Context, arg GetContractInstanceByUUIDParams) (ContractInstance, error)
	GetContractInstanceMessagingByUUID(ctx context.Context, argUuid uuid.UUID) (GetContractInstanceMessagingByUUIDRow, error)
	GetContractMediaByUUID(ctx context.Context, arg GetContractMediaByUUIDParams) (ContractMedium, error)
	GetContractPresetByUUID(ctx context.Context, argUuid uuid.UUID) (ContractPreset, error)
	GetContractSignerByUUID(ctx context.Context, arg GetContractSignerByUUIDParams) (ContractSigner, error)
	GetContractTemplateByUUID(ctx context.Context, arg GetContractTemplateByUUIDParams) (ContractTemplate, error)
	GetCustomerByUUID(ctx context.Context, arg GetCustomerByUUIDParams) (Customer, error)
	GetCustomerVehicleByUUID(ctx context.Context, arg GetCustomerVehicleByUUIDParams) (CustomerVehicle, error)
	GetCustomerVehicleDetailByUUID(ctx context.Context, arg GetCustomerVehicleDetailByUUIDParams) (GetCustomerVehicleDetailByUUIDRow, error)
	GetDailySummarySettings(ctx context.Context, organizationID int64) (DailySummarySetting, error)
	GetDiscountCodeByCode(ctx context.Context, code string) (BillingDiscountCode, error)
	GetDiscountCodeByUUID(ctx context.Context, argUuid uuid.UUID) (BillingDiscountCode, error)
	// Effective feature values and usage counters for platform/entitlements.
	// Plan values of the organization's live subscription plus the custom
	// override JSON (enterprise, F5). Missing rows mean "unlimited / enabled".
	GetEffectiveFeatures(ctx context.Context, organizationID int64) ([]GetEffectiveFeaturesRow, error)
	GetExportJobByID(ctx context.Context, id int64) (ExportJob, error)
	GetExportJobByUUID(ctx context.Context, argUuid uuid.UUID) (ExportJob, error)
	GetFinanceAccountByID(ctx context.Context, arg GetFinanceAccountByIDParams) (FinanceAccount, error)
	GetFinanceAccountByName(ctx context.Context, arg GetFinanceAccountByNameParams) (FinanceAccount, error)
	GetFinanceAccountByUUID(ctx context.Context, arg GetFinanceAccountByUUIDParams) (FinanceAccount, error)
	GetFinanceAccountForSearch(ctx context.Context, arg GetFinanceAccountForSearchParams) (GetFinanceAccountForSearchRow, error)
	GetFinanceAccountIDByUUIDForReport(ctx context.Context, arg GetFinanceAccountIDByUUIDForReportParams) (int64, error)
	GetFinanceAccountStats(ctx context.Context, arg GetFinanceAccountStatsParams) (GetFinanceAccountStatsRow, error)
	GetFinanceCategoryByName(ctx context.Context, arg GetFinanceCategoryByNameParams) (FinanceCategory, error)
	GetFinanceCategoryByUUID(ctx context.Context, arg GetFinanceCategoryByUUIDParams) (FinanceCategory, error)
	GetFinanceCategoryForSearch(ctx context.Context, arg GetFinanceCategoryForSearchParams) (GetFinanceCategoryForSearchRow, error)
	GetFinanceCategoryStats(ctx context.Context, arg GetFinanceCategoryStatsParams) (GetFinanceCategoryStatsRow, error)
	GetFinanceSourceCari(ctx context.Context, arg GetFinanceSourceCariParams) (GetFinanceSourceCariRow, error)
	// Source documents behind finance transactions (job payment, sale,
	// purchase, cari collection) for the transaction detail page.
	GetFinanceSourceJob(ctx context.Context, arg GetFinanceSourceJobParams) (GetFinanceSourceJobRow, error)
	GetFinanceSourcePurchase(ctx context.Context, arg GetFinanceSourcePurchaseParams) (GetFinanceSourcePurchaseRow, error)
	GetFinanceSourceSale(ctx context.Context, arg GetFinanceSourceSaleParams) (GetFinanceSourceSaleRow, error)
	GetFinanceTransactionBySource(ctx context.Context, arg GetFinanceTransactionBySourceParams) (FinanceTransaction, error)
	GetFinanceTransactionByUUID(ctx context.Context, arg GetFinanceTransactionByUUIDParams) (FinanceTransaction, error)
	GetFinanceTransactionForSearch(ctx context.Context, arg GetFinanceTransactionForSearchParams) (GetFinanceTransactionForSearchRow, error)
	GetGitHubAppSettings(ctx context.Context) (GithubAppSetting, error)
	GetImportJobByID(ctx context.Context, id int64) (ImportJob, error)
	GetImportJobByUUID(ctx context.Context, argUuid uuid.UUID) (ImportJob, error)
	GetInvoiceByOrder(ctx context.Context, orderID int64) (GetInvoiceByOrderRow, error)
	GetInvoiceByUUID(ctx context.Context, argUuid uuid.UUID) (GetInvoiceByUUIDRow, error)
	GetInvoiceByUUIDForOrg(ctx context.Context, arg GetInvoiceByUUIDForOrgParams) (GetInvoiceByUUIDForOrgRow, error)
	GetInvoiceProfile(ctx context.Context, id int64) (GetInvoiceProfileRow, error)
	GetJobConsumptionForUpdate(ctx context.Context, arg GetJobConsumptionForUpdateParams) (ServiceJobConsumption, error)
	GetJobOrgAndPhoneByUUID(ctx context.Context, argUuid uuid.UUID) (GetJobOrgAndPhoneByUUIDRow, error)
	GetLatestContractSignerOTP(ctx context.Context, signerID int64) (ContractSignerOtp, error)
	GetLeadDetail(ctx context.Context, arg GetLeadDetailParams) (GetLeadDetailRow, error)
	GetLeadRefByID(ctx context.Context, id int64) (GetLeadRefByIDRow, error)
	GetLeadRowByUUID(ctx context.Context, arg GetLeadRowByUUIDParams) (Lead, error)
	GetLeadRowByUUIDForUpdate(ctx context.Context, arg GetLeadRowByUUIDForUpdateParams) (Lead, error)
	GetLiveSubscription(ctx context.Context, organizationID int64) (GetLiveSubscriptionRow, error)
	GetLiveSubscriptionForUpdate(ctx context.Context, organizationID int64) (BillingSubscription, error)
	GetLogPurgeRuleByUUID(ctx context.Context, argUuid uuid.UUID) (LogPurgeRule, error)
	GetMessageTemplate(ctx context.Context, arg GetMessageTemplateParams) (MessageTemplate, error)
	GetMessageTemplateByKey(ctx context.Context, arg GetMessageTemplateByKeyParams) (MessageTemplate, error)
	GetMessageTemplateDefault(ctx context.Context, arg GetMessageTemplateDefaultParams) (MessageTemplateDefault, error)
	// Organization override regardless of is_active (passive = channel disabled).
	GetMessageTemplateOverride(ctx context.Context, arg GetMessageTemplateOverrideParams) (MessageTemplate, error)
	GetNotificationByID(ctx context.Context, id int64) (Notification, error)
	GetNotificationByUUID(ctx context.Context, argUuid uuid.UUID) (Notification, error)
	GetNotificationMemberSettings(ctx context.Context, arg GetNotificationMemberSettingsParams) (NotificationMemberSetting, error)
	GetNotificationOrganization(ctx context.Context, id int64) (GetNotificationOrganizationRow, error)
	GetNotificationPreferences(ctx context.Context, userID int64) (NotificationPreference, error)
	GetNotificationRecipientCustomer(ctx context.Context, arg GetNotificationRecipientCustomerParams) (GetNotificationRecipientCustomerRow, error)
	// A member of the organization (tenant isolation for user recipients).
	GetNotificationRecipientUser(ctx context.Context, arg GetNotificationRecipientUserParams) (GetNotificationRecipientUserRow, error)
	GetNotificationRule(ctx context.Context, arg GetNotificationRuleParams) (NotificationRule, error)
	GetNotificationTypePreference(ctx context.Context, arg GetNotificationTypePreferenceParams) (NotificationTypePreference, error)
	GetOAuthAccountByProviderAccount(ctx context.Context, arg GetOAuthAccountByProviderAccountParams) (GetOAuthAccountByProviderAccountRow, error)
	GetOAuthAccountByUserProvider(ctx context.Context, arg GetOAuthAccountByUserProviderParams) (GetOAuthAccountByUserProviderRow, error)
	GetOAuthProviderSettings(ctx context.Context, provider string) (OauthProviderSetting, error)
	GetOpenOrderForOrg(ctx context.Context, organizationID int64) (BillingOrder, error)
	GetOrderByUUID(ctx context.Context, argUuid uuid.UUID) (GetOrderByUUIDRow, error)
	GetOrderByUUIDForOrg(ctx context.Context, arg GetOrderByUUIDForOrgParams) (GetOrderByUUIDForOrgRow, error)
	GetOrderForInvoice(ctx context.Context, id int64) (GetOrderForInvoiceRow, error)
	GetOrderForUpdate(ctx context.Context, argUuid uuid.UUID) (BillingOrder, error)
	GetOrgCustomerRef(ctx context.Context, arg GetOrgCustomerRefParams) (GetOrgCustomerRefRow, error)
	GetOrgCustomerVehicleRef(ctx context.Context, arg GetOrgCustomerVehicleRefParams) (GetOrgCustomerVehicleRefRow, error)
	GetOrgLeadRef(ctx context.Context, arg GetOrgLeadRefParams) (GetOrgLeadRefRow, error)
	GetOrgMemberUser(ctx context.Context, arg GetOrgMemberUserParams) (GetOrgMemberUserRow, error)
	GetOrgProductRef(ctx context.Context, arg GetOrgProductRefParams) (GetOrgProductRefRow, error)
	GetOrgServiceRef(ctx context.Context, arg GetOrgServiceRefParams) (GetOrgServiceRefRow, error)
	GetOrganizationByID(ctx context.Context, id int64) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetOrganizationByUUID(ctx context.Context, argUuid uuid.UUID) (Organization, error)
	GetOrganizationMember(ctx context.Context, arg GetOrganizationMemberParams) (GetOrganizationMemberRow, error)
	GetOrganizationMemberByUserAndOrgUUID(ctx context.Context, arg GetOrganizationMemberByUserAndOrgUUIDParams) (GetOrganizationMemberByUserAndOrgUUIDRow, error)
	GetOrganizationMemberByUserAndSlug(ctx context.Context, arg GetOrganizationMemberByUserAndSlugParams) (GetOrganizationMemberByUserAndSlugRow, error)
	GetOrganizationMemberByUserUUID(ctx context.Context, arg GetOrganizationMemberByUserUUIDParams) (GetOrganizationMemberByUserUUIDRow, error)
	GetPermissionBySlug(ctx context.Context, slug string) (Permission, error)
	GetProductByBarcode(ctx context.Context, arg GetProductByBarcodeParams) (Product, error)
	GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error)
	GetProductByName(ctx context.Context, arg GetProductByNameParams) (Product, error)
	GetProductBySKU(ctx context.Context, arg GetProductBySKUParams) (Product, error)
	GetProductByUUID(ctx context.Context, arg GetProductByUUIDParams) (GetProductByUUIDRow, error)
	GetProductForSearch(ctx context.Context, arg GetProductForSearchParams) (GetProductForSearchRow, error)
	GetProductSaleByUUID(ctx context.Context, arg GetProductSaleByUUIDParams) (GetProductSaleByUUIDRow, error)
	GetProductSaleForSearch(ctx context.Context, arg GetProductSaleForSearchParams) (GetProductSaleForSearchRow, error)
	GetPurchaseByUUID(ctx context.Context, arg GetPurchaseByUUIDParams) (GetPurchaseByUUIDRow, error)
	GetPurchaseForSearch(ctx context.Context, arg GetPurchaseForSearchParams) (GetPurchaseForSearchRow, error)
	GetQuoteByShareToken(ctx context.Context, shareToken string) (Quote, error)
	GetQuoteByShareTokenForUpdate(ctx context.Context, shareToken string) (Quote, error)
	GetQuoteDeliveryByUUID(ctx context.Context, arg GetQuoteDeliveryByUUIDParams) (QuoteDelivery, error)
	// Team members related to a quote (creator, lead assignee) for internal notifications.
	GetQuoteNotifyPeople(ctx context.Context, arg GetQuoteNotifyPeopleParams) (GetQuoteNotifyPeopleRow, error)
	// Joined display fields for one quote (detail, PDF, public view).
	GetQuoteRefs(ctx context.Context, id int64) (GetQuoteRefsRow, error)
	GetQuoteReminderByID(ctx context.Context, arg GetQuoteReminderByIDParams) (QuoteReminder, error)
	GetQuoteReminderByUUID(ctx context.Context, argUuid uuid.UUID) (QuoteReminder, error)
	GetQuoteRowByID(ctx context.Context, id int64) (Quote, error)
	GetQuoteRowByUUID(ctx context.Context, arg GetQuoteRowByUUIDParams) (Quote, error)
	GetQuoteRowByUUIDForUpdate(ctx context.Context, arg GetQuoteRowByUUIDForUpdateParams) (Quote, error)
	GetRoleByID(ctx context.Context, id int64) (Role, error)
	GetRoleBySlug(ctx context.Context, slug string) (Role, error)
	GetRoleByUUID(ctx context.Context, argUuid uuid.UUID) (Role, error)
	GetSaleOrgAndPhoneByUUID(ctx context.Context, argUuid uuid.UUID) (GetSaleOrgAndPhoneByUUIDRow, error)
	GetScheduledNotificationByKey(ctx context.Context, arg GetScheduledNotificationByKeyParams) (ScheduledNotification, error)
	GetSellerSettings(ctx context.Context) (GetSellerSettingsRow, error)
	GetServiceByCode(ctx context.Context, arg GetServiceByCodeParams) (Service, error)
	GetServiceByID(ctx context.Context, arg GetServiceByIDParams) (Service, error)
	GetServiceByName(ctx context.Context, arg GetServiceByNameParams) (Service, error)
	GetServiceByUUID(ctx context.Context, arg GetServiceByUUIDParams) (GetServiceByUUIDRow, error)
	GetServiceForSearch(ctx context.Context, arg GetServiceForSearchParams) (GetServiceForSearchRow, error)
	GetServiceJobByID(ctx context.Context, arg GetServiceJobByIDParams) (ServiceJob, error)
	GetServiceJobByUUID(ctx context.Context, arg GetServiceJobByUUIDParams) (GetServiceJobByUUIDRow, error)
	GetServiceJobForSearch(ctx context.Context, arg GetServiceJobForSearchParams) (GetServiceJobForSearchRow, error)
	GetStepupSettings(ctx context.Context) (StepupSetting, error)
	GetStorageLinkBySlug(ctx context.Context, slug pgtype.Text) (StorageLink, error)
	GetStorageLinkByTokenHash(ctx context.Context, tokenHash pgtype.Text) (StorageLink, error)
	GetStorageLinkByUUID(ctx context.Context, argUuid uuid.UUID) (StorageLink, error)
	GetStorageTrashByOriginalKey(ctx context.Context, originalKey string) (StorageTrash, error)
	GetStorageTrashByUUID(ctx context.Context, argUuid uuid.UUID) (StorageTrash, error)
	GetSubscriptionByUUID(ctx context.Context, argUuid uuid.UUID) (GetSubscriptionByUUIDRow, error)
	GetSupplierByUUID(ctx context.Context, arg GetSupplierByUUIDParams) (Supplier, error)
	GetSupplierForSearch(ctx context.Context, arg GetSupplierForSearchParams) (GetSupplierForSearchRow, error)
	GetTemplateByCodeChannelLang(ctx context.Context, arg GetTemplateByCodeChannelLangParams) (NotificationTemplate, error)
	GetTodoAssigneeByUUID(ctx context.Context, arg GetTodoAssigneeByUUIDParams) (GetTodoAssigneeByUUIDRow, error)
	GetTodoByUUID(ctx context.Context, arg GetTodoByUUIDParams) (GetTodoByUUIDRow, error)
	GetTodoCustomerRef(ctx context.Context, arg GetTodoCustomerRefParams) (GetTodoCustomerRefRow, error)
	GetTodoJobRef(ctx context.Context, arg GetTodoJobRefParams) (GetTodoJobRefRow, error)
	GetTodoReminderState(ctx context.Context, arg GetTodoReminderStateParams) (string, error)
	GetTodoRowByID(ctx context.Context, arg GetTodoRowByIDParams) (Todo, error)
	GetUsageCounter(ctx context.Context, arg GetUsageCounterParams) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error)
	GetUserTOTPByUserID(ctx context.Context, userID int64) (UserTotp, error)
	GetValidRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetVehicleAlertJob(ctx context.Context, argUuid uuid.UUID) (GetVehicleAlertJobRow, error)
	GetVehicleAlertSettings(ctx context.Context, organizationID int64) (VehicleAlertSetting, error)
	GetVehicleBrandByName(ctx context.Context, lower string) (VehicleBrand, error)
	GetVehicleBrandByUUID(ctx context.Context, argUuid uuid.UUID) (VehicleBrand, error)
	GetVehicleCatalogOption(ctx context.Context, arg GetVehicleCatalogOptionParams) (GetVehicleCatalogOptionRow, error)
	GetVehicleModelByBrandAndName(ctx context.Context, arg GetVehicleModelByBrandAndNameParams) (VehicleModel, error)
	GetVehicleModelByUUID(ctx context.Context, argUuid uuid.UUID) (VehicleModel, error)
	GetVehicleModelRef(ctx context.Context, argUuid uuid.UUID) (GetVehicleModelRefRow, error)
	GetVehicleModelYearForSearch(ctx context.Context, arg GetVehicleModelYearForSearchParams) (GetVehicleModelYearForSearchRow, error)
	GetWebAuthnCredentialByCredentialID(ctx context.Context, credentialID string) (WebauthnCredential, error)
	GetWebAuthnCredentialByUUID(ctx context.Context, arg GetWebAuthnCredentialByUUIDParams) (WebauthnCredential, error)
	GetWhatsAppSession(ctx context.Context, organizationID int64) (WhatsappSession, error)
	IncrementContractSignerOTPAttempts(ctx context.Context, id int64) (ContractSignerOtp, error)
	IncrementOTPAttempts(ctx context.Context, id int64) (OtpCode, error)
	IncrementQuoteViews(ctx context.Context, id int64) error
	InsertAIMessage(ctx context.Context, arg InsertAIMessageParams) (AiMessage, error)
	InsertAIPendingAction(ctx context.Context, arg InsertAIPendingActionParams) (AiPendingAction, error)
	InsertAIUsage(ctx context.Context, arg InsertAIUsageParams) error
	InsertActivityEvent(ctx context.Context, arg InsertActivityEventParams) (ActivityEvent, error)
	InsertAppLog(ctx context.Context, arg InsertAppLogParams) error
	InsertBulkChange(ctx context.Context, arg InsertBulkChangeParams) (BulkChange, error)
	InsertDiscountUse(ctx context.Context, arg InsertDiscountUseParams) error
	InsertImportChange(ctx context.Context, arg InsertImportChangeParams) (ImportChange, error)
	InsertNotificationHistory(ctx context.Context, arg InsertNotificationHistoryParams) (NotificationHistory, error)
	InsertOutboundMessage(ctx context.Context, arg InsertOutboundMessageParams) (OutboundMessage, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error)
	InsertPlanFeature(ctx context.Context, arg InsertPlanFeatureParams) error
	InsertQueuedOutboundMessage(ctx context.Context, arg InsertQueuedOutboundMessageParams) (OutboundMessage, error)
	InsertReminderLog(ctx context.Context, arg InsertReminderLogParams) (int64, error)
	InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error
	// Inserts a notification slot. A conflicting cancelled row is revived (a
	// reschedule back to the same slot); any other conflict returns no row, which
	// the caller treats as a duplicate.
	InsertScheduledNotification(ctx context.Context, arg InsertScheduledNotificationParams) (ScheduledNotification, error)
	InsertServiceProduct(ctx context.Context, arg InsertServiceProductParams) error
	InsertStorageActivity(ctx context.Context, arg InsertStorageActivityParams) (StorageActivity, error)
	InsertStorageLink(ctx context.Context, arg InsertStorageLinkParams) (StorageLink, error)
	InsertStorageShare(ctx context.Context, arg InsertStorageShareParams) (StorageShare, error)
	InsertStorageStar(ctx context.Context, arg InsertStorageStarParams) (StorageStar, error)
	InsertStorageTrash(ctx context.Context, arg InsertStorageTrashParams) (StorageTrash, error)
	InsertUserRole(ctx context.Context, arg InsertUserRoleParams) error
	InsertVehicleAlertEvent(ctx context.Context, arg InsertVehicleAlertEventParams) error
	InvalidateActiveOTPs(ctx context.Context, arg InvalidateActiveOTPsParams) error
	LeadSummary(ctx context.Context, arg LeadSummaryParams) (LeadSummaryRow, error)
	LinkCariEntryFinanceTransaction(ctx context.Context, arg LinkCariEntryFinanceTransactionParams) (CariEntry, error)
	LinkProductSaleCari(ctx context.Context, arg LinkProductSaleCariParams) (ProductSale, error)
	LinkProductSaleFinance(ctx context.Context, arg LinkProductSaleFinanceParams) (ProductSale, error)
	LinkPurchaseFinance(ctx context.Context, arg LinkPurchaseFinanceParams) (Purchase, error)
	LinkQuoteJob(ctx context.Context, arg LinkQuoteJobParams) (Quote, error)
	LinkServiceJobPaymentCari(ctx context.Context, arg LinkServiceJobPaymentCariParams) (ServiceJobPayment, error)
	LinkServiceJobPaymentFinance(ctx context.Context, arg LinkServiceJobPaymentFinanceParams) (ServiceJobPayment, error)
	ListAIConversations(ctx context.Context, arg ListAIConversationsParams) ([]AiConversation, error)
	ListAIMessages(ctx context.Context, conversationID int64) ([]AiMessage, error)
	ListAIOrganizationSettingsByOrgIDs(ctx context.Context, organizationUuids []uuid.UUID) ([]ListAIOrganizationSettingsByOrgIDsRow, error)
	ListAIUsageByOrganization(ctx context.Context, arg ListAIUsageByOrganizationParams) ([]ListAIUsageByOrganizationRow, error)
	ListActivePublicKeys(ctx context.Context, keys []string) ([]string, error)
	ListActivePublicLinks(ctx context.Context) ([]StorageLink, error)
	ListActiveRefreshTokensByUserID(ctx context.Context, userID int64) ([]RefreshToken, error)
	ListActivityEvents(ctx context.Context, arg ListActivityEventsParams) ([]ActivityEvent, error)
	ListAllBulkJobs(ctx context.Context, arg ListAllBulkJobsParams) ([]BulkJob, error)
	ListAllExportJobs(ctx context.Context, arg ListAllExportJobsParams) ([]ExportJob, error)
	ListAllImportJobs(ctx context.Context, arg ListAllImportJobsParams) ([]ImportJob, error)
	ListAllPermissionSlugs(ctx context.Context) ([]string, error)
	ListAppLogSources(ctx context.Context) ([]string, error)
	ListAppLogs(ctx context.Context, arg ListAppLogsParams) ([]AppLog, error)
	// Plans, feature catalog and subscriptions (spec §3).
	ListBillingFeatures(ctx context.Context, includeInactive bool) ([]BillingFeature, error)
	ListBillingPlanUUIDsByIDs(ctx context.Context, ids []int64) ([]ListBillingPlanUUIDsByIDsRow, error)
	ListBillingPlans(ctx context.Context, publicOnly bool) ([]BillingPlan, error)
	ListBulkChangesForJob(ctx context.Context, jobID int64) ([]BulkChange, error)
	ListBulkJobsForActor(ctx context.Context, arg ListBulkJobsForActorParams) ([]BulkJob, error)
	ListCariAccounts(ctx context.Context, arg ListCariAccountsParams) ([]ListCariAccountsRow, error)
	ListCariAccountsForExport(ctx context.Context, arg ListCariAccountsForExportParams) ([]ListCariAccountsForExportRow, error)
	ListCariAccountsForSearch(ctx context.Context) ([]ListCariAccountsForSearchRow, error)
	ListCariEntries(ctx context.Context, arg ListCariEntriesParams) ([]ListCariEntriesRow, error)
	ListCariEntriesForExport(ctx context.Context, arg ListCariEntriesForExportParams) ([]ListCariEntriesForExportRow, error)
	ListCatalogCategories(ctx context.Context, arg ListCatalogCategoriesParams) ([]ListCatalogCategoriesRow, error)
	ListConnectedWhatsAppSessions(ctx context.Context) ([]WhatsappSession, error)
	ListContractInstances(ctx context.Context, arg ListContractInstancesParams) ([]ContractInstance, error)
	ListContractMediaByInstance(ctx context.Context, instanceID int64) ([]ContractMedium, error)
	ListContractPresets(ctx context.Context, arg ListContractPresetsParams) ([]ContractPreset, error)
	ListContractSignaturesByInstance(ctx context.Context, instanceID int64) ([]ContractSignature, error)
	ListContractSignersByInstance(ctx context.Context, instanceID int64) ([]ContractSigner, error)
	ListContractTemplates(ctx context.Context, arg ListContractTemplatesParams) ([]ContractTemplate, error)
	ListCustomerVehicles(ctx context.Context, arg ListCustomerVehiclesParams) ([]ListCustomerVehiclesRow, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error)
	// Active organization members with their notification phone (may be empty).
	ListDailySummaryMembers(ctx context.Context, organizationID int64) ([]ListDailySummaryMembersRow, error)
	ListDiscountCodes(ctx context.Context, arg ListDiscountCodesParams) ([]ListDiscountCodesRow, error)
	ListEnabledDailySummarySettings(ctx context.Context) ([]DailySummarySetting, error)
	ListEnabledLogPurgeRules(ctx context.Context) ([]LogPurgeRule, error)
	ListExportJobsForActor(ctx context.Context, arg ListExportJobsForActorParams) ([]ExportJob, error)
	ListExportJobsForOrganization(ctx context.Context, arg ListExportJobsForOrganizationParams) ([]ExportJob, error)
	ListFinanceAccounts(ctx context.Context, arg ListFinanceAccountsParams) ([]FinanceAccount, error)
	ListFinanceAccountsForExport(ctx context.Context, arg ListFinanceAccountsForExportParams) ([]FinanceAccount, error)
	ListFinanceAccountsForSearch(ctx context.Context) ([]ListFinanceAccountsForSearchRow, error)
	ListFinanceCategories(ctx context.Context, arg ListFinanceCategoriesParams) ([]FinanceCategory, error)
	ListFinanceCategoriesForSearch(ctx context.Context) ([]ListFinanceCategoriesForSearchRow, error)
	ListFinanceSourceJobLines(ctx context.Context, arg ListFinanceSourceJobLinesParams) ([]ListFinanceSourceJobLinesRow, error)
	ListFinanceSourcePurchaseLines(ctx context.Context, arg ListFinanceSourcePurchaseLinesParams) ([]ListFinanceSourcePurchaseLinesRow, error)
	ListFinanceSourceSaleLines(ctx context.Context, arg ListFinanceSourceSaleLinesParams) ([]ListFinanceSourceSaleLinesRow, error)
	ListFinanceTransactions(ctx context.Context, arg ListFinanceTransactionsParams) ([]ListFinanceTransactionsRow, error)
	ListFinanceTransactionsForExport(ctx context.Context, arg ListFinanceTransactionsForExportParams) ([]ListFinanceTransactionsForExportRow, error)
	ListFinanceTransactionsForSearch(ctx context.Context) ([]ListFinanceTransactionsForSearchRow, error)
	ListImportChangesForJob(ctx context.Context, jobID int64) ([]ImportChange, error)
	ListImportJobsForActor(ctx context.Context, arg ListImportJobsForActorParams) ([]ImportJob, error)
	ListImportJobsForOrganization(ctx context.Context, arg ListImportJobsForOrganizationParams) ([]ImportJob, error)
	ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]ListInvoicesRow, error)
	ListInvoicesForOrg(ctx context.Context, arg ListInvoicesForOrgParams) ([]ListInvoicesForOrgRow, error)
	ListInvoicesForOrgAdmin(ctx context.Context, organizationID int64) ([]ListInvoicesForOrgAdminRow, error)
	ListJobConsumptions(ctx context.Context, arg ListJobConsumptionsParams) ([]ListJobConsumptionsRow, error)
	ListLeadEvents(ctx context.Context, arg ListLeadEventsParams) ([]ListLeadEventsRow, error)
	ListLeadQuotes(ctx context.Context, arg ListLeadQuotesParams) ([]ListLeadQuotesRow, error)
	ListLeads(ctx context.Context, arg ListLeadsParams) ([]ListLeadsRow, error)
	ListLogPurgeRules(ctx context.Context) ([]LogPurgeRule, error)
	ListMessageTemplateDefaults(ctx context.Context) ([]MessageTemplateDefault, error)
	ListMessageTemplatesByOrg(ctx context.Context, organizationID int64) ([]MessageTemplate, error)
	ListNotificationRulesByOrg(ctx context.Context, organizationID int64) ([]NotificationRule, error)
	ListNotificationTypePreferences(ctx context.Context, arg ListNotificationTypePreferencesParams) ([]NotificationTypePreference, error)
	ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error)
	ListOAuthAccountsByUserID(ctx context.Context, userID int64) ([]ListOAuthAccountsByUserIDRow, error)
	ListOAuthAccountsForUserIDs(ctx context.Context, userIds []int64) ([]ListOAuthAccountsForUserIDsRow, error)
	ListOAuthProviderSettings(ctx context.Context) ([]OauthProviderSetting, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error)
	ListOrdersExpiringWithin(ctx context.Context, arg ListOrdersExpiringWithinParams) ([]ListOrdersExpiringWithinRow, error)
	ListOrdersForOrg(ctx context.Context, arg ListOrdersForOrgParams) ([]ListOrdersForOrgRow, error)
	ListOrdersForOrgAdmin(ctx context.Context, organizationID int64) ([]ListOrdersForOrgAdminRow, error)
	ListOrgMemberOptions(ctx context.Context, organizationID int64) ([]ListOrgMemberOptionsRow, error)
	ListOrganizationIDs(ctx context.Context) ([]int64, error)
	ListOrganizationMemberOptions(ctx context.Context, organizationID int64) ([]ListOrganizationMemberOptionsRow, error)
	ListOrganizationMembers(ctx context.Context, organizationID int64) ([]ListOrganizationMembersRow, error)
	ListOrganizationMembersByUserID(ctx context.Context, userID int64) ([]ListOrganizationMembersByUserIDRow, error)
	ListOrganizationsFiltered(ctx context.Context, arg ListOrganizationsFilteredParams) ([]Organization, error)
	ListOrgsWithPendingVehicleAlerts(ctx context.Context) ([]VehicleAlertSetting, error)
	// Pending reminder fire times for a page of subjects (no N+1 in lists).
	ListPendingRemindersForSubjects(ctx context.Context, arg ListPendingRemindersForSubjectsParams) ([]ListPendingRemindersForSubjectsRow, error)
	ListPendingVehicleAlertEvents(ctx context.Context, arg ListPendingVehicleAlertEventsParams) ([]VehicleAlertEvent, error)
	ListPermissionSlugsByRoleID(ctx context.Context, roleID int64) ([]string, error)
	ListPermissionSlugsByRoleSlug(ctx context.Context, slug string) ([]string, error)
	ListPermissionsFiltered(ctx context.Context, arg ListPermissionsFilteredParams) ([]Permission, error)
	ListPlanFeatures(ctx context.Context, planID int64) ([]ListPlanFeaturesRow, error)
	ListPlatformNotifications(ctx context.Context, arg ListPlatformNotificationsParams) ([]Notification, error)
	ListPlatformNotificationsForExport(ctx context.Context, arg ListPlatformNotificationsForExportParams) ([]Notification, error)
	ListProductSaleLines(ctx context.Context, arg ListProductSaleLinesParams) ([]ListProductSaleLinesRow, error)
	ListProductSales(ctx context.Context, arg ListProductSalesParams) ([]ListProductSalesRow, error)
	ListProductSalesForExport(ctx context.Context, arg ListProductSalesForExportParams) ([]ProductSale, error)
	ListProductSalesForSearch(ctx context.Context) ([]ListProductSalesForSearchRow, error)
	ListProductUUIDsForBulk(ctx context.Context, arg ListProductUUIDsForBulkParams) ([]uuid.UUID, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	ListProductsForExport(ctx context.Context, arg ListProductsForExportParams) ([]ListProductsForExportRow, error)
	// ============================================================================
	// Catalog Search Queries
	// ============================================================================
	ListProductsForSearch(ctx context.Context) ([]ListProductsForSearchRow, error)
	ListPurchaseLines(ctx context.Context, arg ListPurchaseLinesParams) ([]ListPurchaseLinesRow, error)
	ListPurchaseLinesByPurchaseIDs(ctx context.Context, arg ListPurchaseLinesByPurchaseIDsParams) ([]ListPurchaseLinesByPurchaseIDsRow, error)
	ListPurchases(ctx context.Context, arg ListPurchasesParams) ([]ListPurchasesRow, error)
	ListPurchasesForExport(ctx context.Context, arg ListPurchasesForExportParams) ([]Purchase, error)
	ListPurchasesForSearch(ctx context.Context) ([]ListPurchasesForSearchRow, error)
	ListPushSubscriptionsByUser(ctx context.Context, userID int64) ([]PushSubscription, error)
	// Who hears about a customer's accept / reject: the quote's creator, the
	// lead assignee and the business owners (members only, de-duplicated).
	ListQuoteDecisionRecipients(ctx context.Context, arg ListQuoteDecisionRecipientsParams) ([]int64, error)
	ListQuoteDeliveries(ctx context.Context, quoteID int64) ([]QuoteDelivery, error)
	ListQuoteEvents(ctx context.Context, quoteID int64) ([]ListQuoteEventsRow, error)
	ListQuoteLines(ctx context.Context, quoteID int64) ([]ListQuoteLinesRow, error)
	ListQuoteReminders(ctx context.Context, quoteID int64) ([]QuoteReminder, error)
	ListQuotes(ctx context.Context, arg ListQuotesParams) ([]ListQuotesRow, error)
	ListRecentFinanceTransactionsByAccount(ctx context.Context, arg ListRecentFinanceTransactionsByAccountParams) ([]ListRecentFinanceTransactionsByAccountRow, error)
	ListRecipesForServices(ctx context.Context, arg ListRecipesForServicesParams) ([]ListRecipesForServicesRow, error)
	ListRolePermissionSlugsByRoleUUID(ctx context.Context, argUuid uuid.UUID) ([]string, error)
	ListRoleUUIDsForBulk(ctx context.Context, q_ pgtype.Text) ([]uuid.UUID, error)
	ListRolesFiltered(ctx context.Context, arg ListRolesFilteredParams) ([]Role, error)
	ListRolesForExport(ctx context.Context, q_ pgtype.Text) ([]Role, error)
	ListRolesForUserIDs(ctx context.Context, userIds []int64) ([]ListRolesForUserIDsRow, error)
	ListScheduledNotificationsBySubject(ctx context.Context, arg ListScheduledNotificationsBySubjectParams) ([]ScheduledNotification, error)
	ListServiceJobLines(ctx context.Context, arg ListServiceJobLinesParams) ([]ListServiceJobLinesRow, error)
	ListServiceJobPayments(ctx context.Context, arg ListServiceJobPaymentsParams) ([]ListServiceJobPaymentsRow, error)
	// Service lines of the listed jobs, for the coloured tags on board cards.
	ListServiceJobServiceTags(ctx context.Context, arg ListServiceJobServiceTagsParams) ([]ListServiceJobServiceTagsRow, error)
	ListServiceJobs(ctx context.Context, arg ListServiceJobsParams) ([]ListServiceJobsRow, error)
	ListServiceJobsByCustomer(ctx context.Context, arg ListServiceJobsByCustomerParams) ([]ListServiceJobsByCustomerRow, error)
	ListServiceJobsForExport(ctx context.Context, arg ListServiceJobsForExportParams) ([]ListServiceJobsForExportRow, error)
	ListServiceJobsForSearch(ctx context.Context) ([]ListServiceJobsForSearchRow, error)
	// Service recipes (products a service uses) and per-job product usage.
	ListServiceProducts(ctx context.Context, arg ListServiceProductsParams) ([]ListServiceProductsRow, error)
	ListServiceUUIDsForBulk(ctx context.Context, arg ListServiceUUIDsForBulkParams) ([]uuid.UUID, error)
	ListServices(ctx context.Context, arg ListServicesParams) ([]ListServicesRow, error)
	ListServicesForExport(ctx context.Context, arg ListServicesForExportParams) ([]ListServicesForExportRow, error)
	ListServicesForSearch(ctx context.Context) ([]ListServicesForSearchRow, error)
	ListSharedKeys(ctx context.Context, keys []string) ([]string, error)
	ListStorageActivity(ctx context.Context, arg ListStorageActivityParams) ([]ListStorageActivityRow, error)
	ListStorageLinksByKey(ctx context.Context, objectKey string) ([]StorageLink, error)
	ListStorageSharesByKey(ctx context.Context, objectKey string) ([]ListStorageSharesByKeyRow, error)
	ListStorageSharesForUser(ctx context.Context, userID int64) ([]StorageShare, error)
	ListStorageStarsByKeys(ctx context.Context, arg ListStorageStarsByKeysParams) ([]StorageStar, error)
	ListStorageStarsByUser(ctx context.Context, userID int64) ([]StorageStar, error)
	ListStorageTrash(ctx context.Context, arg ListStorageTrashParams) ([]StorageTrash, error)
	ListStuckProcessingNotificationIDs(ctx context.Context, staleMinutes int32) ([]int64, error)
	ListSubscriptionHistoryForOrg(ctx context.Context, organizationID int64) ([]ListSubscriptionHistoryForOrgRow, error)
	ListSubscriptionsAdmin(ctx context.Context, arg ListSubscriptionsAdminParams) ([]ListSubscriptionsAdminRow, error)
	ListSubscriptionsEndingOn(ctx context.Context, arg ListSubscriptionsEndingOnParams) ([]ListSubscriptionsEndingOnRow, error)
	// Billing lifecycle transitions, reminder idempotency and dashboard queries.
	ListSubscriptionsToGrace(ctx context.Context, nowAt pgtype.Timestamptz) ([]ListSubscriptionsToGraceRow, error)
	ListSubscriptionsToReadOnly(ctx context.Context, nowAt pgtype.Timestamptz) ([]ListSubscriptionsToReadOnlyRow, error)
	ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error)
	ListSuppliersForExport(ctx context.Context, arg ListSuppliersForExportParams) ([]Supplier, error)
	ListSuppliersForSearch(ctx context.Context) ([]ListSuppliersForSearchRow, error)
	ListTodoAssignees(ctx context.Context, organizationID int64) ([]ListTodoAssigneesRow, error)
	// scope: overdue | today | upcoming | no_date | open_due (overdue + today); today is the local date.
	ListTodos(ctx context.Context, arg ListTodosParams) ([]ListTodosRow, error)
	ListUsageCounters(ctx context.Context, arg ListUsageCountersParams) ([]ListUsageCountersRow, error)
	ListUsageMetersForOrgAdmin(ctx context.Context, organizationID int64) ([]ListUsageMetersForOrgAdminRow, error)
	ListUserRoleSlugs(ctx context.Context, userID int64) ([]string, error)
	ListUserRolesByUserID(ctx context.Context, userID int64) ([]Role, error)
	ListUserRolesByUserUUID(ctx context.Context, argUuid uuid.UUID) ([]Role, error)
	ListUserUUIDsForBulk(ctx context.Context, arg ListUserUUIDsForBulkParams) ([]uuid.UUID, error)
	ListUsersFiltered(ctx context.Context, arg ListUsersFilteredParams) ([]User, error)
	ListUsersForExport(ctx context.Context, arg ListUsersForExportParams) ([]User, error)
	// Active members with notification phone and whether web push reaches them.
	ListVehicleAlertMembers(ctx context.Context, organizationID int64) ([]ListVehicleAlertMembersRow, error)
	ListVehicleAlertServices(ctx context.Context, organizationID int64) ([]ListVehicleAlertServicesRow, error)
	ListVehicleBrands(ctx context.Context, arg ListVehicleBrandsParams) ([]ListVehicleBrandsRow, error)
	ListVehicleModelYearIDsByBrand(ctx context.Context, argUuid uuid.UUID) ([]ListVehicleModelYearIDsByBrandRow, error)
	ListVehicleModelYearIDsByModel(ctx context.Context, argUuid uuid.UUID) ([]ListVehicleModelYearIDsByModelRow, error)
	ListVehicleModelYears(ctx context.Context, modelID int64) ([]int16, error)
	ListVehicleModelYearsForSearch(ctx context.Context) ([]ListVehicleModelYearsForSearchRow, error)
	ListVehicleModelsByBrand(ctx context.Context, brandID int64) ([]VehicleModel, error)
	ListWebAuthnCredentialsByUserID(ctx context.Context, userID int64) ([]WebauthnCredential, error)
	ListWebAuthnCredentialsForUserIDs(ctx context.Context, userIds []int64) ([]WebauthnCredential, error)
	MarkAllNotificationsReadForUser(ctx context.Context, userID pgtype.Int8) (int64, error)
	MarkBulkJobCompleted(ctx context.Context, arg MarkBulkJobCompletedParams) (BulkJob, error)
	MarkBulkJobFailed(ctx context.Context, arg MarkBulkJobFailedParams) (BulkJob, error)
	MarkBulkJobProcessing(ctx context.Context, id int64) (BulkJob, error)
	MarkBulkJobRolledBack(ctx context.Context, arg MarkBulkJobRolledBackParams) (BulkJob, error)
	MarkContractSignerOTPVerified(ctx context.Context, arg MarkContractSignerOTPVerifiedParams) (ContractSigner, error)
	MarkContractSignerOTPVerifiedAt(ctx context.Context, arg MarkContractSignerOTPVerifiedAtParams) error
	MarkContractSignerSigned(ctx context.Context, id int64) (ContractSigner, error)
	MarkExportJobCompleted(ctx context.Context, arg MarkExportJobCompletedParams) (ExportJob, error)
	MarkExportJobFailed(ctx context.Context, arg MarkExportJobFailedParams) (ExportJob, error)
	MarkExportJobProcessing(ctx context.Context, id int64) (ExportJob, error)
	MarkImportJobApplied(ctx context.Context, arg MarkImportJobAppliedParams) (ImportJob, error)
	MarkImportJobApplying(ctx context.Context, id int64) (ImportJob, error)
	MarkImportJobFailed(ctx context.Context, arg MarkImportJobFailedParams) (ImportJob, error)
	MarkImportJobRolledBack(ctx context.Context, id int64) (ImportJob, error)
	MarkLogPurgeRuleRun(ctx context.Context, arg MarkLogPurgeRuleRunParams) (LogPurgeRule, error)
	MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) (Notification, error)
	MarkNotificationProcessing(ctx context.Context, id int64) (Notification, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error)
	// Cast status on every use. Reusing an untyped param as both VARCHAR assignment
	// and IN ('delivered', 'read') makes Postgres raise 42P08
	// (inconsistent types deduced for parameter $2).
	MarkNotificationSent(ctx context.Context, arg MarkNotificationSentParams) (Notification, error)
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error
	MarkOutboxPublished(ctx context.Context, id int64) error
	MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) error
	MarkScheduledNotificationCancelled(ctx context.Context, arg MarkScheduledNotificationCancelledParams) (ScheduledNotification, error)
	// Back to pending with backoff, or failed once max_attempts is reached.
	MarkScheduledNotificationRetry(ctx context.Context, arg MarkScheduledNotificationRetryParams) (ScheduledNotification, error)
	MarkScheduledNotificationSent(ctx context.Context, arg MarkScheduledNotificationSentParams) (ScheduledNotification, error)
	MarkServiceJobCancelled(ctx context.Context, arg MarkServiceJobCancelledParams) (ServiceJob, error)
	MarkServiceJobDelivered(ctx context.Context, arg MarkServiceJobDeliveredParams) (ServiceJob, error)
	MarkServiceJobDone(ctx context.Context, arg MarkServiceJobDoneParams) (ServiceJob, error)
	MarkServiceJobPaid(ctx context.Context, arg MarkServiceJobPaidParams) (ServiceJob, error)
	MarkServiceJobVoided(ctx context.Context, arg MarkServiceJobVoidedParams) (ServiceJob, error)
	MarkVehicleAlertEventsSent(ctx context.Context, arg MarkVehicleAlertEventsSentParams) error
	MoveToGrace(ctx context.Context, arg MoveToGraceParams) (BillingSubscription, error)
	MoveToReadOnly(ctx context.Context, id int64) (BillingSubscription, error)
	NextContractInstanceNumber(ctx context.Context, organizationID int64) (int32, error)
	// Billing invoices, invoice profiles and seller/XSLT settings.
	// Single atomic upsert: row lock on conflict serialises concurrent callers.
	NextInvoiceNumber(ctx context.Context, arg NextInvoiceNumberParams) (int64, error)
	// Tenant quotes (teklifler). Tenant queries are scoped by organization_id;
	// public queries look up by the unguessable share_token only.
	NextQuoteNumber(ctx context.Context, arg NextQuoteNumberParams) (int32, error)
	OrderStatusSummary(ctx context.Context) (OrderStatusSummaryRow, error)
	PingDB(ctx context.Context) (int32, error)
	QueueImportJob(ctx context.Context, argUuid uuid.UUID) (ImportJob, error)
	QuoteSummary(ctx context.Context, arg QuoteSummaryParams) (QuoteSummaryRow, error)
	ReferenceCodeExists(ctx context.Context, referenceCode string) (bool, error)
	ReleaseStuckScheduledNotifications(ctx context.Context, staleBefore pgtype.Timestamptz) (int64, error)
	RemoveUserRoleBySlug(ctx context.Context, arg RemoveUserRoleBySlugParams) error
	ReplaceUserRoles(ctx context.Context, userID int64) error
	ReportCariOutstanding(ctx context.Context, arg ReportCariOutstandingParams) ([]ReportCariOutstandingRow, error)
	ReportCariPeriodTotals(ctx context.Context, arg ReportCariPeriodTotalsParams) (ReportCariPeriodTotalsRow, error)
	ReportExpensesByCategory(ctx context.Context, arg ReportExpensesByCategoryParams) ([]ReportExpensesByCategoryRow, error)
	ReportFinanceBySource(ctx context.Context, arg ReportFinanceBySourceParams) ([]ReportFinanceBySourceRow, error)
	ReportFinanceTimeseries(ctx context.Context, arg ReportFinanceTimeseriesParams) ([]ReportFinanceTimeseriesRow, error)
	// Tenant operational / financial reports (read-only aggregates).
	ReportFinanceTotals(ctx context.Context, arg ReportFinanceTotalsParams) (ReportFinanceTotalsRow, error)
	ReportIncomeByCategory(ctx context.Context, arg ReportIncomeByCategoryParams) ([]ReportIncomeByCategoryRow, error)
	ReportJobPaymentsByMethod(ctx context.Context, arg ReportJobPaymentsByMethodParams) ([]ReportJobPaymentsByMethodRow, error)
	ReportJobStats(ctx context.Context, arg ReportJobStatsParams) (ReportJobStatsRow, error)
	ReportJobsTimeseries(ctx context.Context, arg ReportJobsTimeseriesParams) ([]ReportJobsTimeseriesRow, error)
	ReportOrder(ctx context.Context, arg ReportOrderParams) (BillingOrder, error)
	ReportProductSaleStats(ctx context.Context, arg ReportProductSaleStatsParams) (ReportProductSaleStatsRow, error)
	ReportProductSalesByMethod(ctx context.Context, arg ReportProductSalesByMethodParams) ([]ReportProductSalesByMethodRow, error)
	ReportProductsDistribution(ctx context.Context, arg ReportProductsDistributionParams) ([]ReportProductsDistributionRow, error)
	ReportPurchaseStats(ctx context.Context, arg ReportPurchaseStatsParams) (ReportPurchaseStatsRow, error)
	ReportServicesDistribution(ctx context.Context, arg ReportServicesDistributionParams) ([]ReportServicesDistributionRow, error)
	ReportTopCustomers(ctx context.Context, arg ReportTopCustomersParams) ([]ReportTopCustomersRow, error)
	// Todo ↔ lead / quote links (todos LinkResolver). Every query is org-scoped.
	ResolveTodoLeadLink(ctx context.Context, arg ResolveTodoLeadLinkParams) (int64, error)
	ResolveTodoQuoteLink(ctx context.Context, arg ResolveTodoQuoteLinkParams) (int64, error)
	RestoreProduct(ctx context.Context, arg RestoreProductParams) error
	RestoreService(ctx context.Context, arg RestoreServiceParams) error
	// Marks the job's usage as given back; returns the rows whose stock must be restored.
	RevertJobConsumptions(ctx context.Context, arg RevertJobConsumptionsParams) ([]RevertJobConsumptionsRow, error)
	RevokeAllRefreshTokensForUser(ctx context.Context, userID int64) error
	RevokeOtherRefreshTokensForUser(ctx context.Context, arg RevokeOtherRefreshTokensForUserParams) error
	RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) (int64, error)
	RevokeRefreshTokenByUUIDForUser(ctx context.Context, arg RevokeRefreshTokenByUUIDForUserParams) (int64, error)
	RevokeStorageLink(ctx context.Context, argUuid uuid.UUID) (StorageLink, error)
	SearchVehicleCatalogOptions(ctx context.Context, arg SearchVehicleCatalogOptionsParams) ([]SearchVehicleCatalogOptionsRow, error)
	SetAppSettingsLogo(ctx context.Context, logoObjectKey pgtype.Text) (AppSetting, error)
	SetContractInstancePDFError(ctx context.Context, arg SetContractInstancePDFErrorParams) error
	SetInvoiceStatus(ctx context.Context, arg SetInvoiceStatusParams) (BillingInvoice, error)
	// Used by the quotes module (quoted / won). Never reopens a closed lead
	// except to mark it won.
	SetLeadStatusByID(ctx context.Context, arg SetLeadStatusByIDParams) (SetLeadStatusByIDRow, error)
	SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) (BillingOrder, error)
	SetOrganizationAccess(ctx context.Context, arg SetOrganizationAccessParams) error
	SetOrganizationLogo(ctx context.Context, arg SetOrganizationLogoParams) (Organization, error)
	SetQuotePDF(ctx context.Context, arg SetQuotePDFParams) error
	SetQuoteReminderScheduled(ctx context.Context, arg SetQuoteReminderScheduledParams) error
	// Guarded transition: only applies when the row is still in from_status.
	SetQuoteStatus(ctx context.Context, arg SetQuoteStatusParams) (Quote, error)
	SetRolePermissions(ctx context.Context, roleID int64) error
	SetSubscriptionCredit(ctx context.Context, arg SetSubscriptionCreditParams) error
	SetTodoStatus(ctx context.Context, arg SetTodoStatusParams) (Todo, error)
	SetUsageCounter(ctx context.Context, arg SetUsageCounterParams) error
	SetUserEmailVerified(ctx context.Context, id int64) (User, error)
	SetXSLT(ctx context.Context, arg SetXSLTParams) (SetXSLTRow, error)
	SlugExists(ctx context.Context, slug string) (bool, error)
	SoftDeleteAIConversation(ctx context.Context, id int64) error
	SoftDeleteBillingPlan(ctx context.Context, argUuid uuid.UUID) error
	SoftDeleteCariAccountByCustomer(ctx context.Context, arg SoftDeleteCariAccountByCustomerParams) (CariAccount, error)
	SoftDeleteCatalogCategory(ctx context.Context, arg SoftDeleteCatalogCategoryParams) (CatalogCategory, error)
	SoftDeleteContractPreset(ctx context.Context, argUuid uuid.UUID) error
	SoftDeleteContractTemplate(ctx context.Context, arg SoftDeleteContractTemplateParams) error
	SoftDeleteCustomer(ctx context.Context, arg SoftDeleteCustomerParams) (Customer, error)
	SoftDeleteCustomerVehicle(ctx context.Context, arg SoftDeleteCustomerVehicleParams) (CustomerVehicle, error)
	SoftDeleteCustomerVehiclesByCustomer(ctx context.Context, arg SoftDeleteCustomerVehiclesByCustomerParams) error
	SoftDeleteFinanceAccount(ctx context.Context, arg SoftDeleteFinanceAccountParams) (FinanceAccount, error)
	SoftDeleteFinanceCategory(ctx context.Context, arg SoftDeleteFinanceCategoryParams) (FinanceCategory, error)
	SoftDeleteLead(ctx context.Context, arg SoftDeleteLeadParams) (SoftDeleteLeadRow, error)
	SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) (Product, error)
	SoftDeleteService(ctx context.Context, arg SoftDeleteServiceParams) (Service, error)
	SoftDeleteSupplier(ctx context.Context, arg SoftDeleteSupplierParams) (Supplier, error)
	SoftDeleteVehicleBrand(ctx context.Context, argUuid uuid.UUID) (VehicleBrand, error)
	SoftDeleteVehicleModel(ctx context.Context, argUuid uuid.UUID) (VehicleModel, error)
	// Quota tokens = input + output + cache writes (cache reads are not counted).
	SumAIOrganizationTokensSince(ctx context.Context, arg SumAIOrganizationTokensSinceParams) (int64, error)
	SumCariBalances(ctx context.Context, organizationID int64) (SumCariBalancesRow, error)
	SumFinanceExpensesByCategory(ctx context.Context, arg SumFinanceExpensesByCategoryParams) ([]SumFinanceExpensesByCategoryRow, error)
	SumFinanceTransactionsByType(ctx context.Context, arg SumFinanceTransactionsByTypeParams) ([]SumFinanceTransactionsByTypeRow, error)
	SumProductSalesDaily(ctx context.Context, arg SumProductSalesDailyParams) (SumProductSalesDailyRow, error)
	// Cars are counted on the day they were opened; money on the day it was
	// taken, so closing a multi-day job lands in that day's till.
	SumServiceJobsDaily(ctx context.Context, arg SumServiceJobsDailyParams) (SumServiceJobsDailyRow, error)
	TodoSummary(ctx context.Context, arg TodoSummaryParams) (TodoSummaryRow, error)
	TouchAIConversation(ctx context.Context, arg TouchAIConversationParams) error
	UpdateAIConversationTitle(ctx context.Context, arg UpdateAIConversationTitleParams) (AiConversation, error)
	UpdateAIMessageContentUI(ctx context.Context, arg UpdateAIMessageContentUIParams) error
	UpdateAISettings(ctx context.Context, arg UpdateAISettingsParams) (AiSetting, error)
	UpdateAppSettings(ctx context.Context, arg UpdateAppSettingsParams) (AppSetting, error)
	UpdateAuthSettings(ctx context.Context, arg UpdateAuthSettingsParams) (AuthSetting, error)
	UpdateBillingPlan(ctx context.Context, arg UpdateBillingPlanParams) (BillingPlan, error)
	UpdateCatalogCategory(ctx context.Context, arg UpdateCatalogCategoryParams) (CatalogCategory, error)
	UpdateContractInstanceStatus(ctx context.Context, arg UpdateContractInstanceStatusParams) (ContractInstance, error)
	UpdateContractPreset(ctx context.Context, arg UpdateContractPresetParams) (ContractPreset, error)
	UpdateContractSignerPhone(ctx context.Context, arg UpdateContractSignerPhoneParams) error
	UpdateContractTemplate(ctx context.Context, arg UpdateContractTemplateParams) (ContractTemplate, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateDiscountCode(ctx context.Context, arg UpdateDiscountCodeParams) (BillingDiscountCode, error)
	UpdateFeatureActive(ctx context.Context, arg UpdateFeatureActiveParams) error
	UpdateFinanceAccount(ctx context.Context, arg UpdateFinanceAccountParams) (FinanceAccount, error)
	UpdateFinanceCategory(ctx context.Context, arg UpdateFinanceCategoryParams) (FinanceCategory, error)
	UpdateGitHubAppSettings(ctx context.Context, arg UpdateGitHubAppSettingsParams) (GithubAppSetting, error)
	UpdateImportJobFileKey(ctx context.Context, arg UpdateImportJobFileKeyParams) (ImportJob, error)
	UpdateImportJobMapping(ctx context.Context, arg UpdateImportJobMappingParams) (ImportJob, error)
	UpdateImportJobPreview(ctx context.Context, arg UpdateImportJobPreviewParams) (ImportJob, error)
	UpdateInvoiceFiles(ctx context.Context, arg UpdateInvoiceFilesParams) (BillingInvoice, error)
	UpdateInvoiceProfile(ctx context.Context, arg UpdateInvoiceProfileParams) (UpdateInvoiceProfileRow, error)
	UpdateJobConsumptionQty(ctx context.Context, arg UpdateJobConsumptionQtyParams) (ServiceJobConsumption, error)
	UpdateLead(ctx context.Context, arg UpdateLeadParams) (Lead, error)
	UpdateLogPurgeRule(ctx context.Context, arg UpdateLogPurgeRuleParams) (LogPurgeRule, error)
	UpdateOAuthAccountRefreshToken(ctx context.Context, arg UpdateOAuthAccountRefreshTokenParams) error
	UpdateOAuthProviderSettings(ctx context.Context, arg UpdateOAuthProviderSettingsParams) (OauthProviderSetting, error)
	UpdateOrganizationLetterhead(ctx context.Context, arg UpdateOrganizationLetterheadParams) (Organization, error)
	UpdateOrganizationPlatform(ctx context.Context, arg UpdateOrganizationPlatformParams) (Organization, error)
	UpdateOutboundMessageStatus(ctx context.Context, arg UpdateOutboundMessageStatusParams) (OutboundMessage, error)
	UpdatePaymentSettings(ctx context.Context, arg UpdatePaymentSettingsParams) (BillingSetting, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateQuoteContent(ctx context.Context, arg UpdateQuoteContentParams) (Quote, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateSellerSettings(ctx context.Context, arg UpdateSellerSettingsParams) (UpdateSellerSettingsRow, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateServiceJobAssignee(ctx context.Context, arg UpdateServiceJobAssigneeParams) (ServiceJob, error)
	UpdateServiceJobNotes(ctx context.Context, arg UpdateServiceJobNotesParams) (ServiceJob, error)
	UpdateStepupSettings(ctx context.Context, arg UpdateStepupSettingsParams) (StepupSetting, error)
	UpdateSubscriptionAdmin(ctx context.Context, arg UpdateSubscriptionAdminParams) (BillingSubscription, error)
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
	UpdateUserLastLogin(ctx context.Context, id int64) error
	UpdateUserLocale(ctx context.Context, arg UpdateUserLocaleParams) error
	UpdateUserPasswordByID(ctx context.Context, arg UpdateUserPasswordByIDParams) error
	// Re-activating a user (status -> active) clears a self-service deactivation.
	UpdateUserPlatform(ctx context.Context, arg UpdateUserPlatformParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserProfileBasics(ctx context.Context, arg UpdateUserProfileBasicsParams) error
	UpdateUserProfileByUUID(ctx context.Context, arg UpdateUserProfileByUUIDParams) (User, error)
	UpdateUserTOTPRecoveryHashes(ctx context.Context, arg UpdateUserTOTPRecoveryHashesParams) error
	UpdateVehicleBrand(ctx context.Context, arg UpdateVehicleBrandParams) (VehicleBrand, error)
	UpdateVehicleModel(ctx context.Context, arg UpdateVehicleModelParams) (VehicleModel, error)
	UpdateWebAuthnCredentialCounter(ctx context.Context, arg UpdateWebAuthnCredentialCounterParams) error
	UpdateWebAuthnCredentialName(ctx context.Context, arg UpdateWebAuthnCredentialNameParams) (WebauthnCredential, error)
	UpdateWhatsAppSessionQR(ctx context.Context, arg UpdateWhatsAppSessionQRParams) (WhatsappSession, error)
	UpsertAIOrganizationSettings(ctx context.Context, arg UpsertAIOrganizationSettingsParams) (AiOrganizationSetting, error)
	UpsertBuiltinFeature(ctx context.Context, arg UpsertBuiltinFeatureParams) error
	UpsertDailySummarySettings(ctx context.Context, arg UpsertDailySummarySettingsParams) (DailySummarySetting, error)
	UpsertMessageTemplate(ctx context.Context, arg UpsertMessageTemplateParams) (MessageTemplate, error)
	UpsertNotificationMemberSettings(ctx context.Context, arg UpsertNotificationMemberSettingsParams) (NotificationMemberSetting, error)
	UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error)
	UpsertNotificationRule(ctx context.Context, arg UpsertNotificationRuleParams) (NotificationRule, error)
	UpsertNotificationTypePreference(ctx context.Context, arg UpsertNotificationTypePreferenceParams) (NotificationTypePreference, error)
	UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (PushSubscription, error)
	UpsertUserTOTPSetup(ctx context.Context, arg UpsertUserTOTPSetupParams) (UserTotp, error)
	UpsertVehicleAlertSettings(ctx context.Context, arg UpsertVehicleAlertSettingsParams) (VehicleAlertSetting, error)
	UpsertWhatsAppSession(ctx context.Context, arg UpsertWhatsAppSessionParams) (WhatsappSession, error)
	UserHasRoleSlug(ctx context.Context, arg UserHasRoleSlugParams) (bool, error)
	VehicleModelYearExists(ctx context.Context, arg VehicleModelYearExistsParams) (bool, error)
	VoidCariEntry(ctx context.Context, arg VoidCariEntryParams) (CariEntry, error)
	VoidCariEntryBySource(ctx context.Context, arg VoidCariEntryBySourceParams) (CariEntry, error)
	VoidFinanceTransaction(ctx context.Context, arg VoidFinanceTransactionParams) (FinanceTransaction, error)
	VoidProductSale(ctx context.Context, arg VoidProductSaleParams) (ProductSale, error)
	VoidPurchase(ctx context.Context, arg VoidPurchaseParams) (Purchase, error)
	VoidServiceJobPayment(ctx context.Context, arg VoidServiceJobPaymentParams) (ServiceJobPayment, error)
}

var _ Querier = (*Queries)(nil)
