// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFinanceAccountIDByUUIDForReport = `-- name: GetFinanceAccountIDByUUIDForReport :one
SELECT id FROM finance_accounts
WHERE uuid = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type GetFinanceAccountIDByUUIDForReportParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) GetFinanceAccountIDByUUIDForReport(ctx context.Context, arg GetFinanceAccountIDByUUIDForReportParams) (int64, error) {
	row := q.db.QueryRow(ctx, getFinanceAccountIDByUUIDForReport, arg.Uuid, arg.OrganizationID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const reportCariOutstanding = `-- name: ReportCariOutstanding :many
SELECT
    a.uuid AS account_uuid,
    c.uuid AS customer_uuid,
    c.name AS customer_name,
    c.phone AS customer_phone,
    a.currency,
    a.balance,
    (
        SELECT MAX(e.entry_date)::date
        FROM cari_entries e
        WHERE e.account_id = a.id AND e.status = 'posted'
    ) AS last_entry_date
FROM cari_accounts a
JOIN customers c ON c.id = a.customer_id AND c.deleted_at IS NULL
WHERE a.organization_id = $1
  AND a.deleted_at IS NULL
  AND a.balance > 0
  AND a.is_active = true
  AND ($2::text IS NULL OR a.currency = $2)
ORDER BY a.balance DESC
LIMIT 50
`

type ReportCariOutstandingParams struct {
	OrganizationID int64       `json:"organization_id"`
	Currency       pgtype.Text `json:"currency"`
}

type ReportCariOutstandingRow struct {
	AccountUuid   uuid.UUID      `json:"account_uuid"`
	CustomerUuid  uuid.UUID      `json:"customer_uuid"`
	CustomerName  string         `json:"customer_name"`
	CustomerPhone string         `json:"customer_phone"`
	Currency      string         `json:"currency"`
	Balance       pgtype.Numeric `json:"balance"`
	LastEntryDate pgtype.Date    `json:"last_entry_date"`
}

func (q *Queries) ReportCariOutstanding(ctx context.Context, arg ReportCariOutstandingParams) ([]ReportCariOutstandingRow, error) {
	rows, err := q.db.Query(ctx, reportCariOutstanding, arg.OrganizationID, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportCariOutstandingRow{}
	for rows.Next() {
		var i ReportCariOutstandingRow
		if err := rows.Scan(
			&i.AccountUuid,
			&i.CustomerUuid,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.Currency,
			&i.Balance,
			&i.LastEntryDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportCariPeriodTotals = `-- name: ReportCariPeriodTotals :one
SELECT
    COALESCE(SUM(e.amount) FILTER (WHERE e.type = 'charge'), 0)::numeric AS charged,
    COALESCE(SUM(e.amount) FILTER (WHERE e.type = 'payment'), 0)::numeric AS collected,
    COUNT(*) FILTER (WHERE e.type = 'charge')::bigint AS charge_count,
    COUNT(*) FILTER (WHERE e.type = 'payment')::bigint AS payment_count
FROM cari_entries e
WHERE e.organization_id = $1
  AND e.status = 'posted'
  AND e.entry_date >= $2
  AND e.entry_date <= $3
  AND ($4::text IS NULL OR EXISTS (
      SELECT 1 FROM cari_accounts a
      WHERE a.id = e.account_id AND a.currency = $4
  ))
`

type ReportCariPeriodTotalsParams struct {
	OrganizationID int64       `json:"organization_id"`
	DateFrom       pgtype.Date `json:"date_from"`
	DateTo         pgtype.Date `json:"date_to"`
	Currency       pgtype.Text `json:"currency"`
}

type ReportCariPeriodTotalsRow struct {
	Charged      pgtype.Numeric `json:"charged"`
	Collected    pgtype.Numeric `json:"collected"`
	ChargeCount  int64          `json:"charge_count"`
	PaymentCount int64          `json:"payment_count"`
}

func (q *Queries) ReportCariPeriodTotals(ctx context.Context, arg ReportCariPeriodTotalsParams) (ReportCariPeriodTotalsRow, error) {
	row := q.db.QueryRow(ctx, reportCariPeriodTotals,
		arg.OrganizationID,
		arg.DateFrom,
		arg.DateTo,
		arg.Currency,
	)
	var i ReportCariPeriodTotalsRow
	err := row.Scan(
		&i.Charged,
		&i.Collected,
		&i.ChargeCount,
		&i.PaymentCount,
	)
	return i, err
}

const reportExpensesByCategory = `-- name: ReportExpensesByCategory :many
SELECT
    c.uuid AS category_uuid,
    c.name AS category_name,
    COALESCE(SUM(t.amount), 0)::numeric AS total,
    COUNT(*)::bigint AS count
FROM finance_transactions t
JOIN finance_categories c ON c.id = t.category_id
WHERE t.organization_id = $1
  AND t.type = 'expense'
  AND t.status = 'posted'
  AND t.transaction_date >= $2
  AND t.transaction_date <= $3
  AND ($4::text IS NULL OR t.currency = $4)
  AND ($5::text IS NULL OR t.source_type = $5)
  AND (
    $6::bigint IS NULL
    OR t.account_id = $6
    OR t.counter_account_id = $6
  )
GROUP BY c.uuid, c.name
ORDER BY total DESC
`

type ReportExpensesByCategoryParams struct {
	OrganizationID int64       `json:"organization_id"`
	DateFrom       pgtype.Date `json:"date_from"`
	DateTo         pgtype.Date `json:"date_to"`
	Currency       pgtype.Text `json:"currency"`
	SourceType     pgtype.Text `json:"source_type"`
	AccountID      pgtype.Int8 `json:"account_id"`
}

type ReportExpensesByCategoryRow struct {
	CategoryUuid uuid.UUID      `json:"category_uuid"`
	CategoryName string         `json:"category_name"`
	Total        pgtype.Numeric `json:"total"`
	Count        int64          `json:"count"`
}

func (q *Queries) ReportExpensesByCategory(ctx context.Context, arg ReportExpensesByCategoryParams) ([]ReportExpensesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, reportExpensesByCategory,
		arg.OrganizationID,
		arg.DateFrom,
		arg.DateTo,
		arg.Currency,
		arg.SourceType,
		arg.AccountID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportExpensesByCategoryRow{}
	for rows.Next() {
		var i ReportExpensesByCategoryRow
		if err := rows.Scan(
			&i.CategoryUuid,
			&i.CategoryName,
			&i.Total,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportFinanceBySource = `-- name: ReportFinanceBySource :many
SELECT
    t.source_type,
    t.type,
    COALESCE(SUM(t.amount), 0)::numeric AS total,
    COUNT(*)::bigint AS count
FROM finance_transactions t
WHERE t.organization_id = $1
  AND t.status = 'posted'
  AND t.transaction_date >= $2
  AND t.transaction_date <= $3
  AND ($4::text IS NULL OR t.currency = $4)
  AND ($5::text IS NULL OR t.source_type = $5)
  AND (
    $6::bigint IS NULL
    OR t.account_id = $6
    OR t.counter_account_id = $6
  )
GROUP BY t.source_type, t.type
ORDER BY total DESC
`

type ReportFinanceBySourceParams struct {
	OrganizationID int64       `json:"organization_id"`
	DateFrom       pgtype.Date `json:"date_from"`
	DateTo         pgtype.Date `json:"date_to"`
	Currency       pgtype.Text `json:"currency"`
	SourceType     pgtype.Text `json:"source_type"`
	AccountID      pgtype.Int8 `json:"account_id"`
}

type ReportFinanceBySourceRow struct {
	SourceType pgtype.Text    `json:"source_type"`
	Type       string         `json:"type"`
	Total      pgtype.Numeric `json:"total"`
	Count      int64          `json:"count"`
}

func (q *Queries) ReportFinanceBySource(ctx context.Context, arg ReportFinanceBySourceParams) ([]ReportFinanceBySourceRow, error) {
	rows, err := q.db.Query(ctx, reportFinanceBySource,
		arg.OrganizationID,
		arg.DateFrom,
		arg.DateTo,
		arg.Currency,
		arg.SourceType,
		arg.AccountID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportFinanceBySourceRow{}
	for rows.Next() {
		var i ReportFinanceBySourceRow
		if err := rows.Scan(
			&i.SourceType,
			&i.Type,
			&i.Total,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportFinanceTimeseries = `-- name: ReportFinanceTimeseries :many
SELECT
    date_trunc($1::text, t.transaction_date::timestamptz)::date AS bucket,
    COALESCE(SUM(t.amount) FILTER (WHERE t.type = 'income'), 0)::numeric AS income,
    COALESCE(SUM(t.amount) FILTER (WHERE t.type = 'expense'), 0)::numeric AS expense
FROM finance_transactions t
WHERE t.organization_id = $2
  AND t.status = 'posted'
  AND t.transaction_date >= $3
  AND t.transaction_date <= $4
  AND ($5::text IS NULL OR t.currency = $5)
  AND ($6::text IS NULL OR t.source_type = $6)
  AND (
    $7::bigint IS NULL
    OR t.account_id = $7
    OR t.counter_account_id = $7
  )
GROUP BY bucket
ORDER BY bucket ASC
`

type ReportFinanceTimeseriesParams struct {
	Granularity    string      `json:"granularity"`
	OrganizationID int64       `json:"organization_id"`
	DateFrom       pgtype.Date `json:"date_from"`
	DateTo         pgtype.Date `json:"date_to"`
	Currency       pgtype.Text `json:"currency"`
	SourceType     pgtype.Text `json:"source_type"`
	AccountID      pgtype.Int8 `json:"account_id"`
}

type ReportFinanceTimeseriesRow struct {
	Bucket  pgtype.Date    `json:"bucket"`
	Income  pgtype.Numeric `json:"income"`
	Expense pgtype.Numeric `json:"expense"`
}

func (q *Queries) ReportFinanceTimeseries(ctx context.Context, arg ReportFinanceTimeseriesParams) ([]ReportFinanceTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, reportFinanceTimeseries,
		arg.Granularity,
		arg.OrganizationID,
		arg.DateFrom,
		arg.DateTo,
		arg.Currency,
		arg.SourceType,
		arg.AccountID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportFinanceTimeseriesRow{}
	for rows.Next() {
		var i ReportFinanceTimeseriesRow
		if err := rows.Scan(&i.Bucket, &i.Income, &i.Expense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportFinanceTotals = `-- name: ReportFinanceTotals :one

SELECT
    COALESCE(SUM(t.amount) FILTER (WHERE t.type = 'income'), 0)::numeric AS total_income,
    COALESCE(SUM(t.amount) FILTER (WHERE t.type = 'expense'), 0)::numeric AS total_expense,
    COUNT(*) FILTER (WHERE t.type = 'income')::bigint AS income_count,
    COUNT(*) FILTER (WHERE t.type = 'expense')::bigint AS expense_count
FROM finance_transactions t
WHERE t.organization_id = $1
  AND t.status = 'posted'
  AND t.transaction_date >= $2
  AND t.transaction_date <= $3
  AND ($4::text IS NULL OR t.currency = $4)
  AND ($5::text IS NULL OR t.source_type = $5)
  AND (
    $6::bigint IS NULL
    OR t.account_id = $6
    OR t.counter_account_id = $6
  )
`

type ReportFinanceTotalsParams struct {
	OrganizationID int64       `json:"organization_id"`
	DateFrom       pgtype.Date `json:"date_from"`
	DateTo         pgtype.Date `json:"date_to"`
	Currency       pgtype.Text `json:"currency"`
	SourceType     pgtype.Text `json:"source_type"`
	AccountID      pgtype.Int8 `json:"account_id"`
}

type ReportFinanceTotalsRow struct {
	TotalIncome  pgtype.Numeric `json:"total_income"`
	TotalExpense pgtype.Numeric `json:"total_expense"`
	IncomeCount  int64          `json:"income_count"`
	ExpenseCount int64          `json:"expense_count"`
}

// Tenant operational / financial reports (read-only aggregates).
func (q *Queries) ReportFinanceTotals(ctx context.Context, arg ReportFinanceTotalsParams) (ReportFinanceTotalsRow, error) {
	row := q.db.QueryRow(ctx, reportFinanceTotals,
		arg.OrganizationID,
		arg.DateFrom,
		arg.DateTo,
		arg.Currency,
		arg.SourceType,
		arg.AccountID,
	)
	var i ReportFinanceTotalsRow
	err := row.Scan(
		&i.TotalIncome,
		&i.TotalExpense,
		&i.IncomeCount,
		&i.ExpenseCount,
	)
	return i, err
}

const reportIncomeByCategory = `-- name: ReportIncomeByCategory :many
SELECT
    c.uuid AS category_uuid,
    c.name AS category_name,
    COALESCE(SUM(t.amount), 0)::numeric AS total,
    COUNT(*)::bigint AS count
FROM finance_transactions t
JOIN finance_categories c ON c.id = t.category_id
WHERE t.organization_id = $1
  AND t.type = 'income'
  AND t.status = 'posted'
  AND t.transaction_date >= $2
  AND t.transaction_date <= $3
  AND ($4::text IS NULL OR t.currency = $4)
  AND ($5::text IS NULL OR t.source_type = $5)
  AND (
    $6::bigint IS NULL
    OR t.account_id = $6
    OR t.counter_account_id = $6
  )
GROUP BY c.uuid, c.name
ORDER BY total DESC
`

type ReportIncomeByCategoryParams struct {
	OrganizationID int64       `json:"organization_id"`
	DateFrom       pgtype.Date `json:"date_from"`
	DateTo         pgtype.Date `json:"date_to"`
	Currency       pgtype.Text `json:"currency"`
	SourceType     pgtype.Text `json:"source_type"`
	AccountID      pgtype.Int8 `json:"account_id"`
}

type ReportIncomeByCategoryRow struct {
	CategoryUuid uuid.UUID      `json:"category_uuid"`
	CategoryName string         `json:"category_name"`
	Total        pgtype.Numeric `json:"total"`
	Count        int64          `json:"count"`
}

func (q *Queries) ReportIncomeByCategory(ctx context.Context, arg ReportIncomeByCategoryParams) ([]ReportIncomeByCategoryRow, error) {
	rows, err := q.db.Query(ctx, reportIncomeByCategory,
		arg.OrganizationID,
		arg.DateFrom,
		arg.DateTo,
		arg.Currency,
		arg.SourceType,
		arg.AccountID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportIncomeByCategoryRow{}
	for rows.Next() {
		var i ReportIncomeByCategoryRow
		if err := rows.Scan(
			&i.CategoryUuid,
			&i.CategoryName,
			&i.Total,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportJobPaymentsByMethod = `-- name: ReportJobPaymentsByMethod :many
SELECT
    p.method,
    COALESCE(SUM(p.amount), 0)::numeric AS total,
    COUNT(*)::bigint AS count
FROM service_job_payments p
JOIN service_jobs j ON j.id = p.job_id
WHERE p.organization_id = $1
  AND p.status = 'posted'
  AND j.started_at >= $2
  AND j.started_at < $3
  AND ($4::text IS NULL OR p.currency = $4)
  AND ($5::text IS NULL OR p.method = $5)
GROUP BY p.method
ORDER BY total DESC
`

type ReportJobPaymentsByMethodParams struct {
	OrganizationID int64              `json:"organization_id"`
	TsFrom         pgtype.Timestamptz `json:"ts_from"`
	TsTo           pgtype.Timestamptz `json:"ts_to"`
	Currency       pgtype.Text        `json:"currency"`
	PaymentMethod  pgtype.Text        `json:"payment_method"`
}

type ReportJobPaymentsByMethodRow struct {
	Method string         `json:"method"`
	Total  pgtype.Numeric `json:"total"`
	Count  int64          `json:"count"`
}

func (q *Queries) ReportJobPaymentsByMethod(ctx context.Context, arg ReportJobPaymentsByMethodParams) ([]ReportJobPaymentsByMethodRow, error) {
	rows, err := q.db.Query(ctx, reportJobPaymentsByMethod,
		arg.OrganizationID,
		arg.TsFrom,
		arg.TsTo,
		arg.Currency,
		arg.PaymentMethod,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportJobPaymentsByMethodRow{}
	for rows.Next() {
		var i ReportJobPaymentsByMethodRow
		if err := rows.Scan(&i.Method, &i.Total, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportJobStats = `-- name: ReportJobStats :one
SELECT
    COUNT(*) FILTER (WHERE j.status IN ('delivered', 'ready', 'in_progress'))::bigint AS job_count,
    COUNT(*) FILTER (WHERE j.payment_status = 'paid')::bigint AS paid_count,
    COUNT(*) FILTER (WHERE j.status = 'ready')::bigint AS done_count,
    COUNT(*) FILTER (WHERE j.status = 'in_progress')::bigint AS in_progress_count,
    COUNT(*) FILTER (WHERE j.status = 'cancelled')::bigint AS cancelled_count,
    COALESCE(SUM(j.total_amount) FILTER (WHERE j.payment_status = 'paid'), 0)::numeric AS paid_total,
    COALESCE(AVG(j.total_amount) FILTER (WHERE j.payment_status = 'paid' AND j.total_amount > 0), 0)::numeric AS avg_ticket,
    COUNT(DISTINCT j.vehicle_id) FILTER (WHERE j.status IN ('delivered', 'ready', 'in_progress'))::bigint AS vehicles_served
FROM service_jobs j
WHERE j.organization_id = $1
  AND j.started_at >= $2
  AND j.started_at < $3
  AND ($4::text IS NULL OR j.currency = $4)
`

type ReportJobStatsParams struct {
	OrganizationID int64              `json:"organization_id"`
	TsFrom         pgtype.Timestamptz `json:"ts_from"`
	TsTo           pgtype.Timestamptz `json:"ts_to"`
	Currency       pgtype.Text        `json:"currency"`
}

type ReportJobStatsRow struct {
	JobCount        int64          `json:"job_count"`
	PaidCount       int64          `json:"paid_count"`
	DoneCount       int64          `json:"done_count"`
	InProgressCount int64          `json:"in_progress_count"`
	CancelledCount  int64          `json:"cancelled_count"`
	PaidTotal       pgtype.Numeric `json:"paid_total"`
	AvgTicket       pgtype.Numeric `json:"avg_ticket"`
	VehiclesServed  int64          `json:"vehicles_served"`
}

func (q *Queries) ReportJobStats(ctx context.Context, arg ReportJobStatsParams) (ReportJobStatsRow, error) {
	row := q.db.QueryRow(ctx, reportJobStats,
		arg.OrganizationID,
		arg.TsFrom,
		arg.TsTo,
		arg.Currency,
	)
	var i ReportJobStatsRow
	err := row.Scan(
		&i.JobCount,
		&i.PaidCount,
		&i.DoneCount,
		&i.InProgressCount,
		&i.CancelledCount,
		&i.PaidTotal,
		&i.AvgTicket,
		&i.VehiclesServed,
	)
	return i, err
}

const reportJobsTimeseries = `-- name: ReportJobsTimeseries :many
SELECT
    date_trunc($1::text, j.started_at)::date AS bucket,
    COUNT(*) FILTER (WHERE j.payment_status = 'paid')::bigint AS paid_count,
    COALESCE(SUM(j.total_amount) FILTER (WHERE j.payment_status = 'paid'), 0)::numeric AS paid_total
FROM service_jobs j
WHERE j.organization_id = $2
  AND j.started_at >= $3
  AND j.started_at < $4
  AND ($5::text IS NULL OR j.currency = $5)
GROUP BY bucket
ORDER BY bucket ASC
`

type ReportJobsTimeseriesParams struct {
	Granularity    string             `json:"granularity"`
	OrganizationID int64              `json:"organization_id"`
	TsFrom         pgtype.Timestamptz `json:"ts_from"`
	TsTo           pgtype.Timestamptz `json:"ts_to"`
	Currency       pgtype.Text        `json:"currency"`
}

type ReportJobsTimeseriesRow struct {
	Bucket    pgtype.Date    `json:"bucket"`
	PaidCount int64          `json:"paid_count"`
	PaidTotal pgtype.Numeric `json:"paid_total"`
}

func (q *Queries) ReportJobsTimeseries(ctx context.Context, arg ReportJobsTimeseriesParams) ([]ReportJobsTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, reportJobsTimeseries,
		arg.Granularity,
		arg.OrganizationID,
		arg.TsFrom,
		arg.TsTo,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportJobsTimeseriesRow{}
	for rows.Next() {
		var i ReportJobsTimeseriesRow
		if err := rows.Scan(&i.Bucket, &i.PaidCount, &i.PaidTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportProductSaleStats = `-- name: ReportProductSaleStats :one
SELECT
    COUNT(*)::bigint AS sale_count,
    COALESCE(SUM(s.total_amount), 0)::numeric AS sale_total
FROM product_sales s
WHERE s.organization_id = $1
  AND s.status = 'posted'
  AND s.sold_at >= $2
  AND s.sold_at < $3
  AND ($4::text IS NULL OR s.currency = $4)
  AND ($5::text IS NULL OR s.method = $5)
`

type ReportProductSaleStatsParams struct {
	OrganizationID int64              `json:"organization_id"`
	TsFrom         pgtype.Timestamptz `json:"ts_from"`
	TsTo           pgtype.Timestamptz `json:"ts_to"`
	Currency       pgtype.Text        `json:"currency"`
	PaymentMethod  pgtype.Text        `json:"payment_method"`
}

type ReportProductSaleStatsRow struct {
	SaleCount int64          `json:"sale_count"`
	SaleTotal pgtype.Numeric `json:"sale_total"`
}

func (q *Queries) ReportProductSaleStats(ctx context.Context, arg ReportProductSaleStatsParams) (ReportProductSaleStatsRow, error) {
	row := q.db.QueryRow(ctx, reportProductSaleStats,
		arg.OrganizationID,
		arg.TsFrom,
		arg.TsTo,
		arg.Currency,
		arg.PaymentMethod,
	)
	var i ReportProductSaleStatsRow
	err := row.Scan(&i.SaleCount, &i.SaleTotal)
	return i, err
}

const reportProductSalesByMethod = `-- name: ReportProductSalesByMethod :many
SELECT
    s.method,
    COALESCE(SUM(s.total_amount), 0)::numeric AS total,
    COUNT(*)::bigint AS count
FROM product_sales s
WHERE s.organization_id = $1
  AND s.status = 'posted'
  AND s.sold_at >= $2
  AND s.sold_at < $3
  AND ($4::text IS NULL OR s.currency = $4)
  AND ($5::text IS NULL OR s.method = $5)
GROUP BY s.method
ORDER BY total DESC
`

type ReportProductSalesByMethodParams struct {
	OrganizationID int64              `json:"organization_id"`
	TsFrom         pgtype.Timestamptz `json:"ts_from"`
	TsTo           pgtype.Timestamptz `json:"ts_to"`
	Currency       pgtype.Text        `json:"currency"`
	PaymentMethod  pgtype.Text        `json:"payment_method"`
}

type ReportProductSalesByMethodRow struct {
	Method string         `json:"method"`
	Total  pgtype.Numeric `json:"total"`
	Count  int64          `json:"count"`
}

func (q *Queries) ReportProductSalesByMethod(ctx context.Context, arg ReportProductSalesByMethodParams) ([]ReportProductSalesByMethodRow, error) {
	rows, err := q.db.Query(ctx, reportProductSalesByMethod,
		arg.OrganizationID,
		arg.TsFrom,
		arg.TsTo,
		arg.Currency,
		arg.PaymentMethod,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportProductSalesByMethodRow{}
	for rows.Next() {
		var i ReportProductSalesByMethodRow
		if err := rows.Scan(&i.Method, &i.Total, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportProductsDistribution = `-- name: ReportProductsDistribution :many
SELECT
    l.name AS product_name,
    COALESCE(SUM(l.qty), 0)::numeric AS qty,
    COALESCE(SUM(l.line_total), 0)::numeric AS total,
    COUNT(*)::bigint AS line_count
FROM product_sale_lines l
JOIN product_sales s ON s.id = l.sale_id
WHERE l.organization_id = $1
  AND s.status = 'posted'
  AND s.sold_at >= $2
  AND s.sold_at < $3
  AND ($4::text IS NULL OR l.currency = $4)
  AND ($5::text IS NULL OR s.method = $5)
GROUP BY l.name
ORDER BY total DESC
LIMIT 50
`

type ReportProductsDistributionParams struct {
	OrganizationID int64              `json:"organization_id"`
	TsFrom         pgtype.Timestamptz `json:"ts_from"`
	TsTo           pgtype.Timestamptz `json:"ts_to"`
	Currency       pgtype.Text        `json:"currency"`
	PaymentMethod  pgtype.Text        `json:"payment_method"`
}

type ReportProductsDistributionRow struct {
	ProductName string         `json:"product_name"`
	Qty         pgtype.Numeric `json:"qty"`
	Total       pgtype.Numeric `json:"total"`
	LineCount   int64          `json:"line_count"`
}

func (q *Queries) ReportProductsDistribution(ctx context.Context, arg ReportProductsDistributionParams) ([]ReportProductsDistributionRow, error) {
	rows, err := q.db.Query(ctx, reportProductsDistribution,
		arg.OrganizationID,
		arg.TsFrom,
		arg.TsTo,
		arg.Currency,
		arg.PaymentMethod,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportProductsDistributionRow{}
	for rows.Next() {
		var i ReportProductsDistributionRow
		if err := rows.Scan(
			&i.ProductName,
			&i.Qty,
			&i.Total,
			&i.LineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportPurchaseStats = `-- name: ReportPurchaseStats :one
SELECT
    COUNT(*)::bigint AS purchase_count,
    COALESCE(SUM(p.total_amount), 0)::numeric AS purchase_total
FROM purchases p
WHERE p.organization_id = $1
  AND p.status = 'posted'
  AND p.purchased_at >= $2
  AND p.purchased_at < $3
  AND ($4::text IS NULL OR p.currency = $4)
  AND ($5::text IS NULL OR p.method = $5)
`

type ReportPurchaseStatsParams struct {
	OrganizationID int64              `json:"organization_id"`
	TsFrom         pgtype.Timestamptz `json:"ts_from"`
	TsTo           pgtype.Timestamptz `json:"ts_to"`
	Currency       pgtype.Text        `json:"currency"`
	PaymentMethod  pgtype.Text        `json:"payment_method"`
}

type ReportPurchaseStatsRow struct {
	PurchaseCount int64          `json:"purchase_count"`
	PurchaseTotal pgtype.Numeric `json:"purchase_total"`
}

func (q *Queries) ReportPurchaseStats(ctx context.Context, arg ReportPurchaseStatsParams) (ReportPurchaseStatsRow, error) {
	row := q.db.QueryRow(ctx, reportPurchaseStats,
		arg.OrganizationID,
		arg.TsFrom,
		arg.TsTo,
		arg.Currency,
		arg.PaymentMethod,
	)
	var i ReportPurchaseStatsRow
	err := row.Scan(&i.PurchaseCount, &i.PurchaseTotal)
	return i, err
}

const reportServicesDistribution = `-- name: ReportServicesDistribution :many
SELECT
    l.name AS service_name,
    COALESCE(SUM(l.qty), 0)::numeric AS qty,
    COALESCE(SUM(l.line_total), 0)::numeric AS total,
    COUNT(*)::bigint AS line_count
FROM service_job_lines l
JOIN service_jobs j ON j.id = l.job_id
WHERE l.organization_id = $1
  AND l.line_type = 'service'
  -- Job statuses are in_progress | ready | delivered | cancelled | voided
  -- (000046); payment is tracked separately in payment_status.
  AND j.status NOT IN ('cancelled', 'voided')
  AND j.started_at >= $2
  AND j.started_at < $3
  AND ($4::text IS NULL OR l.currency = $4)
GROUP BY l.name
ORDER BY total DESC
LIMIT 50
`

type ReportServicesDistributionParams struct {
	OrganizationID int64              `json:"organization_id"`
	TsFrom         pgtype.Timestamptz `json:"ts_from"`
	TsTo           pgtype.Timestamptz `json:"ts_to"`
	Currency       pgtype.Text        `json:"currency"`
}

type ReportServicesDistributionRow struct {
	ServiceName string         `json:"service_name"`
	Qty         pgtype.Numeric `json:"qty"`
	Total       pgtype.Numeric `json:"total"`
	LineCount   int64          `json:"line_count"`
}

func (q *Queries) ReportServicesDistribution(ctx context.Context, arg ReportServicesDistributionParams) ([]ReportServicesDistributionRow, error) {
	rows, err := q.db.Query(ctx, reportServicesDistribution,
		arg.OrganizationID,
		arg.TsFrom,
		arg.TsTo,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportServicesDistributionRow{}
	for rows.Next() {
		var i ReportServicesDistributionRow
		if err := rows.Scan(
			&i.ServiceName,
			&i.Qty,
			&i.Total,
			&i.LineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportTopCustomers = `-- name: ReportTopCustomers :many
SELECT
    c.uuid AS customer_uuid,
    c.name AS customer_name,
    COALESCE(SUM(j.total_amount) FILTER (WHERE j.payment_status = 'paid'), 0)::numeric AS job_total,
    COUNT(*) FILTER (WHERE j.payment_status = 'paid')::bigint AS job_count
FROM service_jobs j
JOIN customers c ON c.id = j.customer_id
WHERE j.organization_id = $1
  AND j.started_at >= $2
  AND j.started_at < $3
  AND ($4::text IS NULL OR j.currency = $4)
GROUP BY c.uuid, c.name
HAVING COUNT(*) FILTER (WHERE j.payment_status = 'paid') > 0
ORDER BY job_total DESC
LIMIT 20
`

type ReportTopCustomersParams struct {
	OrganizationID int64              `json:"organization_id"`
	TsFrom         pgtype.Timestamptz `json:"ts_from"`
	TsTo           pgtype.Timestamptz `json:"ts_to"`
	Currency       pgtype.Text        `json:"currency"`
}

type ReportTopCustomersRow struct {
	CustomerUuid uuid.UUID      `json:"customer_uuid"`
	CustomerName string         `json:"customer_name"`
	JobTotal     pgtype.Numeric `json:"job_total"`
	JobCount     int64          `json:"job_count"`
}

func (q *Queries) ReportTopCustomers(ctx context.Context, arg ReportTopCustomersParams) ([]ReportTopCustomersRow, error) {
	rows, err := q.db.Query(ctx, reportTopCustomers,
		arg.OrganizationID,
		arg.TsFrom,
		arg.TsTo,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportTopCustomersRow{}
	for rows.Next() {
		var i ReportTopCustomersRow
		if err := rows.Scan(
			&i.CustomerUuid,
			&i.CustomerName,
			&i.JobTotal,
			&i.JobCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
