// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_consumption.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adjustProductStockByID = `-- name: AdjustProductStockByID :exec
UPDATE products
SET stock_quantity = stock_quantity + $1
WHERE id = $2 AND organization_id = $3
`

type AdjustProductStockByIDParams struct {
	Delta          pgtype.Numeric `json:"delta"`
	ID             int64          `json:"id"`
	OrganizationID int64          `json:"organization_id"`
}

func (q *Queries) AdjustProductStockByID(ctx context.Context, arg AdjustProductStockByIDParams) error {
	_, err := q.db.Exec(ctx, adjustProductStockByID, arg.Delta, arg.ID, arg.OrganizationID)
	return err
}

const countServiceProductsByService = `-- name: CountServiceProductsByService :many
SELECT service_id, COUNT(*)::bigint AS product_count
FROM service_products
WHERE organization_id = $1
GROUP BY service_id
`

type CountServiceProductsByServiceRow struct {
	ServiceID    int64 `json:"service_id"`
	ProductCount int64 `json:"product_count"`
}

func (q *Queries) CountServiceProductsByService(ctx context.Context, organizationID int64) ([]CountServiceProductsByServiceRow, error) {
	rows, err := q.db.Query(ctx, countServiceProductsByService, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountServiceProductsByServiceRow{}
	for rows.Next() {
		var i CountServiceProductsByServiceRow
		if err := rows.Scan(&i.ServiceID, &i.ProductCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createJobConsumption = `-- name: CreateJobConsumption :one
INSERT INTO service_job_consumptions (
    organization_id, job_id, product_id, service_id, name, unit, qty, unit_cost, stock_applied, created_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
)
RETURNING id, uuid, organization_id, job_id, product_id, service_id, name, unit, qty, unit_cost, stock_applied, reverted_at, created_by, created_at, updated_at
`

type CreateJobConsumptionParams struct {
	OrganizationID int64          `json:"organization_id"`
	JobID          int64          `json:"job_id"`
	ProductID      int64          `json:"product_id"`
	ServiceID      pgtype.Int8    `json:"service_id"`
	Name           string         `json:"name"`
	Unit           string         `json:"unit"`
	Qty            pgtype.Numeric `json:"qty"`
	UnitCost       pgtype.Numeric `json:"unit_cost"`
	StockApplied   bool           `json:"stock_applied"`
	CreatedBy      pgtype.Int8    `json:"created_by"`
}

func (q *Queries) CreateJobConsumption(ctx context.Context, arg CreateJobConsumptionParams) (ServiceJobConsumption, error) {
	row := q.db.QueryRow(ctx, createJobConsumption,
		arg.OrganizationID,
		arg.JobID,
		arg.ProductID,
		arg.ServiceID,
		arg.Name,
		arg.Unit,
		arg.Qty,
		arg.UnitCost,
		arg.StockApplied,
		arg.CreatedBy,
	)
	var i ServiceJobConsumption
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.JobID,
		&i.ProductID,
		&i.ServiceID,
		&i.Name,
		&i.Unit,
		&i.Qty,
		&i.UnitCost,
		&i.StockApplied,
		&i.RevertedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJobConsumption = `-- name: DeleteJobConsumption :exec
DELETE FROM service_job_consumptions
WHERE id = $1 AND organization_id = $2
`

type DeleteJobConsumptionParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) DeleteJobConsumption(ctx context.Context, arg DeleteJobConsumptionParams) error {
	_, err := q.db.Exec(ctx, deleteJobConsumption, arg.ID, arg.OrganizationID)
	return err
}

const deleteServiceProducts = `-- name: DeleteServiceProducts :exec
DELETE FROM service_products
WHERE organization_id = $1 AND service_id = $2
`

type DeleteServiceProductsParams struct {
	OrganizationID int64 `json:"organization_id"`
	ServiceID      int64 `json:"service_id"`
}

func (q *Queries) DeleteServiceProducts(ctx context.Context, arg DeleteServiceProductsParams) error {
	_, err := q.db.Exec(ctx, deleteServiceProducts, arg.OrganizationID, arg.ServiceID)
	return err
}

const getActiveJobConsumptionByProduct = `-- name: GetActiveJobConsumptionByProduct :one
SELECT id, uuid, organization_id, job_id, product_id, service_id, name, unit, qty, unit_cost, stock_applied, reverted_at, created_by, created_at, updated_at FROM service_job_consumptions
WHERE organization_id = $1 AND job_id = $2
  AND product_id = $3 AND reverted_at IS NULL
ORDER BY id
LIMIT 1
FOR UPDATE
`

type GetActiveJobConsumptionByProductParams struct {
	OrganizationID int64 `json:"organization_id"`
	JobID          int64 `json:"job_id"`
	ProductID      int64 `json:"product_id"`
}

func (q *Queries) GetActiveJobConsumptionByProduct(ctx context.Context, arg GetActiveJobConsumptionByProductParams) (ServiceJobConsumption, error) {
	row := q.db.QueryRow(ctx, getActiveJobConsumptionByProduct, arg.OrganizationID, arg.JobID, arg.ProductID)
	var i ServiceJobConsumption
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.JobID,
		&i.ProductID,
		&i.ServiceID,
		&i.Name,
		&i.Unit,
		&i.Qty,
		&i.UnitCost,
		&i.StockApplied,
		&i.RevertedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobConsumptionForUpdate = `-- name: GetJobConsumptionForUpdate :one
SELECT id, uuid, organization_id, job_id, product_id, service_id, name, unit, qty, unit_cost, stock_applied, reverted_at, created_by, created_at, updated_at FROM service_job_consumptions
WHERE organization_id = $1 AND job_id = $2 AND uuid = $3
FOR UPDATE
`

type GetJobConsumptionForUpdateParams struct {
	OrganizationID int64     `json:"organization_id"`
	JobID          int64     `json:"job_id"`
	Uuid           uuid.UUID `json:"uuid"`
}

func (q *Queries) GetJobConsumptionForUpdate(ctx context.Context, arg GetJobConsumptionForUpdateParams) (ServiceJobConsumption, error) {
	row := q.db.QueryRow(ctx, getJobConsumptionForUpdate, arg.OrganizationID, arg.JobID, arg.Uuid)
	var i ServiceJobConsumption
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.JobID,
		&i.ProductID,
		&i.ServiceID,
		&i.Name,
		&i.Unit,
		&i.Qty,
		&i.UnitCost,
		&i.StockApplied,
		&i.RevertedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertServiceProduct = `-- name: InsertServiceProduct :exec
INSERT INTO service_products (organization_id, service_id, product_id, qty, sort_order)
VALUES ($1, $2, $3, $4, $5)
`

type InsertServiceProductParams struct {
	OrganizationID int64          `json:"organization_id"`
	ServiceID      int64          `json:"service_id"`
	ProductID      int64          `json:"product_id"`
	Qty            pgtype.Numeric `json:"qty"`
	SortOrder      int32          `json:"sort_order"`
}

func (q *Queries) InsertServiceProduct(ctx context.Context, arg InsertServiceProductParams) error {
	_, err := q.db.Exec(ctx, insertServiceProduct,
		arg.OrganizationID,
		arg.ServiceID,
		arg.ProductID,
		arg.Qty,
		arg.SortOrder,
	)
	return err
}

const listJobConsumptions = `-- name: ListJobConsumptions :many
SELECT c.id, c.uuid, c.organization_id, c.job_id, c.product_id, c.service_id, c.name, c.unit, c.qty, c.unit_cost, c.stock_applied, c.reverted_at, c.created_by, c.created_at, c.updated_at, p.uuid AS product_uuid, s.name AS service_name
FROM service_job_consumptions c
JOIN products p ON p.id = c.product_id
LEFT JOIN services s ON s.id = c.service_id
WHERE c.organization_id = $1 AND c.job_id = $2
ORDER BY c.id
`

type ListJobConsumptionsParams struct {
	OrganizationID int64 `json:"organization_id"`
	JobID          int64 `json:"job_id"`
}

type ListJobConsumptionsRow struct {
	ID             int64              `json:"id"`
	Uuid           uuid.UUID          `json:"uuid"`
	OrganizationID int64              `json:"organization_id"`
	JobID          int64              `json:"job_id"`
	ProductID      int64              `json:"product_id"`
	ServiceID      pgtype.Int8        `json:"service_id"`
	Name           string             `json:"name"`
	Unit           string             `json:"unit"`
	Qty            pgtype.Numeric     `json:"qty"`
	UnitCost       pgtype.Numeric     `json:"unit_cost"`
	StockApplied   bool               `json:"stock_applied"`
	RevertedAt     pgtype.Timestamptz `json:"reverted_at"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ProductUuid    uuid.UUID          `json:"product_uuid"`
	ServiceName    pgtype.Text        `json:"service_name"`
}

func (q *Queries) ListJobConsumptions(ctx context.Context, arg ListJobConsumptionsParams) ([]ListJobConsumptionsRow, error) {
	rows, err := q.db.Query(ctx, listJobConsumptions, arg.OrganizationID, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobConsumptionsRow{}
	for rows.Next() {
		var i ListJobConsumptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.JobID,
			&i.ProductID,
			&i.ServiceID,
			&i.Name,
			&i.Unit,
			&i.Qty,
			&i.UnitCost,
			&i.StockApplied,
			&i.RevertedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductUuid,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipesForServices = `-- name: ListRecipesForServices :many
SELECT sp.service_id, sp.qty, p.id AS product_id, p.name, p.unit, p.cost_price, p.track_stock
FROM service_products sp
JOIN products p ON p.id = sp.product_id AND p.deleted_at IS NULL
WHERE sp.organization_id = $1
  AND sp.service_id = ANY($2::bigint[])
ORDER BY sp.service_id, sp.sort_order, sp.id
`

type ListRecipesForServicesParams struct {
	OrganizationID int64   `json:"organization_id"`
	ServiceIds     []int64 `json:"service_ids"`
}

type ListRecipesForServicesRow struct {
	ServiceID  int64          `json:"service_id"`
	Qty        pgtype.Numeric `json:"qty"`
	ProductID  int64          `json:"product_id"`
	Name       string         `json:"name"`
	Unit       string         `json:"unit"`
	CostPrice  pgtype.Numeric `json:"cost_price"`
	TrackStock bool           `json:"track_stock"`
}

func (q *Queries) ListRecipesForServices(ctx context.Context, arg ListRecipesForServicesParams) ([]ListRecipesForServicesRow, error) {
	rows, err := q.db.Query(ctx, listRecipesForServices, arg.OrganizationID, arg.ServiceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecipesForServicesRow{}
	for rows.Next() {
		var i ListRecipesForServicesRow
		if err := rows.Scan(
			&i.ServiceID,
			&i.Qty,
			&i.ProductID,
			&i.Name,
			&i.Unit,
			&i.CostPrice,
			&i.TrackStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceProducts = `-- name: ListServiceProducts :many

SELECT sp.qty, sp.sort_order, p.id AS product_id, p.uuid AS product_uuid, p.name, p.unit,
       p.cost_price, p.track_stock, p.stock_quantity, p.is_active
FROM service_products sp
JOIN products p ON p.id = sp.product_id AND p.deleted_at IS NULL
WHERE sp.organization_id = $1 AND sp.service_id = $2
ORDER BY sp.sort_order, sp.id
`

type ListServiceProductsParams struct {
	OrganizationID int64 `json:"organization_id"`
	ServiceID      int64 `json:"service_id"`
}

type ListServiceProductsRow struct {
	Qty           pgtype.Numeric `json:"qty"`
	SortOrder     int32          `json:"sort_order"`
	ProductID     int64          `json:"product_id"`
	ProductUuid   uuid.UUID      `json:"product_uuid"`
	Name          string         `json:"name"`
	Unit          string         `json:"unit"`
	CostPrice     pgtype.Numeric `json:"cost_price"`
	TrackStock    bool           `json:"track_stock"`
	StockQuantity pgtype.Numeric `json:"stock_quantity"`
	IsActive      bool           `json:"is_active"`
}

// Service recipes (products a service uses) and per-job product usage.
func (q *Queries) ListServiceProducts(ctx context.Context, arg ListServiceProductsParams) ([]ListServiceProductsRow, error) {
	rows, err := q.db.Query(ctx, listServiceProducts, arg.OrganizationID, arg.ServiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceProductsRow{}
	for rows.Next() {
		var i ListServiceProductsRow
		if err := rows.Scan(
			&i.Qty,
			&i.SortOrder,
			&i.ProductID,
			&i.ProductUuid,
			&i.Name,
			&i.Unit,
			&i.CostPrice,
			&i.TrackStock,
			&i.StockQuantity,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revertJobConsumptions = `-- name: RevertJobConsumptions :many
UPDATE service_job_consumptions SET reverted_at = NOW()
WHERE organization_id = $1 AND job_id = $2 AND reverted_at IS NULL
RETURNING product_id, qty, stock_applied
`

type RevertJobConsumptionsParams struct {
	OrganizationID int64 `json:"organization_id"`
	JobID          int64 `json:"job_id"`
}

type RevertJobConsumptionsRow struct {
	ProductID    int64          `json:"product_id"`
	Qty          pgtype.Numeric `json:"qty"`
	StockApplied bool           `json:"stock_applied"`
}

// Marks the job's usage as given back; returns the rows whose stock must be restored.
func (q *Queries) RevertJobConsumptions(ctx context.Context, arg RevertJobConsumptionsParams) ([]RevertJobConsumptionsRow, error) {
	rows, err := q.db.Query(ctx, revertJobConsumptions, arg.OrganizationID, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevertJobConsumptionsRow{}
	for rows.Next() {
		var i RevertJobConsumptionsRow
		if err := rows.Scan(&i.ProductID, &i.Qty, &i.StockApplied); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobConsumptionQty = `-- name: UpdateJobConsumptionQty :one
UPDATE service_job_consumptions SET qty = $1
WHERE id = $2 AND organization_id = $3
RETURNING id, uuid, organization_id, job_id, product_id, service_id, name, unit, qty, unit_cost, stock_applied, reverted_at, created_by, created_at, updated_at
`

type UpdateJobConsumptionQtyParams struct {
	Qty            pgtype.Numeric `json:"qty"`
	ID             int64          `json:"id"`
	OrganizationID int64          `json:"organization_id"`
}

func (q *Queries) UpdateJobConsumptionQty(ctx context.Context, arg UpdateJobConsumptionQtyParams) (ServiceJobConsumption, error) {
	row := q.db.QueryRow(ctx, updateJobConsumptionQty, arg.Qty, arg.ID, arg.OrganizationID)
	var i ServiceJobConsumption
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.JobID,
		&i.ProductID,
		&i.ServiceID,
		&i.Name,
		&i.Unit,
		&i.Qty,
		&i.UnitCost,
		&i.StockApplied,
		&i.RevertedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
