// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countStorageActivity = `-- name: CountStorageActivity :one
SELECT COUNT(*)::bigint FROM storage_activity
WHERE object_key = $1
`

func (q *Queries) CountStorageActivity(ctx context.Context, objectKey string) (int64, error) {
	row := q.db.QueryRow(ctx, countStorageActivity, objectKey)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countStorageTrash = `-- name: CountStorageTrash :one
SELECT COUNT(*)::bigint FROM storage_trash
`

func (q *Queries) CountStorageTrash(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStorageTrash)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteStorageShare = `-- name: DeleteStorageShare :exec
DELETE FROM storage_shares WHERE uuid = $1
`

func (q *Queries) DeleteStorageShare(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStorageShare, argUuid)
	return err
}

const deleteStorageStar = `-- name: DeleteStorageStar :exec
DELETE FROM storage_stars
WHERE user_id = $1 AND object_key = $2
`

type DeleteStorageStarParams struct {
	UserID    int64  `json:"user_id"`
	ObjectKey string `json:"object_key"`
}

func (q *Queries) DeleteStorageStar(ctx context.Context, arg DeleteStorageStarParams) error {
	_, err := q.db.Exec(ctx, deleteStorageStar, arg.UserID, arg.ObjectKey)
	return err
}

const deleteStorageTrashByUUID = `-- name: DeleteStorageTrashByUUID :exec
DELETE FROM storage_trash WHERE uuid = $1
`

func (q *Queries) DeleteStorageTrashByUUID(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStorageTrashByUUID, argUuid)
	return err
}

const getStorageLinkBySlug = `-- name: GetStorageLinkBySlug :one
SELECT id, uuid, object_key, kind, slug, token_hash, expires_at, can_view, can_download, can_upload, created_by, revoked_at, created_at FROM storage_links
WHERE slug = $1 AND revoked_at IS NULL
`

func (q *Queries) GetStorageLinkBySlug(ctx context.Context, slug pgtype.Text) (StorageLink, error) {
	row := q.db.QueryRow(ctx, getStorageLinkBySlug, slug)
	var i StorageLink
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ObjectKey,
		&i.Kind,
		&i.Slug,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CanView,
		&i.CanDownload,
		&i.CanUpload,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStorageLinkByTokenHash = `-- name: GetStorageLinkByTokenHash :one
SELECT id, uuid, object_key, kind, slug, token_hash, expires_at, can_view, can_download, can_upload, created_by, revoked_at, created_at FROM storage_links
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetStorageLinkByTokenHash(ctx context.Context, tokenHash pgtype.Text) (StorageLink, error) {
	row := q.db.QueryRow(ctx, getStorageLinkByTokenHash, tokenHash)
	var i StorageLink
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ObjectKey,
		&i.Kind,
		&i.Slug,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CanView,
		&i.CanDownload,
		&i.CanUpload,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStorageLinkByUUID = `-- name: GetStorageLinkByUUID :one
SELECT id, uuid, object_key, kind, slug, token_hash, expires_at, can_view, can_download, can_upload, created_by, revoked_at, created_at FROM storage_links WHERE uuid = $1
`

func (q *Queries) GetStorageLinkByUUID(ctx context.Context, argUuid uuid.UUID) (StorageLink, error) {
	row := q.db.QueryRow(ctx, getStorageLinkByUUID, argUuid)
	var i StorageLink
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ObjectKey,
		&i.Kind,
		&i.Slug,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CanView,
		&i.CanDownload,
		&i.CanUpload,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStorageTrashByOriginalKey = `-- name: GetStorageTrashByOriginalKey :one
SELECT id, uuid, object_key, original_key, name, size_bytes, mime_type, deleted_by, deleted_at, expires_at FROM storage_trash
WHERE original_key = $1
ORDER BY deleted_at DESC
LIMIT 1
`

func (q *Queries) GetStorageTrashByOriginalKey(ctx context.Context, originalKey string) (StorageTrash, error) {
	row := q.db.QueryRow(ctx, getStorageTrashByOriginalKey, originalKey)
	var i StorageTrash
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ObjectKey,
		&i.OriginalKey,
		&i.Name,
		&i.SizeBytes,
		&i.MimeType,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getStorageTrashByUUID = `-- name: GetStorageTrashByUUID :one
SELECT id, uuid, object_key, original_key, name, size_bytes, mime_type, deleted_by, deleted_at, expires_at FROM storage_trash
WHERE uuid = $1
`

func (q *Queries) GetStorageTrashByUUID(ctx context.Context, argUuid uuid.UUID) (StorageTrash, error) {
	row := q.db.QueryRow(ctx, getStorageTrashByUUID, argUuid)
	var i StorageTrash
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ObjectKey,
		&i.OriginalKey,
		&i.Name,
		&i.SizeBytes,
		&i.MimeType,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertStorageActivity = `-- name: InsertStorageActivity :one
INSERT INTO storage_activity (object_key, actor_user_id, action, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, uuid, object_key, actor_user_id, action, payload, created_at
`

type InsertStorageActivityParams struct {
	ObjectKey   string      `json:"object_key"`
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	Action      string      `json:"action"`
	Payload     []byte      `json:"payload"`
}

func (q *Queries) InsertStorageActivity(ctx context.Context, arg InsertStorageActivityParams) (StorageActivity, error) {
	row := q.db.QueryRow(ctx, insertStorageActivity,
		arg.ObjectKey,
		arg.ActorUserID,
		arg.Action,
		arg.Payload,
	)
	var i StorageActivity
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ObjectKey,
		&i.ActorUserID,
		&i.Action,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const insertStorageLink = `-- name: InsertStorageLink :one
INSERT INTO storage_links (
    object_key, kind, slug, token_hash, expires_at,
    can_view, can_download, can_upload, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, uuid, object_key, kind, slug, token_hash, expires_at, can_view, can_download, can_upload, created_by, revoked_at, created_at
`

type InsertStorageLinkParams struct {
	ObjectKey   string             `json:"object_key"`
	Kind        string             `json:"kind"`
	Slug        pgtype.Text        `json:"slug"`
	TokenHash   pgtype.Text        `json:"token_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CanView     bool               `json:"can_view"`
	CanDownload bool               `json:"can_download"`
	CanUpload   bool               `json:"can_upload"`
	CreatedBy   pgtype.Int8        `json:"created_by"`
}

func (q *Queries) InsertStorageLink(ctx context.Context, arg InsertStorageLinkParams) (StorageLink, error) {
	row := q.db.QueryRow(ctx, insertStorageLink,
		arg.ObjectKey,
		arg.Kind,
		arg.Slug,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CanView,
		arg.CanDownload,
		arg.CanUpload,
		arg.CreatedBy,
	)
	var i StorageLink
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ObjectKey,
		&i.Kind,
		&i.Slug,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CanView,
		&i.CanDownload,
		&i.CanUpload,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertStorageShare = `-- name: InsertStorageShare :one
INSERT INTO storage_shares (object_key, user_id, role, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (object_key, user_id) DO UPDATE SET role = EXCLUDED.role
RETURNING id, uuid, object_key, user_id, role, created_by, created_at
`

type InsertStorageShareParams struct {
	ObjectKey string      `json:"object_key"`
	UserID    int64       `json:"user_id"`
	Role      string      `json:"role"`
	CreatedBy pgtype.Int8 `json:"created_by"`
}

func (q *Queries) InsertStorageShare(ctx context.Context, arg InsertStorageShareParams) (StorageShare, error) {
	row := q.db.QueryRow(ctx, insertStorageShare,
		arg.ObjectKey,
		arg.UserID,
		arg.Role,
		arg.CreatedBy,
	)
	var i StorageShare
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ObjectKey,
		&i.UserID,
		&i.Role,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertStorageStar = `-- name: InsertStorageStar :one
INSERT INTO storage_stars (user_id, object_key)
VALUES ($1, $2)
ON CONFLICT (user_id, object_key) DO UPDATE SET object_key = EXCLUDED.object_key
RETURNING id, uuid, user_id, object_key, created_at
`

type InsertStorageStarParams struct {
	UserID    int64  `json:"user_id"`
	ObjectKey string `json:"object_key"`
}

func (q *Queries) InsertStorageStar(ctx context.Context, arg InsertStorageStarParams) (StorageStar, error) {
	row := q.db.QueryRow(ctx, insertStorageStar, arg.UserID, arg.ObjectKey)
	var i StorageStar
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.ObjectKey,
		&i.CreatedAt,
	)
	return i, err
}

const insertStorageTrash = `-- name: InsertStorageTrash :one
INSERT INTO storage_trash (object_key, original_key, name, size_bytes, mime_type, deleted_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, uuid, object_key, original_key, name, size_bytes, mime_type, deleted_by, deleted_at, expires_at
`

type InsertStorageTrashParams struct {
	ObjectKey   string             `json:"object_key"`
	OriginalKey string             `json:"original_key"`
	Name        string             `json:"name"`
	SizeBytes   int64              `json:"size_bytes"`
	MimeType    string             `json:"mime_type"`
	DeletedBy   pgtype.Int8        `json:"deleted_by"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertStorageTrash(ctx context.Context, arg InsertStorageTrashParams) (StorageTrash, error) {
	row := q.db.QueryRow(ctx, insertStorageTrash,
		arg.ObjectKey,
		arg.OriginalKey,
		arg.Name,
		arg.SizeBytes,
		arg.MimeType,
		arg.DeletedBy,
		arg.ExpiresAt,
	)
	var i StorageTrash
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ObjectKey,
		&i.OriginalKey,
		&i.Name,
		&i.SizeBytes,
		&i.MimeType,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listActivePublicKeys = `-- name: ListActivePublicKeys :many
SELECT DISTINCT object_key FROM storage_links
WHERE kind = 'public'
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
  AND object_key = ANY($1::text[])
`

func (q *Queries) ListActivePublicKeys(ctx context.Context, keys []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listActivePublicKeys, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePublicLinks = `-- name: ListActivePublicLinks :many
SELECT id, uuid, object_key, kind, slug, token_hash, expires_at, can_view, can_download, can_upload, created_by, revoked_at, created_at FROM storage_links
WHERE kind = 'public'
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) ListActivePublicLinks(ctx context.Context) ([]StorageLink, error) {
	rows, err := q.db.Query(ctx, listActivePublicLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageLink{}
	for rows.Next() {
		var i StorageLink
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ObjectKey,
			&i.Kind,
			&i.Slug,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.CanView,
			&i.CanDownload,
			&i.CanUpload,
			&i.CreatedBy,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedKeys = `-- name: ListSharedKeys :many
SELECT DISTINCT object_key FROM storage_shares
WHERE object_key = ANY($1::text[])
`

func (q *Queries) ListSharedKeys(ctx context.Context, keys []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listSharedKeys, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageActivity = `-- name: ListStorageActivity :many
SELECT a.id, a.uuid, a.object_key, a.actor_user_id, a.action, a.payload, a.created_at, u.name AS actor_name, u.surname AS actor_surname, u.email AS actor_email
FROM storage_activity a
LEFT JOIN users u ON u.id = a.actor_user_id
WHERE a.object_key = $1
ORDER BY a.created_at DESC
LIMIT $3 OFFSET $2
`

type ListStorageActivityParams struct {
	ObjectKey   string `json:"object_key"`
	OffsetCount int32  `json:"offset_count"`
	LimitCount  int32  `json:"limit_count"`
}

type ListStorageActivityRow struct {
	ID           int64              `json:"id"`
	Uuid         uuid.UUID          `json:"uuid"`
	ObjectKey    string             `json:"object_key"`
	ActorUserID  pgtype.Int8        `json:"actor_user_id"`
	Action       string             `json:"action"`
	Payload      []byte             `json:"payload"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ActorName    pgtype.Text        `json:"actor_name"`
	ActorSurname pgtype.Text        `json:"actor_surname"`
	ActorEmail   pgtype.Text        `json:"actor_email"`
}

func (q *Queries) ListStorageActivity(ctx context.Context, arg ListStorageActivityParams) ([]ListStorageActivityRow, error) {
	rows, err := q.db.Query(ctx, listStorageActivity, arg.ObjectKey, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStorageActivityRow{}
	for rows.Next() {
		var i ListStorageActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ObjectKey,
			&i.ActorUserID,
			&i.Action,
			&i.Payload,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorSurname,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageLinksByKey = `-- name: ListStorageLinksByKey :many
SELECT id, uuid, object_key, kind, slug, token_hash, expires_at, can_view, can_download, can_upload, created_by, revoked_at, created_at FROM storage_links
WHERE object_key = $1
ORDER BY created_at DESC
`

func (q *Queries) ListStorageLinksByKey(ctx context.Context, objectKey string) ([]StorageLink, error) {
	rows, err := q.db.Query(ctx, listStorageLinksByKey, objectKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageLink{}
	for rows.Next() {
		var i StorageLink
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ObjectKey,
			&i.Kind,
			&i.Slug,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.CanView,
			&i.CanDownload,
			&i.CanUpload,
			&i.CreatedBy,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageSharesByKey = `-- name: ListStorageSharesByKey :many
SELECT s.id, s.uuid, s.object_key, s.user_id, s.role, s.created_by, s.created_at, u.uuid AS user_uuid, u.name AS user_name, u.surname AS user_surname, u.email AS user_email
FROM storage_shares s
INNER JOIN users u ON u.id = s.user_id
WHERE s.object_key = $1
ORDER BY s.created_at ASC
`

type ListStorageSharesByKeyRow struct {
	ID          int64              `json:"id"`
	Uuid        uuid.UUID          `json:"uuid"`
	ObjectKey   string             `json:"object_key"`
	UserID      int64              `json:"user_id"`
	Role        string             `json:"role"`
	CreatedBy   pgtype.Int8        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UserUuid    uuid.UUID          `json:"user_uuid"`
	UserName    string             `json:"user_name"`
	UserSurname string             `json:"user_surname"`
	UserEmail   string             `json:"user_email"`
}

func (q *Queries) ListStorageSharesByKey(ctx context.Context, objectKey string) ([]ListStorageSharesByKeyRow, error) {
	rows, err := q.db.Query(ctx, listStorageSharesByKey, objectKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStorageSharesByKeyRow{}
	for rows.Next() {
		var i ListStorageSharesByKeyRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ObjectKey,
			&i.UserID,
			&i.Role,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UserUuid,
			&i.UserName,
			&i.UserSurname,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageSharesForUser = `-- name: ListStorageSharesForUser :many
SELECT id, uuid, object_key, user_id, role, created_by, created_at FROM storage_shares
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListStorageSharesForUser(ctx context.Context, userID int64) ([]StorageShare, error) {
	rows, err := q.db.Query(ctx, listStorageSharesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageShare{}
	for rows.Next() {
		var i StorageShare
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ObjectKey,
			&i.UserID,
			&i.Role,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageStarsByKeys = `-- name: ListStorageStarsByKeys :many
SELECT id, uuid, user_id, object_key, created_at FROM storage_stars
WHERE user_id = $1 AND object_key = ANY($2::text[])
`

type ListStorageStarsByKeysParams struct {
	UserID int64    `json:"user_id"`
	Keys   []string `json:"keys"`
}

func (q *Queries) ListStorageStarsByKeys(ctx context.Context, arg ListStorageStarsByKeysParams) ([]StorageStar, error) {
	rows, err := q.db.Query(ctx, listStorageStarsByKeys, arg.UserID, arg.Keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageStar{}
	for rows.Next() {
		var i StorageStar
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.ObjectKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageStarsByUser = `-- name: ListStorageStarsByUser :many
SELECT id, uuid, user_id, object_key, created_at FROM storage_stars
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListStorageStarsByUser(ctx context.Context, userID int64) ([]StorageStar, error) {
	rows, err := q.db.Query(ctx, listStorageStarsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageStar{}
	for rows.Next() {
		var i StorageStar
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.ObjectKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageTrash = `-- name: ListStorageTrash :many
SELECT id, uuid, object_key, original_key, name, size_bytes, mime_type, deleted_by, deleted_at, expires_at FROM storage_trash
ORDER BY deleted_at DESC
LIMIT $2 OFFSET $1
`

type ListStorageTrashParams struct {
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListStorageTrash(ctx context.Context, arg ListStorageTrashParams) ([]StorageTrash, error) {
	rows, err := q.db.Query(ctx, listStorageTrash, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageTrash{}
	for rows.Next() {
		var i StorageTrash
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ObjectKey,
			&i.OriginalKey,
			&i.Name,
			&i.SizeBytes,
			&i.MimeType,
			&i.DeletedBy,
			&i.DeletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeStorageLink = `-- name: RevokeStorageLink :one
UPDATE storage_links
SET revoked_at = NOW()
WHERE uuid = $1
RETURNING id, uuid, object_key, kind, slug, token_hash, expires_at, can_view, can_download, can_upload, created_by, revoked_at, created_at
`

func (q *Queries) RevokeStorageLink(ctx context.Context, argUuid uuid.UUID) (StorageLink, error) {
	row := q.db.QueryRow(ctx, revokeStorageLink, argUuid)
	var i StorageLink
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ObjectKey,
		&i.Kind,
		&i.Slug,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CanView,
		&i.CanDownload,
		&i.CanUpload,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
