// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suppliers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPostedPurchasesBySupplier = `-- name: CountPostedPurchasesBySupplier :one
SELECT COUNT(*)::bigint
FROM purchases
WHERE supplier_id = $1 AND organization_id = $2 AND status = 'posted'
`

type CountPostedPurchasesBySupplierParams struct {
	SupplierID     int64 `json:"supplier_id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) CountPostedPurchasesBySupplier(ctx context.Context, arg CountPostedPurchasesBySupplierParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPostedPurchasesBySupplier, arg.SupplierID, arg.OrganizationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSuppliers = `-- name: CountSuppliers :one
SELECT COUNT(*)::bigint
FROM suppliers
WHERE organization_id = $1 AND deleted_at IS NULL
  AND ($2::boolean IS NULL OR is_active = $2)
  AND (
    $3::text IS NULL
    OR name ILIKE '%' || $3 || '%'
    OR phone ILIKE '%' || $3 || '%'
    OR email ILIKE '%' || $3 || '%'
    OR tax_id ILIKE '%' || $3 || '%'
  )
`

type CountSuppliersParams struct {
	OrganizationID int64       `json:"organization_id"`
	IsActive       pgtype.Bool `json:"is_active"`
	Q              pgtype.Text `json:"q"`
}

func (q *Queries) CountSuppliers(ctx context.Context, arg CountSuppliersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppliers, arg.OrganizationID, arg.IsActive, arg.Q)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createSupplier = `-- name: CreateSupplier :one

INSERT INTO suppliers (
    organization_id, name, phone, email, tax_id, notes, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, uuid, organization_id, name, phone, email, tax_id, notes, is_active, created_at, updated_at, deleted_at
`

type CreateSupplierParams struct {
	OrganizationID int64  `json:"organization_id"`
	Name           string `json:"name"`
	Phone          string `json:"phone"`
	Email          string `json:"email"`
	TaxID          string `json:"tax_id"`
	Notes          string `json:"notes"`
	IsActive       bool   `json:"is_active"`
}

// Tenant suppliers (firmalar).
func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.OrganizationID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.TaxID,
		arg.Notes,
		arg.IsActive,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.TaxID,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSupplierByUUID = `-- name: GetSupplierByUUID :one
SELECT id, uuid, organization_id, name, phone, email, tax_id, notes, is_active, created_at, updated_at, deleted_at FROM suppliers
WHERE uuid = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type GetSupplierByUUIDParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) GetSupplierByUUID(ctx context.Context, arg GetSupplierByUUIDParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByUUID, arg.Uuid, arg.OrganizationID)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.TaxID,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSupplierForSearch = `-- name: GetSupplierForSearch :one
SELECT s.uuid, s.name, s.phone, s.email, s.tax_id, s.is_active,
       o.uuid AS organization_uuid, o.slug AS organization_slug
FROM suppliers s
JOIN organizations o ON o.id = s.organization_id
WHERE s.uuid = $1 AND o.uuid = $2 AND s.deleted_at IS NULL
`

type GetSupplierForSearchParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	Uuid_2 uuid.UUID `json:"uuid_2"`
}

type GetSupplierForSearchRow struct {
	Uuid             uuid.UUID `json:"uuid"`
	Name             string    `json:"name"`
	Phone            string    `json:"phone"`
	Email            string    `json:"email"`
	TaxID            string    `json:"tax_id"`
	IsActive         bool      `json:"is_active"`
	OrganizationUuid uuid.UUID `json:"organization_uuid"`
	OrganizationSlug string    `json:"organization_slug"`
}

func (q *Queries) GetSupplierForSearch(ctx context.Context, arg GetSupplierForSearchParams) (GetSupplierForSearchRow, error) {
	row := q.db.QueryRow(ctx, getSupplierForSearch, arg.Uuid, arg.Uuid_2)
	var i GetSupplierForSearchRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.TaxID,
		&i.IsActive,
		&i.OrganizationUuid,
		&i.OrganizationSlug,
	)
	return i, err
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, uuid, organization_id, name, phone, email, tax_id, notes, is_active, created_at, updated_at, deleted_at
FROM suppliers
WHERE organization_id = $1 AND deleted_at IS NULL
  AND ($2::boolean IS NULL OR is_active = $2)
  AND (
    $3::text IS NULL
    OR name ILIKE '%' || $3 || '%'
    OR phone ILIKE '%' || $3 || '%'
    OR email ILIKE '%' || $3 || '%'
    OR tax_id ILIKE '%' || $3 || '%'
  )
ORDER BY
    CASE WHEN $4::text = 'name' THEN name END ASC,
    CASE WHEN $4::text = '-name' THEN name END DESC,
    CASE WHEN $4::text = 'created_at' THEN created_at END ASC,
    CASE WHEN $4::text = '-created_at' THEN created_at END DESC,
    name ASC
LIMIT $6 OFFSET $5
`

type ListSuppliersParams struct {
	OrganizationID int64       `json:"organization_id"`
	IsActive       pgtype.Bool `json:"is_active"`
	Q              pgtype.Text `json:"q"`
	Sort           string      `json:"sort"`
	OffsetCount    int32       `json:"offset_count"`
	LimitCount     int32       `json:"limit_count"`
}

func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliers,
		arg.OrganizationID,
		arg.IsActive,
		arg.Q,
		arg.Sort,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.TaxID,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppliersForExport = `-- name: ListSuppliersForExport :many
SELECT id, uuid, organization_id, name, phone, email, tax_id, notes, is_active, created_at, updated_at, deleted_at
FROM suppliers
WHERE organization_id = $1 AND deleted_at IS NULL
  AND ($2::boolean IS NULL OR is_active = $2)
  AND (
    $3::text IS NULL
    OR name ILIKE '%' || $3 || '%'
    OR phone ILIKE '%' || $3 || '%'
  )
ORDER BY name ASC
`

type ListSuppliersForExportParams struct {
	OrganizationID int64       `json:"organization_id"`
	IsActive       pgtype.Bool `json:"is_active"`
	Q              pgtype.Text `json:"q"`
}

func (q *Queries) ListSuppliersForExport(ctx context.Context, arg ListSuppliersForExportParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliersForExport, arg.OrganizationID, arg.IsActive, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrganizationID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.TaxID,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppliersForSearch = `-- name: ListSuppliersForSearch :many
SELECT s.uuid, s.name, s.phone, s.email, s.tax_id, s.is_active,
       o.uuid AS organization_uuid, o.slug AS organization_slug
FROM suppliers s
JOIN organizations o ON o.id = s.organization_id
WHERE s.deleted_at IS NULL AND s.is_active = true
ORDER BY s.name ASC
LIMIT 5000
`

type ListSuppliersForSearchRow struct {
	Uuid             uuid.UUID `json:"uuid"`
	Name             string    `json:"name"`
	Phone            string    `json:"phone"`
	Email            string    `json:"email"`
	TaxID            string    `json:"tax_id"`
	IsActive         bool      `json:"is_active"`
	OrganizationUuid uuid.UUID `json:"organization_uuid"`
	OrganizationSlug string    `json:"organization_slug"`
}

func (q *Queries) ListSuppliersForSearch(ctx context.Context) ([]ListSuppliersForSearchRow, error) {
	rows, err := q.db.Query(ctx, listSuppliersForSearch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSuppliersForSearchRow{}
	for rows.Next() {
		var i ListSuppliersForSearchRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.TaxID,
			&i.IsActive,
			&i.OrganizationUuid,
			&i.OrganizationSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSupplier = `-- name: SoftDeleteSupplier :one
UPDATE suppliers
SET deleted_at = NOW(), is_active = false
WHERE uuid = $1 AND organization_id = $2 AND deleted_at IS NULL
RETURNING id, uuid, organization_id, name, phone, email, tax_id, notes, is_active, created_at, updated_at, deleted_at
`

type SoftDeleteSupplierParams struct {
	Uuid           uuid.UUID `json:"uuid"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) SoftDeleteSupplier(ctx context.Context, arg SoftDeleteSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, softDeleteSupplier, arg.Uuid, arg.OrganizationID)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.TaxID,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers
SET name = COALESCE($1, name),
    phone = COALESCE($2, phone),
    email = COALESCE($3, email),
    tax_id = COALESCE($4, tax_id),
    notes = COALESCE($5, notes),
    is_active = COALESCE($6, is_active)
WHERE uuid = $7 AND organization_id = $8 AND deleted_at IS NULL
RETURNING id, uuid, organization_id, name, phone, email, tax_id, notes, is_active, created_at, updated_at, deleted_at
`

type UpdateSupplierParams struct {
	Name           pgtype.Text `json:"name"`
	Phone          pgtype.Text `json:"phone"`
	Email          pgtype.Text `json:"email"`
	TaxID          pgtype.Text `json:"tax_id"`
	Notes          pgtype.Text `json:"notes"`
	IsActive       pgtype.Bool `json:"is_active"`
	Uuid           uuid.UUID   `json:"uuid"`
	OrganizationID int64       `json:"organization_id"`
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.TaxID,
		arg.Notes,
		arg.IsActive,
		arg.Uuid,
		arg.OrganizationID,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrganizationID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.TaxID,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
