// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn_credentials.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :one
INSERT INTO webauthn_credentials (
    user_id,
    credential_id,
    public_key,
    counter,
    device_type,
    backed_up,
    transports,
    provider_account_id,
    name
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, uuid, user_id, credential_id, public_key, counter, device_type, backed_up, transports, provider_account_id, name, last_used_at, created_at, updated_at
`

type CreateWebAuthnCredentialParams struct {
	UserID            int64       `json:"user_id"`
	CredentialID      string      `json:"credential_id"`
	PublicKey         string      `json:"public_key"`
	Counter           int64       `json:"counter"`
	DeviceType        string      `json:"device_type"`
	BackedUp          bool        `json:"backed_up"`
	Transports        pgtype.Text `json:"transports"`
	ProviderAccountID string      `json:"provider_account_id"`
	Name              pgtype.Text `json:"name"`
}

func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, createWebAuthnCredential,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.Counter,
		arg.DeviceType,
		arg.BackedUp,
		arg.Transports,
		arg.ProviderAccountID,
		arg.Name,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.Counter,
		&i.DeviceType,
		&i.BackedUp,
		&i.Transports,
		&i.ProviderAccountID,
		&i.Name,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebAuthnCredentialByCredentialID = `-- name: DeleteWebAuthnCredentialByCredentialID :exec
DELETE FROM webauthn_credentials
WHERE credential_id = $1
`

func (q *Queries) DeleteWebAuthnCredentialByCredentialID(ctx context.Context, credentialID string) error {
	_, err := q.db.Exec(ctx, deleteWebAuthnCredentialByCredentialID, credentialID)
	return err
}

const deleteWebAuthnCredentialByUUID = `-- name: DeleteWebAuthnCredentialByUUID :exec
DELETE FROM webauthn_credentials wc
USING users u
WHERE wc.uuid = $1
  AND wc.user_id = u.id
  AND u.uuid = $2
  AND u.deleted_at IS NULL
`

type DeleteWebAuthnCredentialByUUIDParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	Uuid_2 uuid.UUID `json:"uuid_2"`
}

func (q *Queries) DeleteWebAuthnCredentialByUUID(ctx context.Context, arg DeleteWebAuthnCredentialByUUIDParams) error {
	_, err := q.db.Exec(ctx, deleteWebAuthnCredentialByUUID, arg.Uuid, arg.Uuid_2)
	return err
}

const getWebAuthnCredentialByCredentialID = `-- name: GetWebAuthnCredentialByCredentialID :one
SELECT id, uuid, user_id, credential_id, public_key, counter, device_type, backed_up, transports, provider_account_id, name, last_used_at, created_at, updated_at
FROM webauthn_credentials
WHERE credential_id = $1
`

func (q *Queries) GetWebAuthnCredentialByCredentialID(ctx context.Context, credentialID string) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredentialByCredentialID, credentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.Counter,
		&i.DeviceType,
		&i.BackedUp,
		&i.Transports,
		&i.ProviderAccountID,
		&i.Name,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebAuthnCredentialByUUID = `-- name: GetWebAuthnCredentialByUUID :one
SELECT wc.id, wc.uuid, wc.user_id, wc.credential_id, wc.public_key, wc.counter, wc.device_type, wc.backed_up, wc.transports, wc.provider_account_id, wc.name, wc.last_used_at, wc.created_at, wc.updated_at
FROM webauthn_credentials wc
INNER JOIN users u ON u.id = wc.user_id
WHERE wc.uuid = $1
  AND u.uuid = $2
  AND u.deleted_at IS NULL
`

type GetWebAuthnCredentialByUUIDParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	Uuid_2 uuid.UUID `json:"uuid_2"`
}

func (q *Queries) GetWebAuthnCredentialByUUID(ctx context.Context, arg GetWebAuthnCredentialByUUIDParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredentialByUUID, arg.Uuid, arg.Uuid_2)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.Counter,
		&i.DeviceType,
		&i.BackedUp,
		&i.Transports,
		&i.ProviderAccountID,
		&i.Name,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebAuthnCredentialsByUserID = `-- name: ListWebAuthnCredentialsByUserID :many
SELECT id, uuid, user_id, credential_id, public_key, counter, device_type, backed_up, transports, provider_account_id, name, last_used_at, created_at, updated_at
FROM webauthn_credentials
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebAuthnCredentialsByUserID(ctx context.Context, userID int64) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listWebAuthnCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredential{}
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.Counter,
			&i.DeviceType,
			&i.BackedUp,
			&i.Transports,
			&i.ProviderAccountID,
			&i.Name,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebAuthnCredentialsForUserIDs = `-- name: ListWebAuthnCredentialsForUserIDs :many
SELECT id, uuid, user_id, credential_id, public_key, counter, device_type, backed_up, transports, provider_account_id, name, last_used_at, created_at, updated_at
FROM webauthn_credentials
WHERE user_id = ANY ($1::bigint[])
ORDER BY user_id, created_at ASC
`

func (q *Queries) ListWebAuthnCredentialsForUserIDs(ctx context.Context, userIds []int64) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listWebAuthnCredentialsForUserIDs, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredential{}
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.Counter,
			&i.DeviceType,
			&i.BackedUp,
			&i.Transports,
			&i.ProviderAccountID,
			&i.Name,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebAuthnCredentialCounter = `-- name: UpdateWebAuthnCredentialCounter :exec
UPDATE webauthn_credentials
SET counter = $2,
    last_used_at = NOW()
WHERE credential_id = $1
`

type UpdateWebAuthnCredentialCounterParams struct {
	CredentialID string `json:"credential_id"`
	Counter      int64  `json:"counter"`
}

func (q *Queries) UpdateWebAuthnCredentialCounter(ctx context.Context, arg UpdateWebAuthnCredentialCounterParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnCredentialCounter, arg.CredentialID, arg.Counter)
	return err
}

const updateWebAuthnCredentialName = `-- name: UpdateWebAuthnCredentialName :one
UPDATE webauthn_credentials wc
SET name = $3
FROM users u
WHERE wc.uuid = $1
  AND wc.user_id = u.id
  AND u.uuid = $2
  AND u.deleted_at IS NULL
RETURNING wc.id, wc.uuid, wc.user_id, wc.credential_id, wc.public_key, wc.counter, wc.device_type, wc.backed_up, wc.transports, wc.provider_account_id, wc.name, wc.last_used_at, wc.created_at, wc.updated_at
`

type UpdateWebAuthnCredentialNameParams struct {
	Uuid   uuid.UUID   `json:"uuid"`
	Uuid_2 uuid.UUID   `json:"uuid_2"`
	Name   pgtype.Text `json:"name"`
}

func (q *Queries) UpdateWebAuthnCredentialName(ctx context.Context, arg UpdateWebAuthnCredentialNameParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, updateWebAuthnCredentialName, arg.Uuid, arg.Uuid_2, arg.Name)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.Counter,
		&i.DeviceType,
		&i.BackedUp,
		&i.Transports,
		&i.ProviderAccountID,
		&i.Name,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
