package rbac

// Role slugs (seeded).
const (
	RoleSuperAdmin        = "super_admin"
	RoleOrganizationUser  = "organization_user"
	RoleOrganizationOwner = "organization_owner"
)

// Permission slugs (seeded).
const (
	PermPlatformUsersRead                       = "platform.users.read"
	PermPlatformUsersWrite                      = "platform.users.write"
	PermPlatformUsersExport                     = "platform.users.export"
	PermPlatformUsersImport                     = "platform.users.import"
	PermPlatformUsersBulkDisable                = "platform.users.bulk.disable"
	PermPlatformUsersBulkEnable                 = "platform.users.bulk.enable"
	PermPlatformUsersImpersonate                = "platform.users.impersonate"
	PermPlatformRolesRead                       = "platform.roles.read"
	PermPlatformRolesWrite                      = "platform.roles.write"
	PermPlatformRolesExport                     = "platform.roles.export"
	PermPlatformRolesImport                     = "platform.roles.import"
	PermPlatformRolesBulkDelete                 = "platform.roles.bulk.delete"
	PermPlatformBulkRead                        = "platform.bulk.read"
	PermPlatformNotificationsRead               = "platform.notifications.read"
	PermPlatformNotificationsReadAll            = "platform.notifications.read_all"
	PermPlatformNotificationsExport             = "platform.notifications.export"
	PermPlatformSettingsRead                    = "platform.settings.read"
	PermPlatformSettingsWrite                   = "platform.settings.write"
	PermPlatformActivityRead                    = "platform.activity.read"
	PermPlatformImportsRead                     = "platform.imports.read"
	PermPlatformExportsRead                     = "platform.exports.read"
	PermPlatformStorageRead                     = "platform.storage.read"
	PermPlatformStorageWrite                    = "platform.storage.write"
	PermPlatformLogsRead                        = "platform.logs.read"
	PermPlatformLogsWrite                       = "platform.logs.write"
	PermPlatformAccessRead                      = "platform.access.read"
	PermPlatformAccessWrite                     = "platform.access.write"
	PermPlatformIntegrationsGitHubRead          = "platform.integrations.github.read"
	PermPlatformIntegrationsGitHubWrite         = "platform.integrations.github.write"
	PermPlatformIntegrationsGoogleRead          = "platform.integrations.google.read"
	PermPlatformIntegrationsGoogleWrite         = "platform.integrations.google.write"
	PermPlatformIntegrationsFacebookRead        = "platform.integrations.facebook.read"
	PermPlatformIntegrationsFacebookWrite       = "platform.integrations.facebook.write"
	PermPlatformIntegrationsAppleRead           = "platform.integrations.apple.read"
	PermPlatformIntegrationsAppleWrite          = "platform.integrations.apple.write"
	PermPlatformAuthSettingsRead                = "platform.auth.settings.read"
	PermPlatformAuthSettingsWrite               = "platform.auth.settings.write"
	PermPlatformOrganizationsRead               = "platform.organizations.read"
	PermPlatformOrganizationsWrite              = "platform.organizations.write"
	PermAuthSession                             = "auth.session"
	PermNotificationsRead                       = "notifications.read"
	PermNotificationsManage                     = "notifications.manage"
	PermTenantFinanceRead                       = "tenant.finance.read"
	PermTenantFinanceWrite                      = "tenant.finance.write"
	PermTenantFinanceExport                     = "tenant.finance.export"
	PermTenantFinanceImport                     = "tenant.finance.import"
	PermTenantSettingsRead                      = "tenant.settings.read"
	PermTenantSettingsWrite                     = "tenant.settings.write"
	PermTenantImportsRead                       = "tenant.imports.read"
	PermTenantCatalogRead                       = "tenant.catalog.read"
	PermTenantCatalogWrite                      = "tenant.catalog.write"
	PermTenantCatalogExport                     = "tenant.catalog.export"
	PermTenantCatalogImport                     = "tenant.catalog.import"
	PermTenantCatalogProductsBulkActivate       = "tenant.catalog.products.bulk.activate"
	PermTenantCatalogProductsBulkDeactivate     = "tenant.catalog.products.bulk.deactivate"
	PermTenantCatalogProductsBulkDelete         = "tenant.catalog.products.bulk.delete"
	PermTenantCatalogProductsBulkRaiseSalePrice = "tenant.catalog.products.bulk.raise_sale_price"
	PermTenantCatalogProductsBulkRaiseCostPrice = "tenant.catalog.products.bulk.raise_cost_price"
	PermTenantCatalogProductsBulkAdjustStock    = "tenant.catalog.products.bulk.adjust_stock"
	PermTenantCatalogServicesBulkActivate       = "tenant.catalog.services.bulk.activate"
	PermTenantCatalogServicesBulkDeactivate     = "tenant.catalog.services.bulk.deactivate"
	PermTenantCatalogServicesBulkDelete         = "tenant.catalog.services.bulk.delete"
	PermTenantCatalogServicesBulkRaisePrice     = "tenant.catalog.services.bulk.raise_price"
	PermPlatformVehicleBrandsRead               = "platform.vehicle_brands.read"
	PermPlatformVehicleBrandsWrite              = "platform.vehicle_brands.write"
	PermPlatformContractPresetsRead             = "platform.contract_presets.read"
	PermPlatformContractPresetsWrite            = "platform.contract_presets.write"
	PermTenantCustomersRead                     = "tenant.customers.read"
	PermTenantCustomersWrite                    = "tenant.customers.write"
	PermTenantCariRead                          = "tenant.cari.read"
	PermTenantCariWrite                         = "tenant.cari.write"
	PermTenantCariExport                        = "tenant.cari.export"
	PermTenantJobsRead                          = "tenant.jobs.read"
	PermTenantJobsWrite                         = "tenant.jobs.write"
	PermTenantJobsExport                        = "tenant.jobs.export"
	PermTenantSalesRead                         = "tenant.sales.read"
	PermTenantSalesWrite                        = "tenant.sales.write"
	PermTenantSalesExport                       = "tenant.sales.export"
	PermTenantSuppliersRead                     = "tenant.suppliers.read"
	PermTenantSuppliersWrite                    = "tenant.suppliers.write"
	PermTenantSuppliersExport                   = "tenant.suppliers.export"
	PermTenantPurchasesRead                     = "tenant.purchases.read"
	PermTenantPurchasesWrite                    = "tenant.purchases.write"
	PermTenantPurchasesExport                   = "tenant.purchases.export"
	PermTenantReportsRead                       = "tenant.reports.read"
	PermTenantReportsExport                     = "tenant.reports.export"
	PermTenantContractsRead                     = "tenant.contracts.read"
	PermTenantContractsWrite                    = "tenant.contracts.write"
	PermTenantMessagingRead                     = "tenant.messaging.read"
	PermTenantMessagingWrite                    = "tenant.messaging.write"
	PermTenantStaffRead                         = "tenant.staff.read"
	PermTenantStaffWrite                        = "tenant.staff.write"
	PermPlatformAIRead                          = "platform.ai.read"
	PermPlatformAIWrite                         = "platform.ai.write"
	PermTenantAIUse                             = "tenant.ai.use"
)

// IsSystemRole reports whether slug is a protected system role.
func IsSystemRole(slug string) bool {
	switch slug {
	case RoleSuperAdmin, RoleOrganizationUser, RoleOrganizationOwner:
		return true
	default:
		return false
	}
}
